### ISSUE TITLE
Missing IteratorStateMachineAttribute when making a method async during EnC

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#11704]
**Version Used**: 
D14Rel 25401.00
**Steps to Reproduce**:

```
using System;
using System.Threading.Tasks;

class Program
{
    static void Main(string[] args)
    {
        var x = G().Result;
        Console.WriteLine(x);

        Console.ReadLine();
    }

    static Task<int> G()
    {
        Console.WriteLine(10);
        return Task.FromResult(20);
    }
}
```

1. Create a C# console Application, and change editor text to the above
2. Make a breakpoint at the start of Main
3. Start debugging, and the breakpoint change the following
```
static Task<int> G()
    {
        Console.WriteLine(10);
        return Task.FromResult(20);
    }
```
to
```
async static Task<int> G()
    {
        Console.WriteLine(10);
        return await Task.FromResult(20);
    }
```
4. Try to continue debugging. Note there is no issues in the Error list at this point

**Expected Behavior**:
Debugger should let you continue debugging and the text should print out.
**Actual Behavior**:
Pop up appears saying there are compiler errors. 2 errors are now present in the error list:
![image](https://cloud.githubusercontent.com/assets/10537189/15729093/f5dc9f0e-2815-11e6-8d15-788456fe111a.png)

**Comment by tmat** [comment]
This was fixed by https://github.com/dotnet/roslyn/commit/c7c829963204d0b083efea2e8977ba7756917430 a week ago. Are the bits in D14Rel yet?

**Comment by mattscheffer** [comment]
This is still failing in VSUML as well. There was an insertion from Master (which this was pushed to) on Monday, so I would expect these bits to be present.

**Comment by tmat** [comment]
We might not have updated VSUML since it's in escrow for U3 RC.
