### ISSUE TITLE
[Test Failure] VSSDK Build error in perf_correctness_prtest on PR #12084

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#12086]
PR: [#12084](https://github.com/dotnet/roslyn/pull/12084) *Allow languages to specify if they want to support completion on backspace or not.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/perf_correctness_prtest/42/

**Issue 1: VSSDK Build error**
error VSSDK1031: Extension '49e24138-9ee3-49e0-8ede-6b39f49303bf' could not be found. Please make sure the extension has been installed. [D:\j\workspace\perf_correctn---991e8cc1\src\VisualStudio\VisualStudioDiagnosticsToolWindow\VisualStudioDiagnosticsWindow.csproj]

**Comment by Pilchie** [comment]
Tag @dotnet/roslyn-infrastructure This seems fishy.  This error should only come if the build is deploying packages, we we don't normally do.  Is that something specific to the `perf_correctness_prtest` job?

@TyOverby?

**Comment by TyOverby** [comment]
@dotnet/roslyn-perf

**Comment by TyOverby** [comment]
I certainly don't expect that we'd be deploying packages in perf_correctness.  

As you can see [here](https://github.com/dotnet/roslyn/blob/master/cibuild.cmd#L82-L85), we only do the following: 

1. Build Open/Roslyn.sln with the default arguments
2. Run the perf test runner.

I know that the perf test runner isn't doing anything weird, and building Roslyn.sln doesn't seem like it would deploy extensions.

**Comment by Pilchie** [comment]
I think this got fixed by @jaredpar yesterday?

**Comment by jaredpar** [comment]
The VS SDK bug still exists, and has existed for at least 1.5 years.  It is not fixed.  I'm unsure of what the internal bug is though.  

The behavior of the suite is fixed because we no longer deploy at build time.
