### ISSUE TITLE
IDE shouldn't switch to output window when listing intellisense issues

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#12202]
many times when user opens a solution, they get list of file read failures such as below.

we should find out who is responsible for these files and make sure either project system (or whoever responsible for those files) doesn't add those files to us until they actually exist or create them before hand if possible.

![image](https://cloud.githubusercontent.com/assets/1333179/16348474/9b17b762-3a07-11e6-8daa-6eff20d7f07f.png)

Another duplicate at https://developercommunity.visualstudio.com/content/problem/24671/intellisense-error-after-renaming-windows-form.html

**Comment by heejaechang** [comment]
I added IDE but might belong to project system?

**Comment by jasonmalinowski** [comment]
These files are added to the compilation as part of the Windows Workflow Foundation targets, which unfortunately are defined in the shipped desktop framework, so it's a huge pain to address those. @pilchie and I were on a separate conversation about these errors in general, and think it's probably just wise to not show these so visibly in the output window. Yes, there's a "problem" but no customer probably cares or can do anything about it, so we mind as well not show anything.

**Comment by davkean** [comment]
The temporary files are being tracked by this: https://github.com/Microsoft/msbuild/issues/1646.

**Comment by davkean** [comment]
However, we output an error every time someone deletes a file from a project.

**Comment by wyckster** [comment]
Seems to occur if you just rename a windows forms file.

**Comment by Pilchie** [comment]
Another report in https://developercommunity.visualstudio.com/content/problem/26258/annoying-intellisense-output.html

**Comment by jasonmalinowski** [comment]
Pulling this back into 15.7 as we've had several more feedback related to this in the last few days.

**Comment by CyrusNajmabadi** [comment]
I always only see this for .g.cs files not being available (presuable some part of the build deletes/recreates them).  They're effectively useless notifications entirely.

**Comment by sgwatgit** [comment]
I've encountered this issue under these conditions

A solution containing
.net 4.6.1 ASP.NET WebForms app (old project system)
.net 4.6.1 class library (using the VS2017 project system)

The WebForms app references the class library.

The `IntelliSense` output shows

`[Failure] Could not find file 'C:\dev\projects\mylibrary\obj\Debug\net461\MyLibrary.AssemblyInfo.cs'.` after a clean of the solution.

Because the class library is using the new project system, there is no `MyLibrary.AssemblyInfo.cs` on the filesystem. One is created at build time by the project system, correct?

**Comment by davkean** [comment]
Another two cases: https://github.com/dotnet/project-system/issues/3472 and https://www.yammer.com/microsoft.com/#/Threads/show?threadId=977583688.

**Comment by davkean** [comment]
The minimum change here even if the errors don't go away is to prevent Output window/category from getting focus.

**Comment by heejaechang** [comment]
@kuhlenh  @dotnet/roslyn-ide @jinujoseph is it us who set focus on output window? if it is us, should we not do that?

**Comment by davkean** [comment]
I've submitted a proposed PR to fix the activation issue here: https://github.com/dotnet/roslyn/pull/26230/files.

Note, I've spent 3 hours trying to get it built and tested and failed miserably. I've given up trying to merge this but if anyone on this thread wants to take my changes, test & merge feel free.

**Comment by davkean** [comment]
I've fixed this so that it does not steal focus.

**Comment by b-mi** [comment]
This bug is still not repaired - after two years - VS 2017 15.7.6. Is it problem to repair it and distribute in VS update?

**Comment by jasonmalinowski** [comment]
Closing this bug, as more generally we've removed our output pane entirely. Files that can't be read are now displayed as just a diagnostic in the error list that go away when the files exist again.
