### ISSUE TITLE
Can not reference Portable Forms Library with NetStandard

### ISSUE THREAD

**Issue by pcibraro** [dotnet/roslyn#13836]
**Version Used**: 
Microsoft Visual Studio Community 2015
Version 14.0.25425.01 Update 3

Xamarin   4.2.0.680 (c4382f5)
Xamarin.Android   7.0.0.18 (0e59c36)
Xamarin.iOS   10.0.0.6 (6c3fee4)

**Steps to Reproduce**:

1. Create a new Blank App (Xamarin.Forms Portable)
2. Convert the Portable Library to NetStandard as it described here https://xamarinhelp.com/dot-net-standard-pcl-xamarin-forms/ 
3. Modify one of the generated projects to use project.json (For example WinPhone)
4. Try to add the Portable Library  to the project modified in step 3. 

**Expected Behavior**:
The Portable Library is added to the project and referenced correctly

**Actual Behavior**:
Incompatible Library Error.

![screen shot 2016-09-15 at 6 00 34 pm](https://cloud.githubusercontent.com/assets/722557/18567634/76b11f90-7b6f-11e6-83a6-c77160069078.png)

**Comment by jasonmalinowski** [comment]
@rchande is this a bug we already fixed?

**Comment by Pilchie** [comment]
I believe this was fixed as part of the update to https://msdn.microsoft.com/en-us/library/mt752379.aspx that was published on Tuesday.  @pcibraro can you make sure you have that installed and give it another try?

**Comment by pcibraro** [comment]
Thanks @Pilchie. I installed the update but it did not fix the issue unfortunately.  Once you convert your library to NETStandard, you can not reference it anymore from the rest of the projects. The same error is reported in Visual Studio.

**Comment by rchande** [comment]
@pcibraro Sorry to hear that. What verison of netstandard is your PCL targeting?

**Comment by se** [comment]
@pcibraro This article is not right.

**Comment by rchande** [comment]
@pcibraro I'm able to build/deploy/run the Windows Phone project from the repo you linked. I'm using VS 2015 Update 3 25431.01. I'm going to close this bug--feel free to open another if you continue to encounter the issue in VS "15".
