### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests.TestReportingUnsupportedDiagnostic fails in presence of localized resources

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#1392]
Assemblies Run

F:\Roslyn\Main\Open\Binaries\Debug\Roslyn.Compilers.CSharp.Semantic.UnitTests.dll

Summary

Tests run: 3330   Failures: 1, Skipped: 12, Run time: 130.619s

Failed tests

0.037s
✘
 Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests.TestReportingUnsupportedDiagnostic : Expected: Diagnostic("AD0001").WithArguments("Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests+AnalyzerReportingUnsupportedDiagnostic", "Reported diagnostic with ID 'ID_2' is not supported by the analyzer. Parameter name: diagnostic") Actual: Diagnostic("AD0001").WithArguments("Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests+AnalyzerReportingUnsupportedDiagnostic", "!cSUx2!Reported diagnostic with ID 'ID_2' is not supported by the analyzer. ЁЧЫюрфя ! Имя параметра: diagnostic").WithLocation(1, 1) Diff: ++> Diagnostic("AD0001").WithArguments("Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests+AnalyzerReportingUnsupportedDiagnostic", "!cSUx2!Reported diagnostic with ID 'ID_2' is not supported by the analyzer. ЁЧЫюрфя ! ++> Имя параметра: diagnostic").WithLocation(1, 1) --> Diagnostic("AD0001").WithArguments("Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests+AnalyzerReportingUnsupportedDiagnostic", "Reported diagnostic with ID 'ID_2' is not supported by the analyzer. --> Parameter name: diagnostic")
   в Xunit.Assert.True(Boolean condition, String userMessage)
   в Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Test\Utilities\DiagnosticExtensions.cs:строка 83
   в Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Test\Utilities\DiagnosticExtensions.cs:строка 45
   в Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Test\Utilities\DiagnosticExtensions.cs:строка 60
   в Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyAnalyzerDiagnostics[TCompilation](TCompilation c, DiagnosticAnalyzer[] analyzers, AnalyzerOptions options, Action`3 onAnalyzerException, Boolean logAnalyzerExceptionAsDiagnostics, DiagnosticDescription[] expected) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Test\Utilities\DiagnosticExtensions.cs:строка 123
   в Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests.TestReportingUnsupportedDiagnostic() в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Compilers\CSharp\Test\Semantic\Diagnostics\DiagnosticAnalyzerTests.cs:строка 950

See https://github.com/dotnet/roslyn/issues/821 for repro steps.

**Comment by mavasani** [comment]
This should be fixed with #1714

**Comment by mavasani** [comment]
Moved to @AlekseyTs for verification.

**Comment by AlekseyTs** [comment]
@mavasani I still see the failure.


✘
 Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests.TestReportingUnsupportedDiagnostic : Expected: Diagnostic("AD0001").WithArguments("Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests+AnalyzerReportingUnsupportedDiagnostic", "System.ArgumentException", "Reported diagnostic with ID 'ID_2' is not supported by the analyzer. Имя параметра: diagnostic") Actual: Diagnostic("AD0001").WithArguments("Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests+AnalyzerReportingUnsupportedDiagnostic", "System.ArgumentException", "!cSUx2!Reported diagnostic with ID 'ID_2' is not supported by the analyzer. ЁЧЫюрфя ! Имя параметра: diagnostic").WithLocation(1, 1) Diff: ++> Diagnostic("AD0001").WithArguments("Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests+AnalyzerReportingUnsupportedDiagnostic", "System.ArgumentException", "!cSUx2!Reported diagnostic with ID 'ID_2' is not supported by the analyzer. ЁЧЫюрфя ! ++> Имя параметра: diagnostic").WithLocation(1, 1) --> Diagnostic("AD0001").WithArguments("Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests+AnalyzerReportingUnsupportedDiagnostic", "System.ArgumentException", "Reported diagnostic with ID 'ID_2' is not supported by the analyzer. --> Имя параметра: diagnostic")
   в Xunit.Assert.True(Boolean condition, String userMessage)
   в Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Test\Utilities\DiagnosticExtensions.cs:строка 83
   в Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Test\Utilities\DiagnosticExtensions.cs:строка 45
   в Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Test\Utilities\DiagnosticExtensions.cs:строка 60
   в Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyAnalyzerDiagnostics[TCompilation](TCompilation c, DiagnosticAnalyzer[] analyzers, AnalyzerOptions options, Action`3 onAnalyzerException, Boolean logAnalyzerExceptionAsDiagnostics, DiagnosticDescription[] expected) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Test\Utilities\DiagnosticExtensions.cs:строка 123
   в Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests.TestReportingUnsupportedDiagnostic() в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Compilers\CSharp\Test\Semantic\Diagnostics\DiagnosticAnalyzerTests.cs:строка 955

**Comment by mavasani** [comment]
@AlekseyTs can you please re-try? It should be fixed with #1882

**Comment by AlekseyTs** [comment]
Verified
