### ISSUE TITLE
Converting a VB PCL to .NET Standard causes error

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn#14556]
**Version Used**: Visual Studio 2015 Update 3

**Steps to Reproduce**:
- **File** | **New Project**
- Select V**isual Basic** node
- Select **Class Library (Portable)**
- Select these targets:
  - .NET Framework 4.5
  - Windows 8
  - Windows Phone Silverlight 8
  - ASP.NET Core 1.0
  - Xamarin.Android
  - Xamarin.iOS
  - Xamarin.iOS (Classic)
- Double click **My Project**
- Select app designer tab **Library**
- Click **Target .NET Platform Standard**
- Click **Yes** in the confirmation dialog

**Expected Behavior**:

No error message

**Actual Behavior**:

![pic1](https://cloud.githubusercontent.com/assets/5169960/19449581/f3777eda-945a-11e6-9e6e-53236f7cc865.jpg)

**Comment by Pilchie** [comment]
@terrajobst what exact version do you have?  This changed with KB's for Update 3.

**Comment by terrajobst** [comment]
That's what Help | About shows me:

![image](https://cloud.githubusercontent.com/assets/5169960/19457384/ea7fd136-947a-11e6-955d-bf3067fc3788.png)

**Comment by Pilchie** [comment]
Should this be resolved now?

**Comment by Pilchie** [comment]
Ping?  Is this resolved for RC (or for RC.2)?

**Comment by MattGertz** [comment]
@Pilchie It is not resolved, still repros in  d15rel 15.0.25901.0.

**Comment by MattGertz** [comment]
But moving this to RC.2.

**Comment by rchande** [comment]
Sorry, yes, this is resolved for RC2.

**Comment by rchande** [comment]
(https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/41843?_a=overview)

**Comment by MattGertz** [comment]
@rchande Ah, that would explain it.  Thanks.

**Comment by rchande** [comment]
@terrajobst You can verify this in builds of lab/mlL or wait for RC2. Thanks!
