### ISSUE TITLE
Missing error when a ValueTuple contains a pointer type

### ISSUE THREAD

**Issue by yume-chan** [dotnet/roslyn#15399]
**Version Used**: 

RC insider VSIX from [this documentation](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md)

Visual Studio 2015 Update 3

**Steps to Reproduce**:

1. Allow unsafe.
2. Paste this code snippet:
```` C#
unsafe void ValueTupleWithPointer()
{
    (byte*, int) t = (null, 1);
}
````
3.  Build

**Expected Behavior**:

CS0306 The type 'byte*' may not be used as a type argument

**Actual Behavior**:

No compile-time error, but runtime error:

````
System.TypeLoadException: The generic type 'System.ValueTuple`2' was used with an invalid instantiation in assembly 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
````

**Comment by gafter** [comment]
I wonder if this fixes https://github.com/dotnet/roslyn/issues/15934

**Comment by jcouv** [comment]
Fixed by #15641
@CnSimonChan Thanks for reporting the bug.

**Comment by onionhammer** [comment]
This is still occurring for me in 2.1.2 sdk / 2.0.3 compiler in mstests

```
Failed   TestParserContinuators
Error Message:
 Test method csparser.ParserTests.TestParserContinuators threw exception:
System.TypeLoadException: The generic type 'System.ValueTuple`2' was used with an invalid instantiation in assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
```

**Comment by jcouv** [comment]
@onionhammer Let's re-open then. Could you provide more details so that I can try and repro? Thanks

**Comment by onionhammer** [comment]
Reproduce:

```powershell
mkdir repro
cd repro
dotnet new console
dotnet add package System.Memory -v 4.4.0-preview1-25305-02

@"
using System;

class Program
{
    static void Main(string[] args)
    {
        (string, ReadOnlySpan<char>) identifier(string input) =>
            ("Test", input.AsSpan());

        var (output, _) = identifier("This is a test");
    }
}
"@ > "Program.cs"

dotnet run
```

**Comment by jcouv** [comment]
Tagging @VSadov 
We verified that the compiler [produces errors](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAGAAhwEYBuAWACgcBmIgJgIGECBvKgzounAFgICyACgCUbDl0lCAykgLSxMAK4AHDHAIBeAgBM4AMwhKMMCpUkBfKlcoIDBWAiUBjGPLYELQA===) for a tuple containing a ref-struct. But it is possible that the preview version of ReadOnlySpan was not yet marked properly as a ref-struct.

**Comment by jcouv** [comment]
I downloaded that `System.Memory` package and looked at the ref and implementation assemblies called `System.Memory.dll` and the `ReadOnlySpan<T>` types are missing the `Obsolete` attribute that is supposed to mark ref-structs.

@ahsonkhan It looks like the preview package for System.Memory on nuget is fairly old and lacks some important attributes for the compiler. Is there are more recent preview available?

**Comment by ahsonkhan** [comment]
> Is there are more recent preview available?

Yes, the recent previews are on myget (for example 4.5.0-preview1-26122-01 from today):
https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Memory

**Comment by jcouv** [comment]
The preview package is expected to refresh in a couple of weeks.
I'll go ahead and close the issue, since no compiler problem. Thanks
