### ISSUE TITLE
You can't "fix all" or "suppress" messages that come from within a ".designer" file

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15762]
Similar to #15761, but in this case the window never appears to be doing anything and VS or associated processes aren't consuming any CPU.

1. Clone this repo to this commit: https://github.com/dotnet/roslyn-project-system/commit/e8f444a1ebe3d78b6b494d5dc355e95b7da19086
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (build 26005.0 D15PreRel)
4. Open src\Microsoft.VisualStudio.ProjectSystem.CSharp.VS\ProjectSystem\VS\Xproj\MigrateXprojProjectFactory.cs, line number 203
5. Open Lightbulb, choose Inline variable declaration -> Fix all occurrences in Solution

-- Wait for a large amount of time --

Nothing happens

**Comment by davkean** [comment]
tag @jmarolf Is this similar?

**Comment by jmarolf** [comment]
hmm.  I'll try it out under the debugger.  May be the same may be something else.

**Comment by Pilchie** [comment]
@CyrusNajmabadi @heejaechang there was another issue in the RC timeframe around Fix All not working for some fixes.  Is this the same thing?

**Comment by Pilchie** [comment]
The other bug was #14978...

**Comment by heejaechang** [comment]
@mavasani do you have any idea on this?

**Comment by mavasani** [comment]
I think this is same as https://github.com/dotnet/roslyn/issues/15411. We should check if this repros after that issue has been fixed.

**Comment by davkean** [comment]
No, this is a different issue -  it looks like Fix All is broken for *Solutions*.  Document and Projects work, or eventually show the Preview dialog. No matter how long I wait for Solution it doesn't work.

**Comment by davkean** [comment]
@mavasani  @heejaechang Who should this be assigned to?

**Comment by davkean** [comment]
Okay, this is inconsistent - the first time I kick it off, it works every time after that it doesn't.

**Comment by mavasani** [comment]
@jmarolf is already investigating #15411. Jon does this look related?

**Comment by heejaechang** [comment]
@jmarolf does it work if OOP is turned off?

**Comment by davkean** [comment]
Just to point out - that on occasions, the dialog does show - but choosing **Apply** does nothing. This happened to me both for Fix All in Solution and Fix All in Document.

**Comment by davkean** [comment]
I've got @jmarolf's change locally and it fixes the case where the Preview dialog eventually shows. But I'm still running into situations where it just never shows/runs or anything.

This is what happen when I got into this state:

1. Choose Fix -> all occurrences in Solution

-- Notice nothing happens -- 

2. Choose Fix -> just this occurence
3. Undo
4. Choose Fix -> All occurrences in Solution
5. This dialog appears (it did not appear above the first time):

![image](https://cloud.githubusercontent.com/assets/1103906/21445945/6631845a-c914-11e6-9ff9-3d10533a1de2.png)

-- Notice no preview dialog shows --

**Comment by davkean** [comment]
I think I just figured out the cause, the cases that this happens in (> 2000 cases in my case) are all ".Designer.vb" files. In those cases, the Preview never shows. It looks like you filter ".Designer.cs" from the Fix Alls?

In those cases, why are you firing these violations in the first place for designer files? Is that the bug?

**Comment by jmarolf** [comment]
@davkean sounds like the bug is incorrect filtering at the analyzer level

**Comment by davkean** [comment]
I've found another case where it doesn't work that isn't Designer related. I'll leave this one as the Designer bug.

**Comment by davkean** [comment]
Here is the other one: https://github.com/dotnet/roslyn/issues/15761.

**Comment by davkean** [comment]
Oh worse, you can't suppress "said warnings" either Right-click -> Supression -> In Suppression File _does nothing_ @mavasani @heejaechang

**Comment by Pilchie** [comment]
The latest discussion looks like this is analyzer and suggestion related.

**Comment by heejaechang** [comment]
I have some other urgent one to address for now, but will take a look after that.

**Comment by heejaechang** [comment]
@davkean can you tell me what diagnostic is the one that shows up in designer file? also, @mavasani do we allow changing generated file in codefix?

**Comment by davkean** [comment]
Any of the simplify ones fire.

**Comment by heejaechang** [comment]
this doesnt seems repro.

**Comment by davkean** [comment]
I'm still hitting this in RTM:

I'm in a Resources.Designer file (in https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs#L12) and we have Errors turned on for unused namespaces and I'm getting the following:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	IDE0005	Using directive is unnecessary.	Microsoft.VisualStudio.ProjectSystem.Managed.VS	E:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\VSResources.Designer.cs	12	Active

```

**Comment by davkean** [comment]
However, I can suppress it inline (which is pointless given that's a generated file). I cannot use the Lightbulb however.

**Comment by heejaechang** [comment]
@davkean I think LB never shows up in generated file @mavasani ?

**Comment by heejaechang** [comment]
for ide diagnostic being show up, looks like ide analyzer is not configured to not reporting diagnostics on generated file. @dotnet/roslyn-ide

**Comment by Pilchie** [comment]
@CyrusNajmabadi Can you take a look?  I thought this was addressed in https://github.com/dotnet/roslyn/pull/16703?

**Comment by Pilchie** [comment]
@jinujoseph can you re-triage? This was in the 2.0 milestone.

**Comment by davkean** [comment]
This is still occurring, still get warnings in designer files that can never be fixed:

![image](https://user-images.githubusercontent.com/1103906/36363510-d48582ba-1591-11e8-81b7-555d50431420.png)

**Comment by sharwell** [comment]
@davkean IDE0005 is produced by the compiler and cannot be suppressed in generated code. This diagnostic is unusable at error severity, which is why it remained blocked in dotnet/roslyn#23695.

**Comment by sharwell** [comment]
More specifically, CS8019 is produced by the compiler, and IDE0005 is just produced wherever it's reported by the compiler so the fade out feature works.

**Comment by davkean** [comment]
@sharwell I'm not sure what that means.

**Comment by sharwell** [comment]
@davkean Your image shows IDE0005 with severity Error. The only supported severity for IDE0005 is Hidden. You should restore the severity of the warning to its default value, and the issue you described will go away.

If you want the ability to change the severity of IDE0005, you should file a new issue for that.

**Comment by davkean** [comment]
Really confused. A few releases ago I changed this to an error.

>  You should restore the severity of the warning to its default value, and the issue you described will go away.

This sounds like all IDE0005 errors will go away which is not want I want. I just don't want this warning to show in generated files.

**Comment by mavasani** [comment]
This is a bug in the `AbstractRemoveUnnecessaryImportsDiagnosticAnalyzer`. It's [Initialize](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/RemoveUnnecessaryImports/AbstractRemoveUnnecessaryImportsDiagnosticAnalyzer.cs,73) method does not configure how to deal with generated code. It should be invoking `context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);` to ensure this analyzer is never invoked on generated files.

**Comment by mavasani** [comment]
Filed https://github.com/dotnet/roslyn-analyzers/issues/1592, which would have caught this issue.

**Comment by sharwell** [comment]
@mavasani We likely still want fading of unnecessary imports to work in generated code, so this will need to be modified further to separate the unnecessary code diagnostic from the diagnostic that triggers a code fix.

**Comment by mavasani** [comment]
It seems https://github.com/dotnet/roslyn/pull/16703/files handled this case for bunch of analyzers, but missed this one (and potentially some others?). We should really implement dotnet/roslyn-analyzers#1592 to ensure this is correctly implemented and never regressed.

**Comment by mavasani** [comment]
> We likely still want fading of unnecessary imports to work in generated code

Ah, I presume that is the reason @CyrusNajmabadi didn't do so in https://github.com/dotnet/roslyn/pull/16703.

I agree with @sharwell - we need to split this into two diagnostics, a hidden non-configurable diagnostic for fading/code fix and another user facing configurable diagnostic. The analyzer should explicitly configure generated code analysis so it can run and report diagnostics on generated files. The user facing diagnostic should only be reported for non-generated code by the analyzer (probably needs https://github.com/dotnet/roslyn/issues/7578 to allow the analyzer to correctly do this).

**Comment by heejaechang** [comment]
I am not against fading things out or showing squiggles in generated files but curious on why people wants it? is it for people who authors generators?

for 99.9% people who uses VS, generated files are something they probably won't see at all. so consuming any resource for it (except one absolutely required such as building/semantic information) seems all waste. especially since generated files tends to large.

due to that reason, I dont believe we even format those files to make it look nicer and etc.

anyway, if we want to do something on those generates files for this less than 1% of people, having reg key option might be better solution?

**Comment by heejaechang** [comment]
I think I remember we talked about security related diagnostics we want to show in generated files. I still not 100% sure why?  but I guess people want to use that diagnostics to decide what generator to consume? or again, it is targeting those people who author generators? we probably need to gather some telemetry data but all that sounds like less than 1% people who we can solve by providing simple reg key that let VS to ignore Generated files option

**Comment by davkean** [comment]
The only way to find all naming violations is by going to Explorer, doing a "*.cs", dragging it into VS to open every file. This causes designer files to be opened, which results in errors that you cannot fix or suppress. Frustrating experience.

**Comment by sharwell** [comment]
@davkean That is a known limitation of the naming style analyzer:

https://github.com/dotnet/roslyn/blob/ef11fa5e23c823ecf76e401e0b35747d43b57169/src/Features/Core/Portable/Diagnostics/Analyzers/NamingStyleDiagnosticAnalyzerBase.cs#L39

This property will be removed when the analyzers are transitioned to a NuGet package, so the limitation will be lifted at the same time.

**Comment by davkean** [comment]
Yes, but that doesn't change the fact that there's a disconnect betweeen the thing that shows the errors and thing that lets you fix them and/or suppress them. The latter has what appears to be `if (generated) DoNothing();`

**Comment by sharwell** [comment]
If naming warnings are reported in generated code, it is a bug. Generated code is explicitly excluded from analysis by that analyzer here:

https://github.com/dotnet/roslyn/blob/ef11fa5e23c823ecf76e401e0b35747d43b57169/src/Features/Core/Portable/CodeStyle/AbstractCodeStyleDiagnosticAnalyzer.cs#L120

> Either both should have that check, or the check should be removed.

The check in the code fix layer is wrong and needs to be removed. https://github.com/dotnet/roslyn/issues/2753#issuecomment-128509410

**Comment by davkean** [comment]
I'm not referring to naming violations being found, but other analyzers. Naming violations comment is because the only way to find them all is open every file, which results in different errors showing up.
