### ISSUE TITLE
Should not offer to inline variables within constructor initializers, field initializers, or property initializers

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#17371]
In the following code `value` will be suggested as inline-able

```C#
        private static Func<string, Type, object> _cachedParseValue = (s, type) =>
        {
            if (type == typeof(int))
            {
                var value = 0;
                return int.TryParse(s, out value) ? (object)value : null;
            }
        };
```

However in-lining will produce the following error:

Severity | Code | Description 
------------ | -------------  | ------------- 
Error | CS8200 | Out variable and pattern variable declarations are not allowed within constructor initializers, field initializers, or property initializers.

**Comment by Pilchie** [comment]
I'm surprised this restriction applies in lambdas in initializers, but if it does, we should not off here.

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-compiler @gafter Is the above error expected?  I would have thought an out-var in a lambda in a field would be acceptable.

**Comment by AlekseyTs** [comment]
The error is a known bug, fixed in https://github.com/dotnet/roslyn/pull/17101.

**Comment by CyrusNajmabadi** [comment]
Given that this was just an error in the compiler, I'm just going to close this as desirable behavior.

**Comment by MichaelPuckett2** [comment]
Still exists..
  public static readonly DependencyProperty FillProperty =
            DependencyProperty.Register(nameof(Fill), typeof(Brush), typeof(PaletteMatchCanvas), new PropertyMetadata(new SolidColorBrush(Colors.White), (s, e) =>
            {
                var canvas = s as PaletteMatchCanvas;

                canvas.Children.AsParallel().ForAll(uiElement =>
                {
                    if (uiElement is Shape shape) // throws that error.   Or is it supposed to here?
                        shape.Fill = (Brush)e.NewValue;
                });
            }));

**Comment by CyrusNajmabadi** [comment]
@MichaelPuckett2 Are you using a version of Roslyn that has the fix Aleksey referred to?

**Comment by MichaelPuckett2** [comment]
I guess I need to check; I just assumed this was in the latest version included in VS 2017 and C# 7.  How do I upgrade to that version?

**Comment by CyrusNajmabadi** [comment]
Aleksey's referenced PR was merged into dev15.1.x.  @jasonmalinowski What's the timeline on that being available as an update for VS2017?

**Comment by AlekseyTs** [comment]
I think the change is no longer in that branch, the branch was reset at some point.

**Comment by jasonmalinowski** [comment]
Indeed, that was merged in the small window between when we opened the branch and then the policy was changed. The change _is_ in master which will ship around 15.3 or so. Unfortunately I can't give a public release date for that but "not in the next month" is a correct statement.
