### ISSUE TITLE
Get offered to resolve a type already in scope for an incomplete method

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#18620]
``` C#
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ConsoleApp282
{
    class Program
    {
        public async Task<IReadOnlyCollection<ProjectConfiguration>>
    }
}
```

1. Place cursor over IReadOnlyCollection and press CTRL+.

Expected: Not to be offered to resolve IReadOnlyCollection as it is already in scope
Actual:

![image](https://cloud.githubusercontent.com/assets/1103906/24939636/25e4b5ec-1f82-11e7-8e1e-d957ca81f7db.png)

**Comment by davkean** [comment]
I'm guessing that this is due to the way the compiler parses this due to the generics, I'm seeing the following in the error list:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1003	Syntax error, ',' expected	ConsoleApp282	c:\users\davkean\documents\visual studio 2017\Projects\ConsoleApp282\ConsoleApp282\Program.cs	8	Active
Error	CS1003	Syntax error, '>' expected	ConsoleApp282	c:\users\davkean\documents\visual studio 2017\Projects\ConsoleApp282\ConsoleApp282\Program.cs	8	Active
Error	CS1003	Syntax error, ',' expected	ConsoleApp282	c:\users\davkean\documents\visual studio 2017\Projects\ConsoleApp282\ConsoleApp282\Program.cs	8	Active
Error	CS1002	; expected	ConsoleApp282	c:\users\davkean\documents\visual studio 2017\Projects\ConsoleApp282\ConsoleApp282\Program.cs	8	Active
Error	CS0305	Using the generic type 'IReadOnlyCollection<T>' requires 1 type arguments	ConsoleApp282	c:\users\davkean\documents\visual studio 2017\Projects\ConsoleApp282\ConsoleApp282\Program.cs	8	Active
Error	CS0106	The modifier 'async' is not valid for this item	ConsoleApp282	c:\users\davkean\documents\visual studio 2017\Projects\ConsoleApp282\ConsoleApp282\Program.cs	8	Active
```

**Comment by Pilchie** [comment]
Yes - it's related to parsing for async.  Moving to the compiler.  @CyrusNajmabadi has some ideas about how we could parse better here.

**Comment by gafter** [comment]
The compiler thinks you're declaring something with type `async`. We should have better error recovery for this situation so the IDE is less confused.

**Comment by CyrusNajmabadi** [comment]
I thought i already fixed this :)

**Comment by gafter** [comment]
@CyrusNajmabadi You probably did. I'm going through old bugs. @davkean Can you still reproduce this?

**Comment by CyrusNajmabadi** [comment]
Yup.  I don't repro this locally.  Everything works as expected.  I must have missed closing this out when doing the original fix.
