### ISSUE TITLE
Creating C# WPF apps crash VS with ArgumentNullException

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#19351]
**Version Used**: 
VSUML 26507.1
**Steps to Reproduce**:
1. Install VS with .NET Desktop Development
2. Create a new C# WPF App

**Expected Behavior**:
Project creates successfully and you are able to work on it.
**Actual Behavior**:
Project creates followed by crashing VS.

Exception:
```
CLR: Managed code called FailFast, saying "System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.TryGetValue(TKey key, TValue& value)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)
   at Microsoft.CodeAnalysis.Serialization.ChecksumCache.GetOrCreate(Object value, CreateValueCallback checksumCreator)
   at Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeIndex.<GetChecksumAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeIndex.<PrecalculateAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<>c__DisplayClass31_1`1.<<RunAnalyzersAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<GetOrDefaultAsync>d__33`2.MoveNext()"
```

**Comment by Pilchie** [comment]
Fixed yesterday in https://github.com/dotnet/roslyn/pull/19357.

**Comment by mattscheffer** [comment]
@Pilchie Wasn't this pushed to VSUML? I just upgraded to the latest build which contains 20170509.8 and i'm still seeing the crash.

**Comment by Pilchie** [comment]
Should have been I think.  @tmeschter ?

**Comment by Pilchie** [comment]
And @jasonmalinowski who I think did this insertion.

**Comment by jasonmalinowski** [comment]
@mattscheffer Can you provide a dump? Dumps always make the mysterious clear.

**Comment by mattscheffer** [comment]
Provided dump via email. Can send again if needed. Reopening bug as this is still crashing VS in vsuml

**Comment by CyrusNajmabadi** [comment]
Need link to the dump to investigate.

**Comment by CyrusNajmabadi** [comment]
Your dump doesn't seem to match the stack trace above.  The dump crashes here:

```c#
StreamJsonRpc.RemoteInvocationException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.DesignerAttributes.AbstractDesignerAttributeService.<TryAnalyzeProjectInCurrentProcessAsync>d__5.MoveNext()
```

Which is an issue that @heejaechang is fixing here: https://github.com/dotnet/roslyn/pull/19466

**Comment by CyrusNajmabadi** [comment]
Resolving as dupe of https://devdiv.visualstudio.com/DevDiv/_workitems?id=433730&_a=edit
