### ISSUE TITLE
The .editorconfig setting dotnet_style_qualification_for_method = true does not appear to work.

### ISSUE THREAD

**Issue by emdelaney** [dotnet/roslyn#19373]
**Version Used**: Roslyn Language Services 2.1.0.6152004 / Latest Visual Studio 2017

**Steps to Reproduce**:

1. In the latest version of Visual Studio 2017, open a solution with an .editorconfig file (I based my file on the Roslyn .editorconfig file, as seen here: https://github.com/dotnet/roslyn/blob/master/.editorconfig ).
2. Set the following property in the .editorconfig file: `dotnet_style_qualification_for_method = true:error`
3. Open a .cs file in the project that has at least one method call.
4. Ensure there is at least one method call in the file that is not prefixed with `this.`

**Expected Behavior**:
A compiler error is shown in the errors window in Visual Studio indicating that the method call must be prefixed with `this.`.

**Actual Behavior**:
No compiler errors appear.

** Notes **
When I do the opposite test (setting `dotnet_style_qualification_for_method = false:error` and ensure that a method call is prefixed with `this.`), I get a compiler error as I would expect. `dotnet_style_qualification_for_field` and `dotnet_style_qualification_for_property` seem to work fine for `true:error`, showing an error as I would expect.

**Comment by Pilchie** [comment]
@sharwell - did you just file a VB specific version of this?  Do you want this one too?

**Comment by sharwell** [comment]
I did: #19750

**Comment by Pilchie** [comment]
Note - from #19750 - this affects Tools\Options, and VB as well.  Basically - this option is just not obeyed for methods.

**Comment by poke** [comment]
I believe this was fixed in a recent Visual Studio 15.8 update. At least I am now getting warnings for missing `this.` in front of methods where I didn’t get warnings before.

**Comment by tillig** [comment]
In VS Code 1.41.0 with the C# 1.21.9 extension if you set the style to `true`...

```
dotnet_style_qualification_for_event = true:suggestion
dotnet_style_qualification_for_field = true:suggestion
dotnet_style_qualification_for_method = true:suggestion
dotnet_style_qualification_for_property = true:suggestion
```

Then you'll still get the IDE0003 note that you should (incorrectly) _remove_ the `this` qualifier.

<img width="740" alt="IDE0003 display" src="https://user-images.githubusercontent.com/1156571/71194523-f3196300-2240-11ea-9202-b9fec4be176f.png">

**Comment by jonathanou** [comment]
> 
> 
> In VS Code 1.41.0 with the C# 1.21.9 extension if you set the style to `true`...
> 
> ```
> dotnet_style_qualification_for_event = true:suggestion
> dotnet_style_qualification_for_field = true:suggestion
> dotnet_style_qualification_for_method = true:suggestion
> dotnet_style_qualification_for_property = true:suggestion
> ```
> 
> Then you'll still get the IDE0003 note that you should (incorrectly) _remove_ the `this` qualifier.
> 
> <img alt="IDE0003 display" width="740" src="https://user-images.githubusercontent.com/1156571/71194523-f3196300-2240-11ea-9202-b9fec4be176f.png">

I'm getting the exact same thing in VS 2019 16.4.2

**Comment by CyrusNajmabadi** [comment]
Doesn't repro with the latest roslyn for me:

![image](https://user-images.githubusercontent.com/4564579/72241239-224e9600-359b-11ea-8512-91c270cb811d.png)

**Comment by jonathanou** [comment]
Can you tell me how I can check my Roslyn version is up to date?

Did your VS setting explicitly say not to add `this.`?  Is it possible the VS setting is in effect, and not the `.editorconfig` rule?

![image](https://user-images.githubusercontent.com/1291962/72241293-67b5a680-3621-11ea-9485-6e1e36c25079.png)

**Comment by CyrusNajmabadi** [comment]
> Can you tell me how I can check my Roslyn version is up to date?

You'd have to build and run the latest sources.  That's what i'm doing.

> Did your VS setting explicitly say not to add this.

Yes, it is:

![image](https://user-images.githubusercontent.com/4564579/72241695-5aa2a400-359c-11ea-8abd-d7eefec20ffc.png)

>  Is it possible the VS setting is in effect, and not the .editorconfig rule?

No.  If i change the editorconfig rules to:

![image](https://user-images.githubusercontent.com/4564579/72241725-6f7f3780-359c-11ea-8907-76313652dd58.png)

Then i now see the following as expected:

![image](https://user-images.githubusercontent.com/4564579/72241742-7ad26300-359c-11ea-8efb-ca3c05ebeb35.png)

**Comment by jonathanou** [comment]
>You'd have to build and run the latest sources.

OK.  I guess then perhaps the fix is already in the latest source but not yet released?  Perhaps the fix will come with an upcoming Visual Studio update?

**Comment by CyrusNajmabadi** [comment]
@jonathanou Seems likely!  If i try this on 16.5-preview1 i see the expected behavior.  Can you try that out and let us know if you see the same?

**Comment by jonathanou** [comment]
So I have discovered that in 16.4.2 if I create a brand new solution with a C# project and copy the exact same `.editorconfig` file in, the issue no longer reproduces.  Visual Studio behaves as intended.

However, with my big solution, `this.` still gets flagged as unnecessary and Visual Studio recommends that I remove it.

I'm using the same `.editorconfig` file for both cases, so I'm not sure what's different with the big solution that's causing VS to ignore the 'this.' rule.  I've also tried deleting the `.vs` folder, it didn't help.
