### ISSUE TITLE
Master Unit Test Failures

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#19556]
**Version Used**: 
`Master` at [commit](https://github.com/dotnet/roslyn/commit/2a2bbd4a6e261eed76c2153689d98759934b664c)

**Steps` to Reproduce**:
In VS Dev Cmd Prompt run the following commands
1. Restore (No Issues)
2. Build (No Issues)
3. Test (Lots of Unit Test Failures)

**Expected Behavior**:
No Test Failures

**Actual Behavior**:
See [Gist](https://gist.github.com/AdamSpeight2008/536cfda21f9a14375b8dbdcb0867614d)
[runtests.log.txt](https://github.com/dotnet/roslyn/files/1005047/runtests.log.txt)
[NullReferenceException is thrown on this line.](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb#L34)
[NullReferenceException is thrown on this line.](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs#L38)
[Assetion Failure](https://github.com/dotnet/roslyn/blob/master/src/Interactive/HostTest/InteractiveHostTests.cs#L60)
[NullReferenceException](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Syntax/LexicalAndXml/PreprocessorTests.cs#L3978)

**Comment by AdamSpeight2008** [comment]
@Pilchie I suspect this most likely is an issue with AV software on my side. Just report issue just in case it isn't.

**Comment by jcouv** [comment]
I'm investigating the NRE's in C# and VB CommandLine tests (#19245).

**Comment by jaredpar** [comment]
Fixed by this PR 

https://github.com/dotnet/roslyn/pull/19593

**Comment by jcouv** [comment]
The root cause is still not understood. We should leave the unittests to have strong assumption that CommitHash should be there. If CommitHash is missing, there is a problem with our build system or IDE build.
Re-opening.

**Comment by jaredpar** [comment]
Turns out I was just getting lucky on my box :(
