### ISSUE TITLE
Implement abstract class ignores language version

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#19684]
**Version Used**: 15.2

**Steps to Reproduce**:

1. Set the project `<LangVersion>` to 6
2. Add the following class

    ```csharp
    public class MyPropertyInfo : System.Reflection.PropertyInfo
    {
    }
    ```

3. Use the Implement Abstract Class refactoring to implement `PropertyInfo`

Old steps (didn't work to reproduce):

1. Set the project `<LangVersion>` to 6
1. Create a class with an abstract property `MyProperty`
1. Create a derived type where `MyProperty` is not yet implemented
1. Use the Implemented Abstract Class refactoring to implement `MyProperty`

**Expected Behavior**:

```csharp
class DerivedType : BaseType
{
  public override bool MyProperty
  {
    get
    {
      throw new NotImplementedException();
    }
  }
}
```

**Actual Behavior**:

```csharp
class DerivedType : BaseType
{
  public override bool MyProperty => throw new NotImplementedException();
}
```

Error **CS8059**: Feature 'throw expression' is not available in C# 6. Please use language version 7 or greater.

**Comment by CyrusNajmabadi** [comment]
I can't repro this myself.  I get:

![image](https://cloud.githubusercontent.com/assets/4564579/26315354/c7bee844-3ec5-11e7-8a2b-f883e3898c14.png)

when the language version is set to 6, and 

![image](https://cloud.githubusercontent.com/assets/4564579/26315387/db8a99a4-3ec5-11e7-931f-daa3751744d3.png)

When i set it to 7.

**Comment by Pilchie** [comment]
@sharwell can you verify that this is fixed in 15.3?

**Comment by sharwell** [comment]
I'll verify the resolution after updating locally to 15.3.

**Comment by sharwell** [comment]
@CyrusNajmabadi @Pilchie This is not fixed. I narrowed down the problem to cases where the base class is defined in a different assembly.

**Comment by CyrusNajmabadi** [comment]
New repro steps do not work for me.  When i have C# 6 i get:

![image](https://cloud.githubusercontent.com/assets/4564579/26420139/a16da330-4076-11e7-82c4-8035fc1575e2.png)

And when i have C# 7, i get:

![image](https://cloud.githubusercontent.com/assets/4564579/26420176/b50d1970-4076-11e7-907a-39c9255104b9.png)

**Comment by sharwell** [comment]
@CyrusNajmabadi Did you check properties in that? I only see methods.

**Comment by CyrusNajmabadi** [comment]
yes.  properties generate like so:
![image](https://cloud.githubusercontent.com/assets/4564579/26425973/9fe2d4da-408b-11e7-8360-a5c9aa60b27a.png)

**Comment by sharwell** [comment]
@CyrusNajmabadi Took me way too long to spot the difference.

![image](https://cloud.githubusercontent.com/assets/1408396/26437855/2db8700e-40e5-11e7-8853-eac8614feab4.png)

**Comment by CyrusNajmabadi** [comment]
Not likely to change this given lack of feedback.  Supporting lang versions from that many years ago is just not a priority given lack of feedback.
