### ISSUE TITLE
Visual Studio - Error List: `Build + IntelliSense` does not contain an error shown in `Build`

### ISSUE THREAD

**Issue by tom-dudley** [dotnet/roslyn#19693]
![visual-studio-error-list](https://cloud.githubusercontent.com/assets/21339406/26307553/18405b64-3eed-11e7-9d05-caa31eaaa28f.gif)

The above happens after a failed build. The `Output` pane correctly gives the project and analyzer ID.

**Version Used**:
I can reproduce this issue with both Visual Studio 2015 `14.0.25431.01 Update 3` and Visual Studio 2017 `15.0.0+26228.10`

**Steps to Reproduce**:
Unfortunately I can't reliably reproduce this (sometimes the errors do appear in `Build + IntelliSense`). I'm encountering it while running some SonarLint rules. The rule is available [here](https://github.com/SonarSource/sonaranalyzer-dotnet/blob/master/src/SonarAnalyzer.CSharp/Rules/DisposableMemberInNonDisposableClass.cs). The class violating the rule is part of a WinForms application.

If someone can provide some steps to take to try and nail down a repro I'd be happy to help.

**Expected Behavior**:
`Build + IntelliSense` is the union of the results on the `Build` option and the `IntelliSense` option.

**Actual Behavior**:
* In both VS2015 and VS2017 : `Build` shows an analyzer error. `Build + IntelliSense` does not.
* In both VS2015 and VS2017 : When I navigate to the line of code, it gives no red squiggles.
* In VS2015: Solution Explorer is aware of the error, shows red squiggles for the file, and lists the error in the tooltip.
In VS2017: Solution Explorer is not aware of the error.

**Comment by tom-dudley** [comment]
This is a duplicate of https://github.com/dotnet/roslyn/issues/11462 which itself is a duplicate of https://github.com/dotnet/roslyn/issues/11378

Closing.

**Comment by tom-dudley** [comment]
Re-opened since apparently the root issue, https://github.com/dotnet/roslyn/issues/11378 was fixed, but I'm still getting this in VS 2017.

**Comment by tom-dudley** [comment]
Perhaps someone could clarify, does `Build + IntelliSense` mean the _intersection_ of the two sets? So the reason I'm not seeing the error on `Build + IntelliSense` is that the IntelliSense squiggles aren't working?

If this is the case, is this still a Roslyn / Microsoft issue, or is it handled by a user setting / analyzer package? As far as I'm aware, whenever a `cs` file is open, and the corresponding project has analyzers with some rules set to error, then any violations of that rule (in open files) should get picked up by IntelliSense. This should happen out of the box, regardless of the analyzer used and without having to configure any settings.

**Comment by soerenBoisen** [comment]
I too face this critical bug in VS2017. For me, it was a lack of casting a parameter of type dynamic to the type expected by the method. It seems to be reproducible since I rebuilt a bunch of times and restarted VS. After restart the error shortly appeared on the normal "Build + Intellisense" list but then disappeared. Switching to "Build Only" shows the error. Adding the cast made the project build again.

**Comment by frozenprakash** [comment]
Wasted almost a day due to this issue !!
Founded out this issue at last from stackoverflow, kindly fix it ASAP !

**Comment by CyrusNajmabadi** [comment]
@mavasani do you know what's going o here?  I think i've also run into this occasionally?  Maybe some sort of race between listening to build events and whatever solution crawler is producing?

**Comment by mavasani** [comment]
@CyrusNajmabadi There could be multiple reasons:

1. Diagnostics which are reported during build, but not during live analysis. This happens for compilation level compiler diagnostics, such as unused or unassigned field diagnostics - we never run these in live analysis. This also happens for diagnostics reported from analyzers in CompilationEnd actions, unless user has explicitly changed the background analysis scope to full solution.
2. Bugs in de-duping logic, where we replace build diagnostics with diagnostics from live analysis whenever we analyze a specific document or project.
3. Bugs in IDE analyzer executing logic, diagnostics caching logic, etc. etc.

Unfortunately, there is no easy way to tackle this problem other then work off each repro. Also tagging @vatsalyaagrawal as we discussed issues in this space a bit today.

**Comment by janseris** [comment]
This seems fixed now in 17.3.0 and maybe was in 17.2.5

**Comment by wilfriedb** [comment]
Unfortunately this issue still exists in VS 17.5.1. Actually, sometimes the missing warnings do pop-up for a short time, only to disappear after a few seconds. I've only noticed this issue with RSnnnn code warnings.

**Comment by vzarytovskii** [comment]
We  see it in F# too (which uses Roslyn's ExternalAccess to report live, document diagnostics). Is there a workaround for it, we can implement?

**Comment by shaneharper** [comment]
[https://github.com/shaneharper/Visual_Studio_Warning_Not_Shown_In_Error_List](url) is a very small project that demonstrates that **Build + IntelliSense** isn't always the union of the results on the **Build** option and the **IntelliSense** option.

Note that the unexpected behaviour occurs only when the source file for which a compiler warning is generated was open in an editor window at the time it was compiled.

I've observed this happening on Visual Studio 2022 v17.5.4.

**Comment by CyrusNajmabadi** [comment]
> [shaneharper/Visual_Studio_Warning_Not_Shown_In_Error_List](https://github.com/shaneharper/Visual_Studio_Warning_Not_Shown_In_Error_List?rgh-link-date=2023-04-12T02%3A42%3A53.000Z) is a very small project that demonstrates that Build + IntelliSense isn't always the union of the results on the Build option and the IntelliSense option.

I don't repro this.  I properly get the warning in all circumstancces:

<img width="1624" height="341" alt="Image" src="https://github.com/user-attachments/assets/ff14821a-7943-466d-bfa0-7a443907d6f6" />

<img width="1639" height="339" alt="Image" src="https://github.com/user-attachments/assets/03f987a4-bfbb-4bcf-9158-b384ff81f502" />

If you hit this again, please let us know which specific error code this was with, and provide a current repro.  thanks.

**Comment by shaneharper** [comment]
> > [shaneharper/Visual_Studio_Warning_Not_Shown_In_Error_List](https://github.com/shaneharper/Visual_Studio_Warning_Not_Shown_In_Error_List?rgh-link-date=2023-04-12T02%3A42%3A53.000Z) is a very small project that demonstrates that Build + IntelliSense isn't always the union of the results on the Build option and the IntelliSense option.
> 
> I don't repro this. I properly get the warning in all circumstancces:
> 
> <img alt="Image" width="1624" height="341" src="https://private-user-images.githubusercontent.com/4564579/520785481-ff14821a-7943-466d-bfa0-7a443907d6f6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU5NDMzOTAsIm5iZiI6MTc2NTk0MzA5MCwicGF0aCI6Ii80NTY0NTc5LzUyMDc4NTQ4MS1mZjE0ODIxYS03OTQzLTQ2NmQtYmZhMC03YTQ0MzkwN2Q2ZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMTdUMDM0NDUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTE0YmE5Zjg1NDQ1YjQ5ZWExNmQwMDA3NDkyMGMwYTgwNjFiZWVlYzQ3NWExM2IxZWFhZjQxZWVkNDJhMjVjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.75hgi0_rSf5ZDwUV2VFqz0UVjROYNEjgNTTBF7lRIFw"> <img alt="Image" width="1639" height="339" src="https://private-user-images.githubusercontent.com/4564579/520785529-03f987a4-bfbb-4bcf-9158-b384ff81f502.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU5NDMzOTAsIm5iZiI6MTc2NTk0MzA5MCwicGF0aCI6Ii80NTY0NTc5LzUyMDc4NTUyOS0wM2Y5ODdhNC1iZmJiLTRiY2YtOTE1OC1iMzg0ZmY4MWY1MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMTdUMDM0NDUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2FlM2Q5NTVlY2ZiY2QwNGM2YWQyYTE5ODIxMDIzMTIyOWM1NjAwNTU5MzY5YzZlMmYwOGE1OGU0ODZkYjZkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.iBcl00VbDBd0u7QLFdhYgSO9yCpeGKDOy2Rw8hlkI_o">
> If you hit this again, please let us know which specific error code this was with, and provide a current repro. thanks.

_The problem **still** occurs for me with Visual Studio v18.1.1._

The error shown for "Build only":
<img width="1015" height="191" alt="Image" src="https://github.com/user-attachments/assets/4dd03e7d-b750-4783-bff8-f0a22bf8f403" />
doesn't appear when "Build + Intellisense" is selected:
<img width="978" height="211" alt="Image" src="https://github.com/user-attachments/assets/c227c7fc-dc82-4966-8b01-acb9aa343132" />

(I followed the steps specified in the README of [https://github.com/shaneharper/Visual_Studio_Warning_Not_Shown_In_Error_List](https://github.com/shaneharper/Visual_Studio_Warning_Not_Shown_In_Error_List).)
