### ISSUE TITLE
C# Compiler should not allow out _ within Expression trees

### ISSUE THREAD

**Issue by Supermaxman** [dotnet/roslyn#20380]
This seems to be a problem related to not allowing local out parameters within Expression trees.
The problem is this: out parameters can be used in Expression trees, such as Lambda statements within LINQ Queries, but you are not allowed to use auto typed out parameters within Expression trees. If you want to use a function with an out parameter, but you do not care about the value of the out parameter, you are able to set the out parameter to _ as a discard without a compiler warning.

Example:

```
var canParse = new List<string>
    {
        "1",
        "x"
    }
    .AsQueryable()
    .Select(item => int.TryParse(item, out _))
    .ToList();
```

When you compile the program it will start the build process, but you will find yourself with the following error and warning:
```
Error		"csc.exe" exited with code -2146232797.	
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(71,5): error MSB6006: "csc.exe" exited with code -2146232797.

Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.CSharpSimplifyTypeNamesDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	
```

This was built and easily reproducible using .NET Framework 4.6.2 in a Console application in Visual Studio 2017 with the provided code sample.

```
Microsoft Visual Studio Enterprise 2017
Version 15.2 (26430.15) Release

Microsoft .NET Framework
Version 4.7.02046
```

**Comment by jcouv** [comment]
This was fixed in 15.1: https://github.com/dotnet/roslyn/pull/17170
I'll go ahead and close. Feel free to re-open if the version of Visual Studio 2017 is greater than 15.1.

**Comment by Supermaxman** [comment]
This still exists in Visual Studio 2017 Version 15.2.
My version:

```
Microsoft Visual Studio Enterprise 2017
Version 15.2 (26430.15) Release

Microsoft .NET Framework
Version 4.7.02046
```

**Comment by jcouv** [comment]
Re-opened. Thanks for the info.

**Comment by AlekseyTs** [comment]
Looks fixed to me:
```
Microsoft (R) Visual C# Compiler version 2.4.0.62101 (eb3f5baa)
Copyright (C) Microsoft Corporation. All rights reserved.

debug.cs(14,52): error CS8207: An expression tree may not contain a discard.
```

**Comment by Supermaxman** [comment]
@AlekseyTs This issue was still present for me in the listed version 15.2. 
I am seeing this fixed now that I am using the following version:

```
Microsoft Visual Studio Enterprise 2017
Version 15.3.5

Microsoft .NET Framework
Version 4.7.02046
```

Looks good in 15.3.5. Thanks!
