### ISSUE TITLE
Semantic errors no longer show up in the Error List or squiggles while you type

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#20424]
**Version Used**: 

d15rel 26620.00

**Steps to Reproduce**:

1. Open Roslyn.sln.
2. Open the SolutionExplorer_InProc.cs file.
3. Make some changes to the file so that it will be semantically incorrect. E.g., add calls to methods that don't exist.

**Expected Behavior**:

Errors should appear in the Error List, and corresponding squiggles should appear in the editor.

**Actual Behavior**:

No squiggles or errors appear for semantic errors, though we do get them for syntactic errors. Even after waiting a day, no errors appear. Completion lists, colorization, Parameter Help, and Quick Info all seem to be correct and update to properly reflect semantic changes. 

I've collected design-time build traces and a workspace structure log (from the [Roslyn Info Logger](https://github.com/jasonmalinowski/roslyn-info-logger)) and placed them under `\\mlangfs1\public\tomescht\Issue20424`.

**Comment by Pilchie** [comment]
@jasonmalinowski starting with you, but this might also end up with @heejaechang to adjust when we set the project load complete bit.

**Comment by TyOverby** [comment]
I'd also like to mention that go-to-def and autocomplete don't work.

**Comment by jasonmalinowski** [comment]
@TyOverby That would be unrelated from what we're tracking here. Please file a new bug.

**Comment by MattGertz** [comment]
Mondo escrow triage:  meets the bar.

**Comment by jasonmalinowski** [comment]
Closing as we believe the current impacting issue here (the aliases not being passed through) is now fixed. We'll reactivate if we see problems again.

**Comment by Pilchie** [comment]
Did we ever get a bug on @heejaechang to track still showing errors for open documents.

**Comment by dpoeschl** [comment]
In 26726.0.d15rel without LSL and with FSA, I'm never seeing errors, and the lightbulb is not blocking (so the errors will never show up).

**Comment by dpoeschl** [comment]
Added more data from my recent repro: \\<server>\public\davip\dumps\bugs\20424NoSemanticErrors

**Comment by jasonmalinowski** [comment]
@dpoeschl Looking at your logs there, it was difficult to figure out what is going on. Going to add some additional logging I think that we can use to figure it out.

**Comment by dpoeschl** [comment]
@jasonmalinowski Do we have any better ideas of what's going wrong here now, or have we done as much as we can until the next release?

**Comment by jasonmalinowski** [comment]
@dpoeschl I think there's some opportunity for adding additional logging, but that's about it I'm afraid.

**Comment by jasonmalinowski** [comment]
Closing this, it's almost a year old again.
