### ISSUE TITLE
TrivialTemporaryStorageService: _stream disposed by caller of ReadStream (crashes in monodevelop)

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#22085]
**Version Used**: 
2.3.0-beta1-61703.10 8f02e04893c4b53cf6ca11b064848888365914d3

**Steps to Reproduce**:
We see this in MonoDevelop which uses TrivialTemporaryStorageService. We see crashes with this callstack:
```
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.__Error.StreamIsClosed()
   at System.IO.MemoryStream.set_Position(Int64 value)
   at Microsoft.CodeAnalysis.TrivialTemporaryStorageService.StreamStorage.ReadStream(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.AbstractSyntaxTreeFactoryService.RecoverableSyntaxRoot`1.Recover(CancellationToken cancellationToken)
   at Roslyn.Utilities.AsyncLazy`1.GetValue(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.RecoverableWeakValueSource`1.GetValue(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory.CSharpSyntaxTreeFactoryService.RecoverableSyntaxTree.GetRoot(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetRootCore(CancellationToken cancellationToken)
```

**Expected Behavior**:
ReadStreamAsync returns the underlying _stream here:
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Host/TemporaryStorage/TrivialTemporaryStorageService.cs,49

Callers then dispose of the stream after reading it once:
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Host/SyntaxTreeFactory/AbstractSyntaxTreeFactoryService.AbstractRecoverableSyntaxRoot.cs,126

Since the stream leaks the storage, the caller disposes it, so we're left with a disposed stream. Next time someone reads it again, we'll try to "rewind", thus accessing a disposed stream.

**Actual Behavior**:
Should either make sure callers don't dispose a stream, or return a new copy of a stream (wasteful), or something else.

**Comment by AdamSpeight2008** [comment]
Should it return a `StreamReader`? rather than `stream`. So that when all of readers of the stream have been disposed, disposal of the stream can happen.

**Comment by sharwell** [comment]
💭 Seems like it should return a stream which wraps the underlying `MemoryStream`, to avoid disposing it.

**Comment by tmat** [comment]
Was this fixed by https://github.com/dotnet/roslyn/pull/59431?

**Comment by KirillOsenkov** [comment]
I believe it was, yes. Let's close this and if we still see issues, we'll open a new bug. Thanks!
