### ISSUE TITLE
Microsoft.CodeAnalysis.Scripting.CompilationErrorException: '(1,8): error CS1503

### ISSUE THREAD

**Issue by TylerHelmuth** [dotnet/roslyn#23123]
**Version Used**: 
.Net 4.6.1
VS 2015 w/ Update 3
Nuget Package: Microsoft.CodeAnalysis.CSharp.Scripting V2.4.0

**Steps to Reproduce**:
```
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Scripting;
using Microsoft.CodeAnalysis.Scripting;

namespace RoslynExperimentation
{
    class Program
    {
        static void Main(string[] args)
        {
            var c = new MyClass()
            {
                Description = "test"
            };

            var code = "using RoslynExperimentation;" +
                       "public class TestClass {" +
                       "  public string HelloWorld(MyClass c) {" +
                       "    return c.Description;" +
                       "  }" +
                       "}";

            var metadata = MetadataReference.CreateFromFile(typeof(MyClass).Assembly.Location);

            var scriptTask =
                CSharpScript.Create(
                        code: code,
                        options: ScriptOptions.Default.WithReferences(metadata),
                        globalsType: typeof(Globals))
                    .ContinueWith("new TestClass().HelloWorld(C)")
                    .RunAsync(new Globals { C = c });

            scriptTask.Wait();
            Console.WriteLine(scriptTask.Result.ReturnValue);
        }
    }

    public class MyClass
    {
        public string Description { get; set; }
    }

    public class Globals
    {
        public MyClass C { get; set; }
    }
}
```

**Expected Behavior**:
"test" is written to the Console.

**Actual Behavior**:
Error is thrown when executing .RunAsync

Unhandled Exception: Microsoft.CodeAnalysis.Scripting.CompilationErrorException:
(1,28): error CS1503: Argument 1: cannot convert from 
'RoslynExperimentation.MyClass [D:\Projects2\RoslynExperimentation\RoslynExperimentation\bin\Debug\RoslynExperimentation.exe]' to 
'RoslynExperimentation.MyClass [RoslynExperimentation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]'

**Comment by jcouv** [comment]
Tagging @tmat

**Comment by gafter** [comment]
Did you try looking at the error messages from the script before attempting to run it? Are there errors? Do they look correct?

**Comment by svick** [comment]
When I try running the code, the exception I get is: 

> Microsoft.CodeAnalysis.Scripting.CompilationErrorException: (1,28): error CS0103: The name 'c' does not exist in the current context

I think this error is correct (the casing of the `Globals` property `C` doesn't match the casing used in the continuation, `c`).

I used VS 2017, but I'm not sure how could that affect this. Can you share your whole project? What is the version of .Net you're running the code on? How are you running the code?

**Comment by TylerHelmuth** [comment]
Sorry, I forgot to undo something before I posted. I've corrected `.ContinueWith("new TestClass().HelloWorld(C)")` to pass big C to the HellowWorldMethod.  I've also updated the post to say .Net 4.6.1

I should also note that the script is fine if compiled normally with the rest of the code instead of with Roslyn.

Finally, if I using a native C# class like List<string> instead of my own class, everything works as normal
```
class Program
    {

        static void Main(string[] args)
        {
            var c = new List<string>();

            var code = "using System.Collections.Generic;" +
                       "public class TestClass {" +
                       "  public string HelloWorld(List<string> c) {" +
                       "    return \"hello\";" +
                       "  }" +
                       "}";

            var scriptTask =
                CSharpScript.Create(
                        code: code,
                        options: ScriptOptions.Default.WithReferences(typeof(List<string>).Assembly),
                        globalsType: typeof(Globals))
                    .ContinueWith("(new TestClass()).HelloWorld(C)")
                    .RunAsync(new Globals { C = c });

            scriptTask.Wait();
            Console.WriteLine(scriptTask.Result.ReturnValue);
        }
    }
    public class Globals
    {
        public List<string> C { get; set; }
    }
 ```

The problem seems to be around Roslyn matching the Global property type and the parameter type of the HelloWorld method.  The error message says it can't convert from 'RoslynExperimentation.MyClass [D:\Projects2\RoslynExperimentation\RoslynExperimentation\bin\Debug\RoslynExperimentation.exe]' to 'RoslynExperimentation.MyClass [RoslynExperimentation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]'.  The object names, RoslynExperimentation.MyClass, are the same, but its grabbing one out of the debug folder and the other from somewhere else.

**Comment by svick** [comment]
Sorry, I should have fixed the obvious capitalization error myself. Yeah, now I can see the exception you're reporting. To me, it looks like a bug in Roslyn.

As a guess, I think it could be related to the fact that the original script has two references to your assembly: one included by default with an unspeakable alias and one included by your `MetadataReference`. The continuation script then somehow can't reconcile the two references, I think.

**Comment by TylerHelmuth** [comment]
I think you're onto something with the Continuation Script comment.  When I remove the ContinueWith line and add a variable in the original script, it works
```
class Program
    {

        static void Main(string[] args)
        {
            var c = new MyClass
            {
                Description = "test"
            };

            var code = "using RoslynExperimentation;" +
                       "public class TestClass {" +
                       "  public string HelloWorld(MyClass c) {" +
                       "    return c.Description;" +
                       "  }" +
                       "}" +
                       "var x = (new TestClass()).HelloWorld(C);";

            var metadata = MetadataReference.CreateFromFile(typeof(MyClass).Assembly.Location);

            var scriptTask =
                CSharpScript.Create(
                        code: code,
                        options: ScriptOptions.Default.WithReferences(metadata),
                        globalsType: typeof(Globals))
                    .RunAsync(new Globals { C = c });

            scriptTask.Wait();
            Console.WriteLine(scriptTask.Result.Variables[0].Value);
        }
    }

    public class MyClass
    {
        public string Description { get; set; }
    }


    public class Globals
    {
        public MyClass C { get; set; }
    }
```

**Comment by TylerHelmuth** [comment]
I can also confirm that splitting it into a "continue from previous state" state produces the same error
```
class Program
    {

        static void Main(string[] args)
        {
            var c = new MyClass
            {
                Description = "hello"
            };

            var code = "using RoslynExperimentation;" +
                       "public class TestClass {" +
                       "  public string HelloWorld(MyClass c) {" +
                       "    return c.Description;" +
                       "  }" +
                       "}";

            var metadata = MetadataReference.CreateFromFile(typeof(MyClass).Assembly.Location);

            var scriptTask =
                CSharpScript.Create(
                        code: code,
                        options: ScriptOptions.Default.WithReferences(metadata),
                        globalsType: typeof(Globals))
                    .RunAsync(new Globals {C = c});
            scriptTask.Wait();


            scriptTask = scriptTask.Result.ContinueWithAsync("(new TestClass()).HelloWorld(C)",
                options: ScriptOptions.Default.WithReferences(metadata));
            scriptTask.Wait();

            Console.WriteLine(scriptTask.Result.ReturnValue);
        }
    }

    public class MyClass
    {
        public string Description { get; set; }
    }


    public class Globals
    {
        public MyClass C { get; set; }
    }
```

**Comment by tmat** [comment]
Seems to be similar to https://stackoverflow.com/questions/47394231/csharpscript-uses-incompatible-internal-type-representations-at-every-external-c

**Comment by tluyben** [comment]
Experiencing this issue as well; the Stackoverflow question is exactly what I am attempting and that brought me here. Hope some is able to resolve it as I cannot run without the continuation (aka; I don't know the next line of the script before it comes in and I cannot wait for all lines to be in).

**Comment by tluyben** [comment]
Does anyone know why this happens? I would still love to see a solution.

**Comment by GoldenCrystal** [comment]
I believe I've hit this issue as well there: https://github.com/GoldenCrystal/SolidSharp

Here's a session in my console application:
````
>var v = n(0); // Basically sets v to a SymbolicExpression of value 0
>v // Displays v
0
>n(0) + n(0) // Displays the result of summing two SymbolicExpressions of value 0
0
>v + v // Displays the result of summing two SymbolicExpressions of value 0
0
>v + n(0) // Try to do the same thing, but mix a variable and a dynamically generated expression
(1,1): error CS0019: Operator '+' cannot be applied to operands of type 'SymbolicExpression' and 'SymbolicExpression'
>v.GetType() == n(0).GetType() // Verify that both runtime types are indeed the same
System.Boolean:
True
>(SymbolicExpression)(object)v + n(0) // Trick the compiler into enforcing the correct type
0
````

This is the list of commands that can replayed to observe the results above:
````
var v = n(0); // Basically sets v to a SymbolicExpression of value 0
v // Displays v
n(0) + n(0) // Displays the result of summing two SymbolicExpressions of value 0
v + v // Displays the result of summing two SymbolicExpressions of value 0
v + n(0) // Try to do the same thing, but mix a variable and a dynamically generated expression
v.GetType() == n(0).GetType() // Verify that both runtime types are indeed the same
(SymbolicExpression)(object)v + n(0) // Trick the compiler into enforcing the correct type
````

It seems that in some cases, Roslyn fails to correctly identify that two type instances are the same, while they are indeed of the same runtime type later on.

I hope this will get fixed 🙂

**Comment by Seuntjie900** [comment]
I ran into the same issue with one of my projects, I was able to work around it by defining my method parameter as a dynamic instead of strongly typing it. In the example posted above, it would look something like:

var code = "using RoslynExperimentation;" +
                       "public class TestClass {" +
                       "  public string HelloWorld(dynamic c) {" +
                       "    return c.Description;" +
                       "  }" +
                       "}";

With the rest of the code as is. It's far from ideal, but I am able to execute the code and call my method without the compiler error. I don't think this will work for GoldenCrystals scenario though.

**Comment by svick** [comment]
I believe this was fixed by https://github.com/dotnet/roslyn/pull/38550. When I run the code from the first post using version 3.4.0-beta3-19511-04 from [MyGet](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis.CSharp), I no longer get the error.

**Comment by jaredpar** [comment]
Closing as this does appear to be fixed now.

**Comment by Tom-Lu** [comment]
Still facing same issue with Roslyn release 3.10.0, not sure why this still happened.

`Microsoft.CodeAnalysis.Scripting.CompilationErrorException: '(1,83): error CS1503: Argument 1: cannot convert from 'TestLite.Core.Common.ExecutionContext [C:\Source\TestLite\testlite.net\TestLite.Net\TestLite.UI\bin\Debug\netcoreapp3.1\TestLite.Core.dll]' to 'TestLite.Core.Common.ExecutionContext [TestLite.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]''
`
![image](https://user-images.githubusercontent.com/3454238/124065221-e4804e80-da68-11eb-85a9-dadfb248a54d.png)
