### ISSUE TITLE
OOP crashes with unrecoverable error after installing FxCop analyzers VSIX and NuGet

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#23766]
**Version Used**: VS2017 Version 15.5.0 RTW

**Steps to Reproduce**:

1.	Install the below FxCop analyzers VSIX: `<%internal_build_drops%>\Roslyn\RoslynAnalyzers\20171213.3\VSSetup\Microsoft.CodeAnalysis.FxCopAnalyzers.Setup.vsix`
2.	Create a new C#/VB class library project and verify analyzers run fine
3.	Install the latest analyzer beta2 NuGet package: https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/2.6.0-beta2

**Expected Behavior**:
VS de-dupes the analyzers from VSIX and NuGet and runs from any one source.

**Actual Behavior**:
I get the below gold bar for unrecoverable VS error:
![image](https://user-images.githubusercontent.com/10605811/33960547-ed5361ee-dfff-11e7-8cac-064a001d2cc3.png)

4. Close and re-open VS and open the same solution

**Actual Behavior**:
You again get the same gold bar. Only uninstalling the NuGet will avoid the OOP crash.

**Comment by mavasani** [comment]
Fixed now.

**Comment by alfredmyers** [comment]
Still happening on:
- Visual Studio 15.5.3
- Microsoft.CodeAnalysis.FxCopAnalyzers 2.6.0
- VSIX 2.6.0.6241303

**Comment by heejaechang** [comment]
15.5.3 doesn't have fix yet.
