### ISSUE TITLE
"When variable type is apparent" doesn't apply to array initialization

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#23907]
![image](https://user-images.githubusercontent.com/1103906/34284997-4f721560-e72a-11e7-959a-639088c6bd82.png)

``` C#
using System.Threading.Tasks;

class Program
{
    static void Main(string[] args)
    {
        var tasks = new Task[0];
    }
}

```

Expected: No messages
Actual: For IDE0008 "use explicit type instead of var" not fire

**Comment by jcouv** [comment]
This seems by-design. Type is apparent in `new Task[0]`.
@sharwell to confirm.

**Comment by jcouv** [comment]
Never mind. Got confused. Definitely a bug :-)

**Comment by jcouv** [comment]
Fix is merged for 15.6 preview 4

**Comment by davkean** [comment]
Heads up, this isn't fixed: https://github.com/dotnet/roslyn/issues/26531.
