### ISSUE TITLE
Opening a Visual Basic file resulted in >100 editor errors about NullReferenceException in DeferredContentFrameworkElementFactory.CreateElement

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#26672]
No repro, just opened a Visual Basic source file, resulting in:

```

ERROR | System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.   
at Microsoft.CodeAnalysis.Editor.QuickInfo.DeferredContentFrameworkElementFactory.CreateElement(IDeferredQuickInfoContent deferredContent)   
at Microsoft.CodeAnalysis.Editor.QuickInfo.QuickInfoDisplayDeferredContentConverter.CreateFrameworkElement(IDeferredQuickInfoContent deferredContent, DeferredContentFrameworkElementFactory factory)   
at Microsoft.CodeAnalysis.Editor.QuickInfo.DeferredContentFrameworkElementFactory.CreateElement(IDeferredQuickInfoContent deferredContent)   
at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Presentation.QuickInfoPresenter.QuickInfoPresenterSession.AugmentQuickInfoSession(IList`1 quickInfoContent, ITrackingSpan& applicableToSpan)   
at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Presentation.QuickInfoPresenter.QuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 quickInfoContent, ITrackingSpan& applicableToSpan)   
at Microsoft.VisualStudio.Language.Intellisense.Implementation.LegacyQuickInfoSource.AugmentQuickInfoSession(IAsyncQuickInfoSession session, IList`1 content, ITrackingSpan& applicableToSpan)   
at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<TryComputeContentFromLegacySourceAsync>d__45.MoveNext() --- End of stack trace from previous location where exception was thrown ---    
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeSourceContentAsync>d__44.MoveNext()    
--- End of inner exception stack trace 
--- ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.   
at Microsoft.CodeAnalysis.Editor.QuickInfo.DeferredContentFrameworkElementFactory.CreateElement(IDeferredQuickInfoContent deferredContent)   
at Microsoft.CodeAnalysis.Editor.QuickInfo.QuickInfoDisplayDeferredContentConverter.CreateFrameworkElement(IDeferredQuickInfoContent deferredContent, DeferredContentFrameworkElementFactory factory)   
at Microsoft.CodeAnalysis.Editor.QuickInfo.DeferredContentFrameworkElementFactory.CreateElement(IDeferredQuickInfoContent deferredContent)   
at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Presentation.QuickInfoPresenter.QuickInfoPresenterSession.AugmentQuickInfoSession(IList`1 quickInfoContent, ITrackingSpan& applicableToSpan)   
at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Presentation.QuickInfoPresenter.QuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 quickInfoContent, ITrackingSpan& applicableToSpan)   
at Microsoft.VisualStudio.Language.Intellisense.Implementation.LegacyQuickInfoSource.AugmentQuickInfoSession(IAsyncQuickInfoSession session, IList`1 content, ITrackingSpan& applicableToSpan)   
at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<TryComputeContentFromLegacySourceAsync>d__45.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---    
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeSourceContentAsync>d__44.MoveNext()<---
-- | --
```

Looked at [ActivityLog.zip](https://github.com/dotnet/roslyn/files/1978545/ActivityLog.zip) and this was output about ~100 times.

**Comment by cativity** [comment]
I have this issue too.

**Comment by jinujoseph** [comment]
also reported [link](https://developercommunity.visualstudio.com/content/problem/254587/scroll-in-ide-error-dialog-prompts.html)

**Comment by JieCarolHu** [comment]
@davkean  Could you please install the latest 15.8 preview 2 to try again? We refactored quick info to use Async QuickInfo editor API and all these DeferredContent are gone now. Thanks

**Comment by GSyren** [comment]
Still there in v. 15.7.2, at least in the Community edition.

**Comment by jinujoseph** [comment]
Fixed in 15.8 preview2

**Comment by Allann** [comment]
I'm running 15.8 preview 2 and I'm constantly getting this issue.  I don't think it's fixed.

  <entry>
    <record>1173</record>
    <time>2018/06/13 21:46:04.263</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.AggregateException: One or more errors occurred. ---&gt; System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.TSServerProxy.GetQuickInfoAtPosition(ITSServerProxyEndpoint endpoint, Document document, SnapshotPoint snapshotPoint, IExternalDocumentationResolver xmlDocService, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.QuickInfo.TypeScriptQuickInfoSourceProvider.QuickInfoSource.&lt;&gt;c__DisplayClass3_0.&lt;GetQuickInfoItemAsync&gt;b__0(TSServerProxy proxy, ITSServerProxyEndpoint endpoint, CancellationToken operationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.InvokeTSServerEndpoint[T](TSServerProxy tsServerProxy, ITSServerProxyEndpoint endpoint, OneOrMultipleDocuments oneOrMultipleDocuments, TSServerOperation`1 operation, TSServerOperation refreshOperation, CancellationToken ct)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.&lt;&gt;c__DisplayClass19_1`1.&lt;InvokeTSServerViaSchedulerAsync&gt;b__1(CancellationToken ct)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Threading.PriorityWorkScheduler.&lt;&gt;c__DisplayClass6_0.&lt;RunNextTaskAsync&gt;b__0()&#x000D;&#x000A;   at System.Threading.Tasks.Task`1.InnerInvoke()&#x000D;&#x000A;   at System.Threading.Tasks.Task.Execute()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.&lt;InvokeTSServerViaSchedulerAsync&gt;d__19`1.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.&lt;InvokeTSServerAsync&gt;d__17`1.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.QuickInfo.TypeScriptQuickInfoSourceProvider.QuickInfoSource.&lt;GetQuickInfoItemAsync&gt;d__3.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&lt;ComputeSourceContentAsync&gt;d__44.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;---&gt; (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.TSServerProxy.GetQuickInfoAtPosition(ITSServerProxyEndpoint endpoint, Document document, SnapshotPoint snapshotPoint, IExternalDocumentationResolver xmlDocService, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.QuickInfo.TypeScriptQuickInfoSourceProvider.QuickInfoSource.&lt;&gt;c__DisplayClass3_0.&lt;GetQuickInfoItemAsync&gt;b__0(TSServerProxy proxy, ITSServerProxyEndpoint endpoint, CancellationToken operationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.InvokeTSServerEndpoint[T](TSServerProxy tsServerProxy, ITSServerProxyEndpoint endpoint, OneOrMultipleDocuments oneOrMultipleDocuments, TSServerOperation`1 operation, TSServerOperation refreshOperation, CancellationToken ct)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.&lt;&gt;c__DisplayClass19_1`1.&lt;InvokeTSServerViaSchedulerAsync&gt;b__1(CancellationToken ct)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Threading.PriorityWorkScheduler.&lt;&gt;c__DisplayClass6_0.&lt;RunNextTaskAsync&gt;b__0()&#x000D;&#x000A;   at System.Threading.Tasks.Task`1.InnerInvoke()&#x000D;&#x000A;   at System.Threading.Tasks.Task.Execute()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.&lt;InvokeTSServerViaSchedulerAsync&gt;d__19`1.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.&lt;InvokeTSServerAsync&gt;d__17`1.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.QuickInfo.TypeScriptQuickInfoSourceProvider.QuickInfoSource.&lt;GetQuickInfoItemAsync&gt;d__3.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&lt;ComputeSourceContentAsync&gt;d__44.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)&lt;---&#x000D;&#x000A;</description>
  </entry>

**Comment by davkean** [comment]
That stack looks very different and isn't Visual Basic. Can you Help -> Send Feedback -> Report a Problem sot that it gets routed to the right team (TypeScript).

**Comment by Allann** [comment]
ok

**Comment by scottmcd9999** [comment]
I have the same issue running 15.7.3:

 <description>System.AggregateException: One or more errors occurred. ---&gt; System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.QuickInfo.DeferredContentFrameworkElementFactory.CreateElement(IDeferredQuickInfoContent deferredContent)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.QuickInfo.QuickInfoDisplayDeferredContentConverter.CreateFrameworkElement(IDeferredQuickInfoContent deferredContent, DeferredContentFrameworkElementFactory factory)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.QuickInfo.DeferredContentFrameworkElementFactory.CreateElement(IDeferredQuickInfoContent deferredContent)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Presentation.QuickInfoPresenter.QuickInfoPresenterSession.AugmentQuickInfoSession(IList`1 quickInfoContent, ITrackingSpan&amp; applicableToSpan)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Presentation.QuickInfoPresenter.QuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 quickInfoContent, ITrackingSpan&amp; applicableToSpan)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LegacyQuickInfoSource.AugmentQuickInfoSession(IAsyncQuickInfoSession session, IList`1 content, ITrackingSpan&amp; applicableToSpan)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&lt;TryComputeContentFromLegacySourceAsync&gt;d__45.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&lt;ComputeSourceContentAsync&gt;d__44.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;---&gt; (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.QuickInfo.DeferredContentFrameworkElementFactory.CreateElement(IDeferredQuickInfoContent deferredContent)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.QuickInfo.QuickInfoDisplayDeferredContentConverter.CreateFrameworkElement(IDeferredQuickInfoContent deferredContent, DeferredContentFrameworkElementFactory factory)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.QuickInfo.DeferredContentFrameworkElementFactory.CreateElement(IDeferredQuickInfoContent deferredContent)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Presentation.QuickInfoPresenter.QuickInfoPresenterSession.AugmentQuickInfoSession(IList`1 quickInfoContent, ITrackingSpan&amp; applicableToSpan)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Presentation.QuickInfoPresenter.QuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 quickInfoContent, ITrackingSpan&amp; applicableToSpan)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LegacyQuickInfoSource.AugmentQuickInfoSession(IAsyncQuickInfoSession session, IList`1 content, ITrackingSpan&amp; applicableToSpan)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&lt;TryComputeContentFromLegacySourceAsync&gt;d__45.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&lt;ComputeSourceContentAsync&gt;d__44.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)&lt;---&#x000D;&#x000A;</description>

**Comment by scottmcd9999** [comment]
I just updated to 15.8, and I still get the issue.

 

Scott

**Comment by davkean** [comment]
What's happening, is VS crashing or are you getting this from ActivityLog.xml? Where are you pulling the stack from?

**Comment by scottmcd9999** [comment]
I get a notif during editing, and I pull it from ActivityLog.xml

 

Scott

**Comment by davkean** [comment]
@JieCarolHu @jinujoseph Got a report that this is still happening on 15.8 Preview 2. 

> Could you please install the latest 15.8 preview 2 to try again? We refactored quick info to use Async QuickInfo editor API and all these DeferredContent are gone now. Thanks

This method still exists: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core.Wpf/QuickInfo/DeferredContentFrameworkElementFactory.cs#L31. Was it supposed to be removed?

**Comment by JieCarolHu** [comment]
@davkean It is gone in master-vs-deps branch. I am not entirely sure when it will be merged into master.

**Comment by davkean** [comment]
@jinujoseph mentioned:

> Fixed in 15.8 preview2

@jinujoseph Do you know what actual release this will be making?

**Comment by jinujoseph** [comment]
if this is marked fixed in 15.8.Preview2 then it ideally it should be in 15.8.Preview2. 
can you point to the report where its been seen for 15.8.Preview2 ?

**Comment by davkean** [comment]
https://github.com/dotnet/roslyn/issues/26672#issuecomment-400297325

**Comment by jinujoseph** [comment]
Was there any customer report from 15.8.Preview2 ?

**Comment by davkean** [comment]
@scottmcd9999 commented that he hit this on VS 15.8 at which time only preview 2 was released. Preview 3 was only released today.

**Comment by scottmcd9999** [comment]
Please disregard my error report. My VS upgrade failed, and I was still on 15.7.4 when I reported this. My apologies.

 

Scott McDaniel

**Comment by davkean** [comment]
np, so the question is, is the code that fixed this merged in 15.8? I've not been using VB recently so can't confirm its fixed or not fixed.

**Comment by jinujoseph** [comment]
yes , the code has significantly changed after moving to editor api for quickinfo and was merged for 15.8.Preview2 , and this issue should not be happening in 15.8.Preview2 or latest.

Pls reopen if you find otherwise.

**Comment by jhinder** [comment]
I get this exception in my local build (current `master`, revision c4189de0), but not in 15.8 Preview 4, which is curious.

Repro:

1. Open `EditorServicesTest2.vbproj` (from the Roslyn repo).
2. Go to `IntelliSense/CSharpCompletionCommandHandlerTests.vb`, then to `TestMatchWithTurkishIWorkaround1()` (line 2698).
3. Hover over the `GetType` in line 2708.

The NRE happens because `quickInfoDisplay.CapturesText` is `null` in `CreateFrameworkElement` (2nd stack frame).
