### ISSUE TITLE
Running Code Metrics on CPS project targeting .NET Core/.NET Standard displays an error 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#27001]
**Version Used**: 
15.8 Preview 3

**Steps to Reproduce**:

1. File -> Console App (.NET Core) or Class Library (.NET Standard)
2. Analyze -> Calculate Code Metrics -> For [ConsoleApp]

**Expected Behavior**:
Succeeded

**Actual Behavior**:
```
Message: An error occurred while calculating code metrics for target file 'c:\users\davkean\Source\Repos\ConsoleApp341\ConsoleApp341\bin\Debug\netcoreapp2.0\ConsoleApp341.dll' in project ConsoleApp341. Could not identify platform for 'c:\users\davkean\Source\Repos\ConsoleApp341\ConsoleApp341\bin\Debug\netcoreapp2.0\ConsoleApp341.dll'.
```

Note: If you target .NET Framework from the project than it succeeds.

**Comment by davkean** [comment]
Make note, we recently changed Project.Kind which unblocked this path and Code Metrics now shows up.

**Comment by davkean** [comment]
Area-External means "we don't own it". We own this.

**Comment by mavasani** [comment]
Tagging @jinujoseph 

The Code Metrics command handlers are currently statically hooked up with project type GUIDs, hence always show up for all C#, VB and C++ projects, until the Metrics Package gets loaded in VS (which happens when either user first attempts to calculate code metrics or opens the Code Metrics results window). Run Code Analysis command(s) on the other hand has duplicate handling in the shell and StanCore assemblies, but is dynamically setup only for legacy C# and VB project system. I talked with @jinujoseph and we are going for the following approach:

15.8 - Gracefully fail for attempted "Calculate Code Metrics" for C# and VB CPS projects. Note that after the first attempt, the menu will not show up for CPS projects.
16.0 - Hide the command by default for all C# and VB projects, so we can gather telemetry and usage info for this feature and make a call on whether to deprecate it in VS in a subsequent release and replace it with a standard analyzer/external tool to report code metrics OR continue support in VS, which would mean properly hook up all the handlers.

**Comment by davkean** [comment]
Feedback here: https://developercommunity.visualstudio.com/content/problem/30872/support-code-metrics-for-net-core-projects.html.

**Comment by mavasani** [comment]
@davkean There are couple of reasons not to do your suggested change now:

1. For long term (16.0), we want the Code metrics feature support to be uniform across project systems and TFMs. If we decide to deprecate it or remove it from VS, it will be removed for all managed projects. If not, it will be fully supported for both project systems and all TFMs. If we decided to do the latter, then we will move the code metrics implementation to be source based analysis, which should work for all managed projects. So, all the current command handler functionality for Code metrics commands will just work.
2. Risk: My proposed fix for 15.8 is the simplest low risk fix to gracefully tell the users it is not supported for now. This fix will be reverted for 16.0 when we deprecate or properly support code metrics for all scenarios.

**Comment by davkean** [comment]
Help me understand the risk with using context based rules? Here's an example of a definition: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs#L22.

**Comment by mavasani** [comment]
On second thought, I feel we should do **nothing** here in 15.8 and instead figure out the story for Code Metrics for 16.0: deprecate it or fully support it for all TFMs, especially as we are very sure that we want to deprecate binary FxCop and the FxCop analysis engine that current Code Metrics implementation is based upon in 16.0.
Current experience for CPS projects, though not ideal, neither blocks any supported feature nor leads to a crash/hang/performance issue to warrant a short term fix. @jinujoseph to make a call.

**Comment by ardalis** [comment]
I'd very much like to see Code Metrics support added for Core/Standard projects. Please consider it as a priority to include in an upcoming (soon) release, since currently behavior feels like VS is going backward, losing functionality it's had for many years/versions. Thanks!

**Comment by mavasani** [comment]
Fixed with internal [VSO PR](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/133019?_a=overview). The fix should be available in Dev16 P1.

**Comment by mavasani** [comment]
To clarify: With Dev16 P1, Code Metrics should work for all C# and VB projects.

Given the number of customer requests, we have also ported Code metrics related FxCop rules to analyzers with https://github.com/dotnet/roslyn-analyzers/pull/1740. We also plan to provide a command line executable, such as Metrics.exe in pre-Dev15 versions - https://github.com/dotnet/roslyn-analyzers/issues/1741 tracks that work.

**Comment by xt449** [comment]
This error is still present for .NET Core Projects. (.net core version 2.1) (VS Version 15.8.1)

```Create .NET Core Console Application
Calculate Code Metrics```

**Comment by mavasani** [comment]
This should work with Dev16 Preview1. Alternatively, you can build Metrics.csproj from Roslyn-analyzers repo and use the built exe to generate a code metrics report from command line.

**Comment by mavasani** [comment]
See https://github.com/dotnet/roslyn-analyzers/pull/1754 for usage of Metrics.exe.

**Comment by bearslumber** [comment]
What version of visual studio is Dev16 Preview 1?
How does that equate to Visual Studio versions 15.x.x?

**Comment by mavasani** [comment]
@bearslumber It is not part of VS2017 (i.e. version 15.x.x or Dev15), but should be part of VS2019 (i.e., version 16.x.x or Dev16). See https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview.
