### ISSUE TITLE
Change name of 'Roslyn SDK Project Templates VSIX' to 'Roslyn SDK VSIX'

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#2815]
Now that the syntax visualizer and project templates have been merged into a singe VSIX, we should just call it 'Roslyn SDK.vsix' and '.NET Compiler Platform SDK' since -

1. This will make it clear that this is the only thing users need to get and
2. The new name will take up less space in all the places where the string will show up :)
![capture2](https://cloud.githubusercontent.com/assets/10579684/7663346/cb709d0e-fb1d-11e4-9493-d8eb0261d7aa.PNG)

![capture](https://cloud.githubusercontent.com/assets/10579684/7663332/a24f6fe0-fb1d-11e4-84e8-dbd0231c1364.PNG)

Logging this issue so that we can change the branding in all required places.

**Comment by jmarolf** [comment]
Fixed with internal changeset 1474285

**Comment by jmarolf** [comment]
@shyamnamboodiripad could you please verify?

**Comment by lgolding** [comment]
I verified that the Roslyn SDK.vsix file is renamed, and that the title in the Extensions and Updates dialog is not ".NET Compiler Platform SDK".

There is still an issue because the description of that VSIX suggests that it includes the Syntax Visualizer, which tempted me to uninstall the (separate) Syntax Visualizer VSIX, because I thought I had two of them now. Do you want to change the wording of the description?

**Comment by jmarolf** [comment]
Fixed with internal changeset 1483043

**Comment by lgolding** [comment]
Verified as fixed.
