### ISSUE TITLE
Inline temporary variable codefix removes indentation when VS does not know how to indent the target line

### ISSUE THREAD

**Issue by binki** [dotnet/roslyn#32024]
**Version Used**: 2.11.0-beta1-63519-03+4c7d79a254288388d97d793c4087db6ebf00d2fd

**Steps to Reproduce**:

1. Create a program which uses a variable on a line which VS is unable to automatically reindent.
2. Use the “Inline temporary variable” codefix on the variable’s declaration.
3. Observe that all indentation is removed instead of preserved.

Example program:

```csharp
using System;

class Program
{
    static void Main(string[] args)
    {
        var value = 2;
        foreach (var x in new[]
        {
            1,
            value,
        })
        {
            Console.WriteLine($"x={x}");
        }
    }
}
```

In this program, triggering VS to automatically reindent things (by deleting and retyping the closing `}` for the `class`) will never touch three lines starting from the line containing `1,`. This is because VS does not think it knows how to indent those lines, so it leaves them alone in an attempt to avoid displeasing the developer.

**Expected Behavior**:

```csharp
using System;

class Program
{
    static void Main(string[] args)
    {
        foreach (var x in new[]
        {
            1,
            2,
        })
        {
            Console.WriteLine($"x={x}");
        }
    }
}
```

**Actual Behavior**:

```csharp
using System;

class Program
{
    static void Main(string[] args)
    {
        foreach (var x in new[]
        {
            1,
2,
        })
        {
            Console.WriteLine($"x={x}");
        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
This has been fixed.  You get this now:

![image](https://user-images.githubusercontent.com/4564579/199118172-df869529-7185-4ce0-b965-c417aec5bcb8.png)

**Comment by binki** [comment]
@CyrusNajmabadi Thanks!

I tried testing this in VisualStudio-17.3.6 with Roslyn-4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea. I still get the issue. What version is this fixed in so that I can validate it?

**Comment by CyrusNajmabadi** [comment]
The duck was merged 4 days ago: https://github.com/dotnet/roslyn/pull/65021

It will still have to flow into vs and then get released.

**Comment by binki** [comment]
I see, thanks! I don’t know how to figure out when that will be released, so I will trust your work ;-).
