### ISSUE TITLE
Formatting `x is {} && y` introduces a newline

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#34683]
![format-braces](https://user-images.githubusercontent.com/12466233/55431119-91935600-5544-11e9-9a10-d1cbcfbc596b.gif)

FYI @gafter

**Comment by sharwell** [comment]
Is this not already fixed by #34619?

**Comment by jcouv** [comment]
#34619 didn't fix this. It was about the space between the curlies. 
The present issue is about a newline (wrongly) getting inserted after the `{}` pattern and before `&&`.

**Comment by jcouv** [comment]
Ran into another case:


![image](https://user-images.githubusercontent.com/12466233/57264611-aa9d9400-7027-11e9-8e55-167b1c13368f.png)

![image](https://user-images.githubusercontent.com/12466233/57264620-b5582900-7027-11e9-89af-218da7951d62.png)
