### ISSUE TITLE
IDE005 "Fix formatting" does a poor job with a switch expression as the body of an expression-bodied method

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#34962]
Given this method

``` c#
        public static NullableAnnotation EnsureCompatible(this NullableAnnotation a, NullableAnnotation b) =>
            (a, b) switch
            {
                (NullableAnnotation.Oblivious, _) => b,
                (_, NullableAnnotation.Oblivious) => a,
                _ => a < b ? a : b,
            };
```

The IDE005 "Fix formatting" diagnostic wants the body of the switch expression (curly braces and what is between them) to be less indented by four spaces.  That seems wrong in this context.

**Comment by sharwell** [comment]
This was already fixed, but somehow isn't part of the build being used. I need to look into whether this the formatter in the IDE is too old, or the formatter in the NuGet package is too old.

**Comment by jcouv** [comment]
FWIW, I'm still seeing this in 16.2p4:
![image](https://user-images.githubusercontent.com/12466233/61165490-1263d580-a4d6-11e9-935b-6413ac79500c.png)

**Comment by sharwell** [comment]
The new analyzers were applied to Roslyn in #37433 so this should now be fixed.
