### ISSUE TITLE
Microsoft.VisualStudio.LanguageServices 3.1.0 on NuGet.org has dependencies that are not on NuGet.org

### ISSUE THREAD

**Issue by markrendle** [dotnet/roslyn#36056]
The latest stable [Microsoft.VisualStudio.LanguageServices NuGet package](https://www.nuget.org/packages/Microsoft.VisualStudio.LanguageServices/3.1.0) has a dependency on one package that is not on NuGet.org at all, and another on one which is a whole major version behind.

- [M.CA.EditorFeatures.Common 3.1.0](https://www.nuget.org/packages/Microsoft.CodeAnalysis.EditorFeatures.Common/) -> 404
- [M.CA.EditorFeatures.Wpf 3.1.0](https://www.nuget.org/packages/Microsoft.CodeAnalysis.EditorFeatures.Wpf/) -> Latest version 2.8.2

**Comment by ravero** [comment]
I'm having the same issue.

**Comment by ravero** [comment]
This issue is open for about a month and there's no comments on that. Is there any kind of workaround? Why this happening? Are you referencing packages published on internal NuGet feeds only? Can't you provide those packages so we can make a local feed to resolve this issue? This is really impacting our extension development.

**Comment by jmarolf** [comment]
@ravero 	see here: https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis.EditorFeatures.Common

@genlu 	and @jinujoseph 	can we fix this issue so all the packages we upload to nuget also include their dependencies

**Comment by genlu** [comment]
As @jmarolf recommended, you should be able to find those packages on roslyn myget feed. 

Some quick context: we decided not to publish some of the editor related packages when 2.9 was released, because they have dependencies on VS packages from other teams, and we are not able to get them to publish those packages on NuGet whenever Roslyn releases a new version. Since we don't want to block our package release on the dependencies and those packages are only consumed by teams internally, we have asked them to use our myget feed instead.

That said, sounds like there's some dependency changes in Roslyn for 3.1. @JoeRobich could you please take a look at this?

**Comment by ravero** [comment]
@jmarolf the MyGet feed lists only beta versions of those packages, is it right? 
Which version should I use to fill the dependency for the `Microsoft.VisualStudio.LanguageServices` current stable release?

**Comment by ravero** [comment]
Also I've checked that version 3.2.0-beta3-final listed in Nuget suffers from the same issue.

**Comment by JoeRobich** [comment]
This issue was resolved with https://github.com/dotnet/roslyn/pull/36283

**Comment by ravero** [comment]
This issue is closed but it isn't resolved:

- The stable version of the package version `3.1.0` was just skipped on nuget.org
- The stable version of the package version `3.2.0` still doesn't install correctly and is dependent upon packages not published in nuget.org: `Microsoft.CodeAnalysis.InteractiveHost`

As shown in the example screenshot:
<img width="1154" alt="Screen Shot 2019-08-04 at 20 51 59" src="https://user-images.githubusercontent.com/1834963/62431055-6e4b0400-b6fa-11e9-8774-128b62fe737c.png">

@JoeRobich can you help us with this? We have an extension that is shared among VS Windows and VS Mac and we're having a hard time trying to keep the common libraries in sync since we can't upgrade then in Windows and the previous versions don't work right in VS Mac.

**Comment by JoeRobich** [comment]
@Ravero I am publishing 3.2.1 packages now which removes the InteractiveHost dependency regression. The search should update shortly.

**Comment by ravero** [comment]
@JoeRobich I could find the updated package and now it's working fine for adding to a VSIX project. Thanks! 🙏🏻
