### ISSUE TITLE
VS2019, C# : Cannot peek inside an active peek unless the current peek target is already opened as a proper file (applies only to non-std peek target symbols)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36294]
VSF_TYPE_MARKDOWNSteps:

1. Have different files with different custom types and methods.
2. Close them all except one that uses types/methods from other files.
3. Peek into any such custom type or method definition.
4. Inside that peek window, only symbols from the standard library and symbols local to the target file (of the peek) are properly highlighted and you can peek at them.
5. If you open the file of the target of (3), the peek window in (4) should have the proper highlighting and you can peek at them properly.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/482007/vs2019-c-cannot-peek-inside-an-active-peek-unless.html
VSTS ticketId: 814177_
_These are the original issue comments:_

Visual Studio Feedback System on 3/7/2019, 08:11 PM (95 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 3/8/2019, 00:55 AM (94 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

Sara Shi [MSFT] on 3/12/2019, 02:47 AM (90 days ago): <p>Thank you for your feedback! I tried to repro the issue, </p><ol>
<li>Create a console app, add Box.cs</li><li> add reference of Box.cs in Program.cs</li><li> set caret at Box, invoke 'peek Definition'</li><li>inside the peek window, set caret at symbols ,invoke 'peek definition'<p><img src="https://developercommunity.visualstudio.com/storage/temp/62980-capture1.png"></p><strong></strong><u></u><sub></sub><sup></sup></li><li>open Box.cs, we can invoke peek window.<p><img src="https://developercommunity.visualstudio.com/storage/temp/62981-capture2.png"></p></li></ol><p>Could you confirm if my steps are correct and what do you mean of step 4,5? Could you provide some more detailed description or screenshots follow the attached project <a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/62970-consoleappc.zip">consoleappc.zip</a> to help us better understand this scenario? </p><p>We look forward to hearing from you!</p>

Muhammad Nael [MSFT] on 3/12/2019, 06:22 AM (90 days ago): <p>Hi!</p><p>I modified the project and included it with 2 screenshots. If `Thing` in `Box` were a symbol from the .NET 'standard library' (I don't know what else to call it), it wouldn't have the same issue. The issue shows in the `Box.cs-closed` screenshot.</p><p>* Box.cs is not open. `Thing` is not highlighted and cannot be peeked into.</p><p><img src="https://developercommunity.visualstudio.com/storage/attachments/63049-boxcs-closed.png"></p><p>* Box.cs is open and `Thing` is properly highlighted and reachable by peek in the peek into Box.cs from Program.cs.</p><p><img src="https://developercommunity.visualstudio.com/storage/attachments/63050-boxcs-opened.png"></p>

Visual Studio Feedback System on 3/12/2019, 09:35 PM (89 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

Visual Studio Feedback System on 4/10/2019, 03:03 AM (61 days ago): <p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

Leon(Work) Yang on 6/4/2019, 01:35 PM (6 days ago): <strong>(private comment)</strong><p>similar issue with Mouse Click got to definition, the peek view is not recursive , I guess it's same root cause.</p><p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/76837-mouseclickgotodefinition.png">mouseclickgotodefinition.png</a></p>

_These are the original issue solutions:_
(no solutions)

**Comment by Sebastriani** [comment]
This is a regression it works fine in Visual Studio 2017, I should add that if you peek a definition and then try to do a "Go to definition" it throws a message windows saying "Cannot navigate to the symbol under the caret.

**Comment by guiAlberto** [comment]
> This is a regression it works fine in Visual Studio 2017, I should add that if you peek a definition and then try to do a "Go to definition" it throws a message windows saying "Cannot navigate to the symbol under the caret.
> This is so frustrating, I'll have to o back to VS2017...

I'm almost going back to VS2017 too. Would be great to have this issue fixed soon...

**Comment by narfanar** [comment]
Not certain yet, but it seems to be working again after updating to `16.3.0 Preview 1.0` (I was updating from `16.1.0 Preview 3.0`, IIRC).

**Comment by Sebastriani** [comment]
@narfanar I have updated to 16.1.6 and still have the problem. Latest version at this time is 16.2.1 but I didn't have the time to update it yet and see what happens.

**Comment by tziemek** [comment]
Seems fixed in `16.3.0 Preview 2.0`. Highlighting works for types from other assemblies,  even when they are not open in another editor window. Can anybody confirm?

**Comment by Sebastriani** [comment]
Visual Studio 2019 16.2.3 and the problem still persists. And it's not only than you cannot peek inside a peek (even if the file is open in my case) but you can't either "Go to Definition"...

**Comment by HarleeDavidson** [comment]
Visual Studio 2019 16.2.3, regression, even if the files are already open, Peek **and** Go to Definition both return the error now:  "Cannot navigate to the symbol under the caret."

**Comment by narfanar** [comment]
Wait till 16.3.x+ (any Previews) is available to you. Should be fixed there.

**Comment by chborl** [comment]
I have verified on the latest build 16.4.0 Preview 2.0 [29315.20.master] that this is fixed.
