### ISSUE TITLE
Using a git worktree `Microsoft.Build.Tasks.Git.targets` fails to verify

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#37141]
**Version Used**: 2ee0e35d5d4f2020850534f492c1fb031782a102

**Steps to Reproduce**:

1. Run `restore`
2. Run `build`

```
...
C:\Users\<username>\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19324-01\build\Microsoft.Build.Tasks.Git.targets(10,5): error : Error reading git repository information: Path specified in file 'C:\<root>\.git' is invalid. [C:\<root>\src\VisualStudio\Setup.Dependencies\Roslyn.VisualStudio.Setup.Dependencies.csproj]
    0 Warning(s)
    23 Error(s)
````

Note: this is ran from a git worktree

**Comment by alrz** [comment]
perhaps this doesn't belong to roslyn repo. I don't know where this should be filed.

**Comment by alrz** [comment]
After commenting `Microsoft.Build.Tasks.Git.LocateRepository` out, `generated source link is empty` is reported. could we just disable it on local builds?

**Comment by tmat** [comment]
I believe this has been fixed. We need to update to the new version of SourceLink.

**Comment by qlikTERror** [comment]
This is still a problem with Microsoft.SourceLink.GitHub 1.1.1 and Microsoft.Build.Tasks.Git 1.1.1 and using worktrees
