### ISSUE TITLE
Report Diagnostics in Partial Classes

### ISSUE THREAD

**Issue by johnkoerner** [dotnet/roslyn#3748]
I am seeing an issue when reporting diagnostics on partial classes.  I posted on [stackoverflow](http://stackoverflow.com/q/30856482/573218), but got no answers. I did get verification that others are seeing it and it was suggested that I post an issue here.

I am modifying the default analyzer project that comes from the code analyzer template to try and get it to report at all of the declarations for a partial class.

I have modified the code to:

    public override void Initialize(AnalysisContext context)
    {
        context.RegisterSymbolAction(AnalyzeSymbol, SymbolKind.NamedType);
    }

    private static void AnalyzeSymbol(SymbolAnalysisContext context)
	{
	    var namedTypeSymbol = (INamedTypeSymbol)context.Symbol;
	
	    // Find just those named type symbols with names containing lowercase letters.
	    if (namedTypeSymbol.Name.ToCharArray().Any(char.IsLower))
	    {
	        foreach (var location in namedTypeSymbol.Locations)
	        {
	            // For all such symbols, produce a diagnostic.
	            var diagnostic = Diagnostic.Create(Rule, location, namedTypeSymbol.Name);
	            context.ReportDiagnostic(diagnostic);
	        }
	    }
	}
In two separate files, I have partial classes like this:

    // File1.cs
	partial class Foo
	{
	    public string BarString;
	}

	// File2.cs
	partial class Foo
	{
	    public string FooBarString;
	}

I put breakpoints on the ReportDiagnostic and am seeing it called for each location, but within Visual Studio it only reports diagnostics within a single file.

If I put multiple implementations of Foo in a single file (and it happens to be reporting on that files declaration) then I will see both diagnostics reported.

Am I misunderstanding how diagnostics are supposed to be reported or is this a bug? If it is a bug, is it a Roslyn problem or is it a problem with Visual Studio's consumption of Roslyn?

**Comment by mavasani** [comment]
@johnkoerner thanks for reporting the issue.

/cc @heejaechang @JohnHamby for reference.

This is a known issue in the v1 implementation of the Visual Studio IDE's diagnostic service. It currently doesn't handle analyzer reporting diagnostics outside the document being analyzed. So, if `File1.cs` has the primary definition of `Foo` for which `AnalyzeSymbol` was invoked, then the diagnostic service only retains diagnostics reported by the analyzer within this file.

We are working on a v2 implementation of the IDE driver, and we should address this issue as part of that work. I'll keep this issue with myself to track this work.

However, that work will not make into the current release of VS. As a workaround, I would recommend that you define your analyzer to report these diagnostics in a CompilationEndAction, and the IDE should correctly report all your partial definition diagnostics. 

You should define a RegisterCompilationStartAction with a nested RegisterSymbolAction callback that just adds to a set of symbols or locations on which you intend to report these diagnostics, and a nested RegisterCompilationEndAction that walks all these symbols/locations and reports the diagnostics. See [here](https://github.com/dotnet/roslyn/blob/master/src/Samples/CSharp/Analyzers/CSharpAnalyzers/CSharpAnalyzers/StatefulAnalyzers/CompilationStartedAnalyzerWithCompilationWideAnalysis.cs#L48) for an example of how to structure your actions for such a stateful compilation analyzer.

**Comment by mavasani** [comment]
This should be addressed by https://github.com/dotnet/roslyn/pull/4081
I'll add a regression test to confirm once that PR is merged in.

**Comment by mavasani** [comment]
Regression test added with https://github.com/dotnet/roslyn/commit/61450e9fbf7b97ff575995f7304eac5d8b8d3437

**Comment by dbolkensteyn** [comment]
@mavasani I'm on VS2015 Update 1, and I am still encountering this issue. I don't see any issue being created on a partial class defined in 2 separate files, however it does work for non-partial classes:
```
public override void Initialize(AnalysisContext context)
{
    context.RegisterSymbolAction(
        c =>
        {
            var symbol = (INamedTypeSymbol)c.Symbol;
            if (symbol.TypeKind != TypeKind.Class)
            {
                return;
            }

            foreach (var location in symbol.Locations)
            {
               c.ReportDiagnostic(Diagnostic.Create(Rule, location, counter.ToString()));
            }
        },
        SymbolKind.NamedType);
}
```

**Comment by srivatsn** [comment]
I'm seeing the same behavior described by @dbolkensteyn. Reopening this issue,

**Comment by mavasani** [comment]
I was able to repro this - it seemed to have regressed with Update1. The regression test added for this bug (https://github.com/dotnet/roslyn/issues/3748?_pjax=%23js-repo-pjax-container#issuecomment-128052147) didn't catch it as it is run with a single analyzer and the bug repros only when there are multiple analyzers and the driver processes some other analyzer prior to this one - basically its a race condition. I will add a separate regression test with the fix.

**Comment by weltkante** [comment]
@mavasani Might be worth checking if the fix for this also fixes #8067 or if its a different issue.

**Comment by tvsonar** [comment]
I'm still seeing issues regarding partial classes and symbol based analyzers. When an issue should be reported or not based on some changes that are not changes the symbol itself, then the warnings do not show up.

Here's a repro of the problem:
```C#
context.RegisterSymbolAction(
    c =>
    {
        var declaredSymbol = (INamedTypeSymbol)c.Symbol;
        var syntaxNodes = declaredSymbol.DeclaringSyntaxReferences.Select(r => r.GetSyntax());
        var emptyStatementCounts = syntaxNodes
            .Select(n => new
                {
                    Count = n.DescendantNodes().OfType<EmptyStatementSyntax>().Count(),
                    Node = n
                })
            .ToList();

        var max = emptyStatementCounts.Select(x => x.Count).Max();
        var node = emptyStatementCounts.FirstOrDefault(x => x.Count == max);
        c.ReportDiagnostic(Diagnostic.Create(Rule, node.Node.GetLocation()));
    },
    SymbolKind.NamedType);
```

The above analyzer reports on the partial part of a class containing the most number of empty statements.

**Step 1**
Having the following two input files, an issue is reported on the partial part in File2.
File1:
```
partial class X
{
    public void Bar()
    {
        ;
    }
}
```

File2:
```
partial class X
{
    public void Foo()
    {
        ; ;
    }
}
```

**Step 2**
Changing File1 to the following results in two issues reported (one in File1, the other in File2).
File1:
```
partial class X
{
    public void Bar()
    {
        ;;;;
    }
}
```
*This is wrong, only one warning should be displayed.*

**Step 3**
Finally, modifying File2 by adding a space to it removes the left-over issue (File2) from the Error List.

**Alternative Step 2**
If in step 2, I was modifying File2 to the following, then only a single (correct) issue is reported (, which is in File1).
File1:
```
partial class X
{
    public void Bar()
    {
        ;;;;
    }
    public void Bar2()
    {
    }
}
```

**Comment by mavasani** [comment]
This maybe same issue as mentioned in https://github.com/dotnet/roslyn/issues/8067#issuecomment-216306649. I'll try and repro your scenario on latest bits and add test.

**Comment by mavasani** [comment]
Tagging @heejaechang - @tvsonar has a method body editing scenario, where editing a method body is affecting analyzer diagnostics reported on a separate file. It is a local diagnostic as it is reported within the span of symbol's location.

Heejae, do you think this should be fixed with latest Roslyn bits? I am going to give it a try later today.

**Comment by heejaechang** [comment]
@mavasani the definition of "local" in IDE I used is span that got edited and span (with v2, span is removed, so tree edited and tree diagnostic reported) where diagnostic reported is same. above case, it doesn't looks like they are same. so they are not local diagnostics.

**Comment by mavasani** [comment]
@heejaechang These are local diagnostics as per the classification in analyzer driver - http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerExecutor.cs,1263. So basically, CompilationWithAnalyzers.GetAnalyzerSemanticDiagnostics(tree) will return the diagnostic.

**Comment by heejaechang** [comment]
@mavasani that makes things complicated since a file can contain diagnostics from multiple snapshots.
. by the way, this might just work with v2 engine, but diagnostics on other files will shows up slowly than one on active file.

**Comment by mavasani** [comment]
I verified that this still repros in latest bits - and this is a dupe of https://github.com/dotnet/roslyn/issues/8067, which in turn is due to compiler bug https://github.com/dotnet/roslyn/issues/11015. I am closing this bug and adding a note to https://github.com/dotnet/roslyn/issues/8067 to verify this scenario when closing it.

**Comment by mavasani** [comment]
**Update:** Underlying issue #11015 is now fixed, which caused #8067 to be fixed as well. However, the issue reported by @weltkante in https://github.com/dotnet/roslyn/issues/3748#issuecomment-218400083 is still not fixed - this seems to be due to incorrect analyzer implementation.

The analyzer shown by @weltkante reports a symbol diagnostic (i.e. declaration diagnostic) which depends on the method body content of a method body within a type. A diagnostic reported by symbol action should be a pure declaration diagnostic - it shouldn't differ based on method body contents being altered. If an analyzer wants to report such a diagnostic (i.e. executable code or method body diagnostic) it can do so by taking one of the following approach:

1. If the diagnostic depends only on the contents of the specific executable code block, it can register a syntax node/code block action(s).
2. If the diagnostic depends on contents of multiple executable code blocks, it should register a compilation end action to report such diagnostics. So @weltkante's analyzer should register a compilation start action, with a nested symbol action that has the same code as https://github.com/dotnet/roslyn/issues/3748#issuecomment-218400083, except that it should not report the diagnostic there, but instead just add the syntax node to a list maintained in the compilation scope, and also register a compilation end action that goes through this list of nodes and reports diagnostics on them.

**Comment by mavasani** [comment]
More specifically, below code works fine for @weltkante's repro:

```
            context.RegisterCompilationStartAction(compilationStartContext =>
            {
                var locations = new List<Location>();
                compilationStartContext.RegisterSymbolAction(
                     c =>
                     {
                         var declaredSymbol = (INamedTypeSymbol)c.Symbol;
                         var syntaxNodes = declaredSymbol.DeclaringSyntaxReferences.Select(r => r.GetSyntax());
                         var emptyStatementCounts = syntaxNodes
                             .Select(n => new
                             {
                                 Count = n.DescendantNodes().OfType<EmptyStatementSyntax>().Count(),
                                 Node = n
                             })
                             .ToList();

                         var max = emptyStatementCounts.Select(x => x.Count).Max();
                         var node = emptyStatementCounts.FirstOrDefault(x => x.Count == max)?.Node;
                         if (node != null)
                         {
                             locations.Add(node.GetLocation());
                         }
                     },
                     SymbolKind.NamedType);

                compilationStartContext.RegisterCompilationEndAction(compilationEndContext =>
                {
                    foreach (var location in locations)
                    {
                        compilationEndContext.ReportDiagnostic(Diagnostic.Create(Rule, location));
                    }
                });
            });
```

**Comment by weltkante** [comment]
@mavasani thanks for checking, I assume you meant @tvsonar in your previous two comments. My repros were based on the provided analyzer templates in VS, so if they are broken the templates need to be fixed too.

**Comment by mavasani** [comment]
Oh yes, that is correct, I meant @tvsonar.

**Comment by tvsonar** [comment]
@mavasani Thanks, I'm aware that this analyzer could have been implemented with the use of `RegisterCompilationEndAction`, however we tend to not use that as we found that's (almost) unusable when reporting on a large project. The amount of time between a user edit and the issue showing up is dependent on the project size. We've seen cases where it was above 2 minutes on decent developer machines.

When analyzing partial classes, the symbol analyzer seemed the only alternative. The restriction you mention on symbol analyzer makes the API a bit inconsistent to me: why is a compilation action triggered on whitespace inserts and why a symbol based one not? If this choice is by design, then I think this should be clearly documented.

**Comment by mavasani** [comment]
@tvsonar IDE live analysis tries to optimize analysis performance by avoiding re-running analyzers on non-active open files when you have method body edits in the active file. @heejaechang - is it reasonable to drop and re-compute open file diagnostics for method body edits?
