### ISSUE TITLE
Error with Large HTML

### ISSUE THREAD

**Issue by rogeriorlima3** [dotnet/roslyn#37572]
**Version Used**: 
VS2019 COMMUNITY

**Steps to Reproduce**:
1. FIRST CREATE A VB WEB PROJECT WEB FORMS
2. CREATE PAGE1.ASPX
3. WRITE A LARGE HTML IN IT
4. TRY TO RUN THE PROJECT

**Expected Behavior**:
SEE HTML NORMALLY

**Actual Behavior**:
ERROR THAT APPEAR:
https://github.com/rogeriorlima3/errorVS2019/issues/1

**Comment by gafter** [comment]
This is the same issue as #7398, but in VB.

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/37915

**Comment by rogeriorlima3** [comment]
> 
> 
> Fixed in #37915

Guys,

It was not fixed... We are facing the same error.

We just bought metronic template. 
index.html open normally
but when we put it (index.html content) in test1.aspx, it does not open.
