### ISSUE TITLE
C# auto-formatter ignores the "Keep tabs" setting around syntax errors

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#4014]
Try pasting the following snippet with tabs (assuming GitHub doesn't destroy the formatting) into VS2015 RTM:

```
class Program
{
	static void Main()
	{
		return // Note the missing semicolon
	} // The tab here will be turned into four spaces
}
```

The same thing happens while typing. Something about my coding style (too many typos?) triggers this frequently and it's insanely annoying!

**Comment by lorcanmooney** [comment]
And of course GitHub replaced all the tabs in my sample with spaces. Pasting the snippet as above produces the same end result, but possibly for different reasons.

**Comment by Pilchie** [comment]
This is the same issue tracked by https://connect.microsoft.com/VisualStudio/feedback/details/950651/incorrect-changed-formatting-of-spaces-tabs-for-the-next-code-row-after-pasting-coding.

**Comment by dg9ngf** [comment]
It also affects XAML code even with correct code. All pasted XAML code is reformatted with spaces even if it had tabs and tabs are configured for XAML. "Fix mixed tabs" from the Productivity Power Tools is popping up all the time now. Maybe it's a more general problem and some editor property name was changed and not updated everywhere? (I've noticed lots of changed names when comparing settings files of VS 2013 and 2015.)

**Comment by Pilchie** [comment]
The issue with the Xaml editor has nothing to do with this one.  The two codebases are completely different.

**Comment by Dessix** [comment]
This issue appears to occur in many situations involving tabs, to the degree that I'm considering switching to spaces for the time being. The auto-formatter will replace lines that are not even being touched, cascading through close nesting.

**Comment by Pilchie** [comment]
We haven't seen that - if you have a repro, can you share it with us?

**Comment by Dessix** [comment]
I'll be on the lookout for another occurrence. If I recall, it was in nested dictionary or object initializers, when fiddling with the last line in the innermost initializer if that initializer was the last element of the parent (and so on) it would cascade to the parent's last line. If I find a situation where it happens again, I will post it.

**Comment by DanTup** [comment]
A colleague and I are also frequently seeing random lines being changed to spaces in our diffs since switching to VS 2015. It's hard to say for sure (it's pretty intermittent) but it's entirely possible there are syntax errors when the formatting is triggered (we tend to press Ctrl+K+D frequently).

We do both have format-on-save turned on now (Productivity PowerTools) which I thought might've fixed it, but since there are many things where VS doesn't reformat (seems to assume we'd manually formatted to try and line things up, etc.) that might confuse it further.

Here's an example of something I saw in a code review - the code around this line was not modified (though other things in the file where). I believe it was the Format Document action (possibly on save) that fixed the if statement into two lines; but it ended up with spaces.

![unnamed](https://cloud.githubusercontent.com/assets/1078012/9245223/0c77a01e-419a-11e5-9afc-bbf8e2e7900b.png)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/issues/4707

**Comment by lorcanmooney** [comment]
This is still happening in some limited circumstances in the new CTP (14.0.24606.01 Update 1 CTP). For example, I had the following code...
```
struct Foo
{
	private readonly string bar;

	public Foo()
	{
	}
}
```
...and wanted to initialize the field via a constructor parameter, so I copy-and-pasted `readonly string bar` into the constructor parameter list, taking the `readonly` by accident. This caused the tab before the constructor closing brace to turn into spaces.  
I can't find a way to reactivate this issue. Should I open a new bug?

**Comment by CyrusNajmabadi** [comment]
Hey @lorcanmooney.  Good catch.  I've at least updated the code to handle these scenarios.

**Comment by lorcanmooney** [comment]
So, this again. Update 1 RTM. Like the last time an errant paste showed another case where this still happens:
```
class AClass
{
	void AMethod(Object anArgument)
	{
		if (anArgument == null)
		{
			throw new ArgumentNullException(nameof(anArgument));
		}$$

		DoSomething();
	}

	void DoSomething()
	{
	}
}
```
Paste an identifier (and _just_ and identifier) at the $$ marker, and the tab preceding the call to `DoSomething` turns into 3(!) spaces.

**Comment by Pilchie** [comment]
@CyrusNajmabadi can you take another look?

**Comment by CyrusNajmabadi** [comment]
Yup.  I'll look right away.

**Comment by CyrusNajmabadi** [comment]
This is interesting.  If i'm understanding correctly, this is because of how the parser interprets this tree.  Specifically, it thinks you're declaring things as if you had a local variable:

```SomeIdentifier doSomething```

Because of this, it's wanting to change the whitespace to be a single space.  I can make some targetted fixes where by we don't think of "foo bar()" or "foo bar." as a local declaration.  However, the general problem may remain that we think we've parsed things properly, and then try to fix up the formatting accordingly.  

I'll also see if we can make it so that we try to not screw up indentation here regardless.

**Comment by dg9ngf** [comment]
This isn't a complete fix, right? It only patches a number of cases but doesn't generally regard the tab indentation setting. Even with Update 1 I have that tab to spaces replacement a few times a day. While editing code, it occurs that I temporarily have total garbage in a line. Right now I had parts of strings and a method call. When I also paste something in, the following line's tabs are often replaced with the correct number of spaces. Still completely invisible (if whitespace is not shown). "Fix mixed tabs" extension promptly catches that when I save the file (which I do often).

I managed to find out the cause by undoing until the spaces disappear:

    Test($"\"_\"");

Put the cursor directly behind the `_` and insert `{` there. This will change the following line's indenting. The `Test` method may but does not need to exist, it happens either way.

**Comment by CyrusNajmabadi** [comment]
> This isn't a complete fix

The issue is complex and subtle.  We are effectively trying to "do the right thing" even in the presence of parse errors.  Parse errors already means we're making our best effort to just understand the code.  And if our understanding doesn't match your intuition on what your code means, then issues can occur.

We have considered just disabling formatting in the presence of errors.  However, that leads to a rather poor experience in other ways (one of the reasons we moved to enabling formatting in these cases).  

I expect there will continue to be a back and forth as we patch cases and discover more interesting cases where our trees can be extremely wonky, and we want to process your code properly.

In the specific case you brought up, the problem is how messed the tree is when you have an interpolated string literal.  The insertion of the ```{``` causes the parser error recovery to go all screwy, causing us to think your code is totally different.  As such, converting the tab to spaces makes sense to the formatting engine because this is now no longer indentation but rather spacing between other constructs.

**Comment by dg9ngf** [comment]
Hm. Maybe another thing to consider is a line break, followed by tabs. That looks a lot like indentation in general, I wouldn't need a parse tree for that. And I believe that your parse tree has those whitespaces as well.

As for the "poor experience", I consider less help better than more damage.

**Comment by CyrusNajmabadi** [comment]
>  That looks a lot like indentation in general

That's not the issue though.  Even indented code may need to have spacing adjustments to it.  For example, we try to preserve indentation when constructs move.  We call this preservation 'anchoring'.  i.e. say you have normal tab settings (4 spaces to a tab).  And you have some child code indented one tab from the parent.  You then indent the parent by 2 spaces.  In order to keep the child indentation accurate, we need to insert spaces there as well.

So the issue often occurs that you have incorrect code, and we both think we need to adjust things *and* we're trying to preserve anchoring.  This can lead to tabs being converted to spaces.  This is the right behavior in most user code.  But can be incorrect in some cases.  Accurately making that determination is what we're working on.

> As for the "poor experience", I consider less help better than more damage

That's a personal perspective.  We had the less help approach before.  Others complained.  It's a balance that we're continually working on.  

Imagine, for example if in the presence of parse errors, indentation didn't even work at all.  That would be "less help" but would be an awful experience.  Every time you pressed enter, we'd simply take you to column 0.  Clearly that's just not going to cut it.  So we still support features in the presence of errors because not having them makes for a very poor experience.

**Comment by dg9ngf** [comment]
Can I please have an option to _never_ have anything indented with spaces? Even if the parser thinks something is indented between tabs, which I never do and never accept. If I could tell the parser about my strict tab preference, it might be able to spare me with such guesses.

And if following code is reformatted in some situations, it should be updated again later as well. I commonly see this with VS 2015: Paste an `if` statement or something similar, and the next statement is indented by a tab. Even if it was there before and a comment line is in between (that comment is not indented IIRC). When I continue typing `{` and `}`, the next statement is still indented but it should be outdented again to where it was before. These modifications to code I'm not touching is the annoying part of it. Makes me need to edit something I wasn't even looking at.

**Comment by CyrusNajmabadi** [comment]
> which I never do and never accept

It is not clear if this is a widespread position.  It's very common for people to follow the "indent with tabs, align with spaces" philosophy.  i.e.:
http://vim.wikia.com/wiki/Indent_with_tabs,_align_with_spaces
http://dmitryfrank.com/articles/indent_with_tabs_align_with_spaces

This is used all the time to align things on multiple lines.  For example:

```c#
<tab>void Foo(int arg1,
<tab><tab><sp>int arg2)
```

If this method gets indented then it would be really bad (and broken for most people) if the wrapped parameters didn't stay aligned.  

> I commonly see this with VS 2015

Please file bugs for all the cases you run into.  I (and others) will attempt to fix them to the best of our ability. 

> These modifications to code I'm not touching is the annoying part of it. Makes me need to edit something I wasn't even looking at.

It's difficult to know what users are looking at currently :)  
Because of this we make some assumptions about the code in question and what should be affected by what the user is typing.  It is very often the case that users *do* want to update the code that follows/precedes what they are editing.  In those cases if we do not update the code, it is quite likely that the code will then not be appropriate for other users.

Regardless, if you don't want VS autoformatting, then I recommend you disable these options:
![image](https://cloud.githubusercontent.com/assets/4564579/12188086/dd8dbf04-b566-11e5-9ac2-e66b28dbe314.png)

Right now it's a feature that pasting causes reformatting to happen (so that users can paste code and have it be correctly formatted without an extra explicit step).  If  you don't like that behavior then I recommend you disable this feature.

Cheers!

**Comment by dg9ngf** [comment]
> "indent with tabs, align with spaces"

Then I guess I don't align code, only indent. I never use tabs where problems can arise if the tab width is changed.

The issue with "auto-format on `}`" I meant is that the (meanwhile indented) following statement is not outdented again. Look at this code:

    Method();

Now paste the following before the statement and it will get indented:

    if (variable)
        Method();

As I continue to type, it looks like this:

    if (variable)
    {
    }
        Method();

`}` only formats the code it closes, not the code that has been moved around before.

**Comment by CyrusNajmabadi** [comment]
> Then I guess I don't align code, only indent. I never use tabs where problems can arise if the tab width is changed.

Sure.  But others do.  We have to try to make sure our features work properly for those cases as well.

> The issue with "auto-format on  } " I meant is that the (meanwhile indented) following statement is not outdented again.

Yes.  Humorously enough, this now goes against something you were mentioning earlier.  Previously you stated: "These modifications to code I'm not touching is the annoying part of it."

But now we're *not* modifying code you're not touching.  And in this case you *do* want us to modify it.  :)

This is precisely why this area is complex.  Some people want everything to automagically happen (VB being the case where it is super aggressive and happens all the time).  Some people want it to never happen.  And some people want things in the middle.

It sounds like you're more irked by the times when it happens, but when the heuristics for what you are/aren't touching don't exactly match what you want.  If this is the case, I would recommend that you disable the auto-formatting options.  Now we want try to 'guess' as to what we should be fixing up, and you should be in control of when formatting happens.  Now you can just explicitly invoke 'format document' or 'format selection' when you want, and the auto formatting won't interfere with things for you.

**Comment by CyrusNajmabadi** [comment]
> Can I please have an option to never have anything indented with spaces?

@dg9ngf  You can see from the linked PR that it isn't trivial/obvious how to immediately know if something is actually indentation or not.  This is our code that attempts to determine this.  But even we/I got it wrong due to the complexities around working with broken code.  I'm hoping this latest change is able to stop out a large class of these issue (ideally all of them).  However, it may not be complete.  If you run into other cases where you still see indentation tabs converted to spaces, please let us know and i'll work to fix them asap.
