### ISSUE TITLE
Incorrect CodeFixProvider diff colorization

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#4059]
![diff-colors](https://cloud.githubusercontent.com/assets/10324372/8831447/9fd516ec-30a2-11e5-9bc7-44fae33bf152.png)

I believe the red `(` in fix preview popup indicates that the character is about to be removed when applying this fix, which is not the case.

Applies to VS2015 RTM.

**Comment by Pilchie** [comment]
This is happening because we just use the editor's text diffing, and it is grouping all the non-character/non-whitespace characters as a single chunk that is getting replaced.

**Comment by Pilchie** [comment]
I think @heejaechang changed the preview changes window diffing after RTM.  Did we change this preview too?  Using character diffing would help here, right?

**Comment by heejaechang** [comment]
@shyamnamboodiripad probably knows better on this. but looking at the source, we use default stringdifferenceoption. I am not sure what mode is the default. probably line?

**Comment by shyamnamboodiripad** [comment]
I think this is the editor's differ treating "([" as a single punctuation and assuming that the "(" has changed to "([". I am not sure whether the differ has a mode that controls this behavior (perhaps there is and perhaps someone from the editor team would know - Its been a while since I have looked at this code). But note that this is also the default for the regular diff view in VS -

![capture](https://cloud.githubusercontent.com/assets/10579684/8993015/10774a5e-36b7-11e5-817f-45fe027e9d15.PNG)

**Comment by dpoeschl** [comment]
Is this any better with Line Diffing now?

**Comment by bkoelman** [comment]
@dpoeschl Can I view the new behavior somewhere? Is this in Update1 RC?

**Comment by jmarolf** [comment]
![image](https://cloud.githubusercontent.com/assets/9797472/18302090/85d1a526-748a-11e6-992b-b2812e7f495d.png)
Still looks bad on 2.0.0.6090909

**Comment by heejaechang** [comment]
this seems not our bug but something we need to ask editor team to make the differ better?

**Comment by heejaechang** [comment]
"I believe the red ( in fix preview popup indicates that the character is about to be removed when applying this fix, which is not the case."

I am not sure whether I agree with it. what it tells is ( will be changed to ([NotNull] and I dont see any problem on that.

**Comment by Pilchie** [comment]
Tagging @CyrusNajmabadi who was looking at something similar the other day.

**Comment by CyrusNajmabadi** [comment]
Oddly enough, i just reached out to the editor team about this . I'll point them to this thread.

**Comment by Pilchie** [comment]
Is there anything we can do here, or should we close this as external and track it with with the editor team?

**Comment by CyrusNajmabadi** [comment]
David did some work here that should address this.  I think we should try this out when we have a recent VS build and we can close this whne we've verified the fix.

**Comment by CyrusNajmabadi** [comment]
This was fixed with this editor PR: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/56315?_a=overview

**Comment by bkoelman** [comment]
@CyrusNajmabadi The PR link is inaccessible to me. However in VS2017 RTM I'm still seeing the old behavior. Does this PR affect a future release?

**Comment by CyrusNajmabadi** [comment]
Yes.  This PR will come out in 15.3 (i.e. the first VS 2017 update).

**Comment by CyrusNajmabadi** [comment]
I'm reopening until the fix makes it out to customers.

**Comment by CyrusNajmabadi** [comment]
@jmarolf is going to verify and handle as appropriate.

**Comment by jmarolf** [comment]
![image](https://user-images.githubusercontent.com/9797472/27749165-45a9f232-5d87-11e7-96f4-2d7c5645b782.png)
 This is fixed in Visual Studio 15.3 Preview 3

**Comment by bkoelman** [comment]
Nice, thanks a lot!
