### ISSUE TITLE
Code cleanup - Sort accessibility modifiers fixer doesn't work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42575]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/943970/code-cleanup-sort-accessibility-modifiers-fixer-do.html)._

---
I included Sort accessibility modifiers fixer to my code cleanup configuration, but when I run code cleanup on the code that is not sorted properly, nothing happens. I have csharp_preferred_modifier_order setting set in my .editorconfig. Do I need to configure something else to make it work?

---
#### Visual Studio Feedback System on 3/10/2020, 02:47 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Szymod** [comment]
Hey, if you need any other info, let me know. I'm really looking forward for this to work.

**Comment by bjornenalfa** [comment]
It seems like visual studio has some hardcoded modifier order and ignores the .editorconfig setting. For example it will put async before override, regardless of the configuration.

**Comment by Guspaz** [comment]
I'm not sure if it's the order being hardcoded that's the problem, when I ran this cleanup on a solution where the files had stuff in purely random order (private/public/private/public all mixed together), it made zero changes to any files. It simply does nothing.

**Comment by RicardoNiepel** [comment]
Bug is still there - it does not matter if a custom .editorconfig is used or not - the sorting is not happening.

VS 2019 16.11.7

**Comment by sharwell** [comment]
This was fixed by #57883

**Comment by oborsha** [comment]
Why was this issue closed?  As far as I can tell, the functionality still does not work even in latest Visual Studio 2022.  When you run Code Cleanup, the fixer for "Order modifiers" does nothing.
