### ISSUE TITLE
IntelliSense offers members of type in another overload that are unambiguously wrong

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#43201]
**Version Used**: VS 16.5.3 and 16.6.0-p2.1

**Steps to Reproduce**:

```cs
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;

class C
{
    public int PropertyOnC { get; }

    async Task M(IQueryable<C> query)
    {
        _ = await query.MaxAsync(c => c.[||])
    }
}

// From Entity Framework
static class QueryableExtensions
{
    public static Task<TResult> MaxAsync<TSource, TResult>(
        this IQueryable<TSource> source,
        Expression<Func<TSource, TResult>> selector)
    {
        throw new NotImplementedException();
    }
    public static Task<TResult> MaxAsync<TSource, TResult>(
        this IQueryable<TSource> source,
        CancellationToken cancellationToken)
    {
        throw new NotImplementedException();
    }
}
```

**Expected Behavior**:

IntelliSense offers only members that can dot off `C`

**Actual Behavior**:

IntelliSense offers members of both `C` and `CancellationToken`, even though the lambda syntax guarantees that there is no ambiguity about the fact that `CancellationToken` members are not what anyone would want to see.

![image](https://user-images.githubusercontent.com/8040367/78822339-ea43cd00-79a8-11ea-8489-78aa0afd05f6.png)

**Comment by CyrusNajmabadi** [comment]
@dpoeschl did you just fix this?

**Comment by dpoeschl** [comment]
Yes, I believe this should be fixed by https://github.com/dotnet/roslyn/pull/42942 but can't double-check currently. Will do so tomorrow.

**Comment by dpoeschl** [comment]
Thanks for the awesome standalone repro @jnm2!

This was indeed fixed by #42942, and the fix will be in the next preview of Visual Studio 2019 Update 6.

![image](https://user-images.githubusercontent.com/235241/78919342-a4d5dd00-7a46-11ea-8ea6-3f83e4cc5c2e.png)

**Comment by tdaniely** [comment]
Still getting this in preview 5.
At least I think it's the same issue.
The variable type is correct, the member list is of another type.

![image](https://user-images.githubusercontent.com/7197386/80959255-1834f980-8e0f-11ea-8936-d57630a4cdb7.png)

**Comment by jnm2** [comment]
The milestone on this issue is incorrect.

> and the fix will be in the next preview of Visual Studio 2019 Update 6.

**Comment by dpoeschl** [comment]
@tdaniely Sorry if I've missed it somewhere else, but can you post more context for your repro so we can give it a try? Does the list contain things from the correct type AND the incorrect type, or only the incorrect type?

Thanks!

**Comment by tdaniely** [comment]
Yes, I just didn't see it because of all of the extensions on IServiceCollection.
I've reduced it to a simpler example.

![image](https://user-images.githubusercontent.com/7197386/81016048-688c7580-8e68-11ea-9ab8-8a34ecbfdca5.png)

This is on preview 5.
![image](https://user-images.githubusercontent.com/7197386/81016789-ca011400-8e69-11ea-9c75-3d5d91e4d5fa.png)

**Comment by CyrusNajmabadi** [comment]
That's a differnet issue @tdaniely .  Could you open a new bug on it?  Thanks!

**Comment by tdaniely** [comment]
Ok, it was linked to this though which is exactly what I'm describing.
https://developercommunity.visualstudio.com/content/problem/893896/intellisense-works-incorrect-with-overloaded-metho.html?inRegister=true

And you posted this as fixing that, That's why I'm posting here.

**Comment by CyrusNajmabadi** [comment]
They're basically different scenarios.   The original one relates to overloads taking a Delegate vs non-Delegate arg, and having a lambda unambiguously use the Delegate version.

The case you're talking about is one where tehre are mulitple Delegate overloads, and you want the overload to be chosen based on parameter count of the lambda.

**Comment by tdaniely** [comment]
https://github.com/dotnet/roslyn/issues/43966
