### ISSUE TITLE
GoToImplementation Doesn't Work On Async Interface Instance When Interface/Class Implementation Are In A Separate Project To The Interface Instance

### ISSUE THREAD

**Issue by JoshuaKlaser** [dotnet/roslyn#45303]
This is an update from this [issue](https://github.com/dotnet/roslyn/issues/45290) as it was closed before I could update it with updates steps to reproduce.

**Version Used**: 
Microsoft Visual Studio Community 2019
Version 16.4.5

**Steps to Reproduce**:

1. Create a Class Library (.NET Standard 2.1)
2. Add in an interface with a method that returns a Task and class where the class inherits
```
**IInterfaceExample.cs**
public interface IInterfaceExample
    {
        Task<int> MethodThatIsAsync();
    }

**ClassExample.cs**
public class ClassExample : IInterfaceExample
    {
        public async Task<int> MethodThatIsAsync()
        {
            await Task.Run(() => { });

            return 0;
        }
    }
```
3. Create a Console Application (.NET Core 3.0)
4. Declare a type of IInterfaceExample and set an instance of ClassExample into it.
```
**AnotherClassInConsoleApp.cs**
public class AnotherClassInConsoleApp
    {
        public AnotherClassInConsoleApp()
        {
            
        }

        private async void SomeFunction()
        {
            IInterfaceExample interfaceInstance = new ClassExample();
            await interfaceInstance.MethodThatIsAsync();
        }
    }
```
5. Have the cursor on MethodThatIsAsync and run GoToImplementation.

**Expected Behavior**:
This should open up the class ClassExample in the Class Library and have the cursor on the function.

**Actual Behavior**:
A window appears saying "The symbol has no implementations.". See gif below.
![VS_GoToImplementation_Proof](https://user-images.githubusercontent.com/7035048/85078259-665b5c00-b207-11ea-84d5-3b3e28ceeb7e.gif)

**Comment by CyrusNajmabadi** [comment]
So i can't repro this on any current version of VS.  Perhaps an issue with your version?  Can you check 16.6 to see if you still see this?

**Comment by CyrusNajmabadi** [comment]
Ah, this is a cross runtime example.  Yes, this has been fixed with https://github.com/dotnet/roslyn/pull/43479.  Thanks!

**Comment by JoshuaKlaser** [comment]
I'll update later on in the day and will update if it worked or not.

**Comment by JoshuaKlaser** [comment]
@CyrusNajmabadi  I have updated to version Microsoft Visual Studio Community 2019 Version 16.6.2 and the issue still occurs.

**Comment by CyrusNajmabadi** [comment]
We introduced support for this in 16.7:

![image](https://user-images.githubusercontent.com/4564579/85093028-f2d23400-b19f-11ea-998e-99bc11569d7e.png)

**Comment by JoshuaKlaser** [comment]
Thanks Cyrus. Will wait for version 16.7 to be released.
