### ISSUE TITLE
C# auto-formats property getter on new line instead of leaving it on a single line

### ISSUE THREAD

**Issue by conniey** [dotnet/roslyn#4720]
__Steps to Reproduce__
1.  Type the following:
```csharp
		public Int32 PaymentMethodID
		{
			[System.Diagnostics.DebuggerStepThrough]
			get { return 10; }
		}
```
2. Press Ctrl + K, D

__Expected__
It remains the same.
__Actual__
There is a new line added after get and the open brace { which did not happen in VS 2013.
```csharp
		public Int32 PaymentMethodID
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{ return 10; }
		}
```

**Comment by conniey** [comment]
Sorry, I created an issue for the wrong bug... This is a duplicate of:  https://github.com/dotnet/roslyn/issues/2837

**Comment by oatkins** [comment]
Please also consider this similar case. The following is the result from Format Document:

    public int SomeProperty { get;[SomeAttribute] private set; }

Any space between the semi-colon that terminates the get and the "[" that begins the attribute is removed. Before running Format Document (Ctrl-E, D), the above was 

    public int SomeProperty { get; [SomeAttribute] private set; }

(I originally reported this through the Send a Frown tool, and later received an e-mail, "Visual Studio Feedback[357850]‏", directing me to this post. I don't think my case is exactly the same as this issue, but perhaps they can be handled together.)

**Comment by Pilchie** [comment]
Thanks - I'll take a look at this at the same time.

**Comment by diryboy** [comment]
How about also this? http://stackoverflow.com/questions/30520764/did-c-sharp-formatting-change-in-visual-studio-2015-and-how-can-i-change-it-bac

Auto format results
```C#
public int Whatever
{ get; set; }
```
when "Leave block on single line" is checked and "Leave statements and member declarations on the same line" is unchecked,

**Comment by Pilchie** [comment]
@diryboy: I think I fixed that with #5719.

**Comment by diryboy** [comment]
@Pilchie Great, thanks.

**Comment by Pilchie** [comment]
Re-opening to track merging to stabilization

**Comment by Pilchie** [comment]
Closing as fixed by #6244

**Comment by ZigMeowNyan** [comment]
Thank you for working on this. I am *extremely* excited to see this make its way into VS 2015. I never thought multi-line auto-properties would irritate me so much. I would have gone back to VS 2013 because of how much time I waste dealing with this behavior on auto-implemented properties, but I unfortunately already started using some of the new C# 6 features and don't want the extra commit churn.

I guess I'll try doing some snippet-ish workaround while waiting for this to filter out into updates. Thanks again!

**Comment by Wizard2007** [comment]
in vs 2017 version 15.7.4 it's case still not work. How I can fix it?

**Comment by CyrusNajmabadi** [comment]
hi @Wizard2007 I don't repro any problem in:

![image](https://user-images.githubusercontent.com/4564579/41793942-a19bc90e-7612-11e8-96c1-3f106aef0492.png)

Can you provide a repro case where you still see this?

**Comment by staraneelpatra** [comment]
GOTO:
Preferences->Text Editor->Code Snippets.
Select for c# -> select ...prop and click on Edit 
change the prop snippet to       "public $type$ $name$ {get;set;}" (without double ")
