### ISSUE TITLE
CodeLens doesn't work on records

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#47445]
**Version Used**: 

Visual Studio 16.8.0 Preview 2.1
.NET SDK 5.0.100-preview.8.20417.9
Compiler version: '3.8.0-2.20418.7 (0276b9b7)'. Language version: 9.0.

**Steps to Reproduce**:

Enter the following code:

```csharp
public class Person
{
    public string Name { get; init; }
}

public record PersonRecord
{
    public string Name { get; init; }
}

public static class Factory
{
    public static Person MakePerson(string name)
        => new() { Name = name };

    public static PersonRecord MakeRecord(string name)
        => new() { Name = name };
}
```

**Expected Behavior**:

Code Lens shows number of references above `PersonRecord` and `PersonRecord.Name`.

**Actual Behavior**:

Code Lens is missing for record type and its members:

![image](https://user-images.githubusercontent.com/278957/92181540-186df180-ee0f-11ea-9a2f-f8d18db11b40.png)

**Comment by CyrusNajmabadi** [comment]
@jcouv  Not critical.  @jinujoseph who owns codelens now?

**Comment by sharwell** [comment]
There are two components to CodeLens: a tagger implemented in devdiv (internal) code, and a references provider implemented here in dotnet/roslyn. Both will need to be updated to report tags and information for the new syntax.

**Comment by huoyaoyuan** [comment]
What do you plan for codelens on properties that's only declared in primary constructor? Are they not being able to work with?

**Comment by CyrusNajmabadi** [comment]
VS PR for this here: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/279270

**Comment by sharwell** [comment]
🔗 Also reported as AB#1245289

**Comment by thomaslevesque** [comment]
In fact, there are a number of things that don't work for records.
- CodeLens (this issue)
- Go to all / Go to type (see [this feedback item](https://developercommunity2.visualstudio.com/t/Go-to-all-and-Go-to-types-dont-work/1252528))
- In the solution explorer, when you expand a C# file containing a record type, it appears as a method
- Refactorings don't work (e.g. move to namespace (#48315))

**Comment by CyrusNajmabadi** [comment]
@thomaslevesque what version of vs are you using?

**Comment by thomaslevesque** [comment]
16.8.1

**Comment by thomaslevesque** [comment]
> In the solution explorer, when you expand a C# file containing a record type, it appears as a method

Sorry, actually I saw that in the screenshot in the [feedback item](https://developercommunity2.visualstudio.com/t/Go-to-all-and-Go-to-types-dont-work/1252528) I mentioned. I'm not seeing this on my machine, instead I can't expand the file in the solution explorer if the record is the only type in the file; if there are multiple types, I see the other types, but not the record.

**Comment by CyrusNajmabadi** [comment]
Go-to-all:

![image](https://user-images.githubusercontent.com/4564579/99687777-e6495480-2a39-11eb-9c04-47f1377293d0.png)

(it's a record)

Solution explorer:

![image](https://user-images.githubusercontent.com/4564579/99687847-f8c38e00-2a39-11eb-8fdf-3758c844629e.png)

Looks like a class.

Change namespace:

![image](https://user-images.githubusercontent.com/4564579/99687900-0711aa00-2a3a-11eb-8eb4-dba000dbc6a3.png)

Move to namespace:

![image](https://user-images.githubusercontent.com/4564579/99687996-24df0f00-2a3a-11eb-8d18-ee278c9d31eb.png)

**Comment by thomaslevesque** [comment]
Wow... are you on 16.8.1 too? I'm seeing this bug on 2 different machines with a fresh VS install.
I just tried again in a different project, and I still have the same issue. As soon as I change the record to a class, the issue disappears.

**Comment by CyrusNajmabadi** [comment]
No, i'm on 16.9preview2 :)

**Comment by thomaslevesque** [comment]
Ah. Well, at least it's fixed in the next version... Any chance of getting the fix before 16.9 RTM?

**Comment by CyrusNajmabadi** [comment]
There is no chance of that happening.

**Comment by silkfire** [comment]
@CyrusNajmabadi Is the missing CodeLens reference bug (this issue) fixed in 16.9 too?

**Comment by PathogenDavid** [comment]
@silkfire I can confirm that it is not. (At least not in 16.9 preview 2.)

**Comment by magnusbakken** [comment]
Yeah, I just installed 16.9, and the CodeLens data is still missing for records.

**Comment by behzad888** [comment]
I just installed 16.9.1, and the CodeLens data is still missing for records too.

**Comment by bencgreen** [comment]
Anyone know if this is even being worked on at MS? It seems possibly only a minor thing, but actually for stuff like code coverage in tests codelens is invaluable to see at a glance what needs looking at.

**Comment by CyrusNajmabadi** [comment]
This currently is not assigned to anyone.  We'd need to move it out of our backlog and into a particular release to make this happen.

**Comment by CyrusNajmabadi** [comment]
I'll see if i can make some time in the weekend to get this working.

**Comment by CyrusNajmabadi** [comment]
This has been fixed and is in the latest vs (internal) previews:

![image](https://user-images.githubusercontent.com/4564579/113742213-3c502900-96b7-11eb-8791-05c5d29693bc.png)


Fixed with: https://devdiv.visualstudio.com/DevDiv/_git/a290117c-5a8a-40f7-bc2c-f14dbe3acf6d/pullrequest/279270

Should be in 16.10
