### ISSUE TITLE
Changing class to record crashes VS

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#48784]
**Version Used**: 

Version 16.9.0 Preview 2.0 [30618.5.main]
Microsoft.Net.Compilers.Toolset 3.8.0-4.final

**Steps to Reproduce**:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="3.8.0-4.final" />
  </ItemGroup>
  
</Project>
```

```c#
using System;

interface I
{
    event Action E;
}

class Foo : I
{
    public event Action E;
}
```

Change `class` to `record`. VS will crash once you finish typing.

This doesn't repro if the interface list is empty, the interface has no members, or if the interface has a simple property. It seems related to the event.

**Expected Behavior**:

No crash.

**Actual Behavior**:

Boom.

**Comment by jaredpar** [comment]
@jcouv fyi

**Comment by jcouv** [comment]
This was fixed in https://github.com/dotnet/roslyn/pull/47734

**Comment by jaryn-kubik** [comment]
In what version is it supposed to be fixed?
This still crashes in the newly released VS 16.8.0 and 16.9-preview1.

**Comment by jcouv** [comment]
Re-opened to retest on released version of 16.8 (since it includes change https://github.com/dotnet/roslyn/pull/47734)

**Comment by jcouv** [comment]
Verified this was fixed. Going ahead and closing the issue.
