### ISSUE TITLE
FAR doesn't cascade from virtual method to overrides

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#4936]
If you start a find-all-references by pointing at a base class virtual method declaration or a call to it, you only find the base declaration of the method with the references, but none of the overridden declarations in derived classes.

Repro.
1. Try FAR on Workspace.ApplyDocumentTextChanged in Workspace.cs
This should produce a list of one declaration and 3 references (all from the same source file)
2. Try FAR from MSBuildWorkspace.ApplyDocumentTextChanged in MSBuildWorkspace.cs
This will produce a list with many overridden declarations (msbuild, vs workspace, etc).

**Comment by balajikris** [comment]
ah-ha. This seems to work in general. This specific case does not work because Workspace is defined in a portable project and MSBuildWorkspace is defined in another project that has a reference to the portable project.

* If Workspace and MSBuildWorkspace were defined in the same project, cascading to overrides works
* If Workspace and MSBuildWorkspace are defined in separate projects and are connected by a p2p reference and if neither are portable, cascading to overrides still works.
* If workspace is defined in a portable project (Win8, Net45) and MSBuildWorkspace is defined in a regular project with a p2p ref to the portable project, cascading to overrides fails.

**Comment by balajikris** [comment]
the [equivalence check in FindOverrides](https://github.com/dotnet/roslyn/blob/0382e3e3fc543fc483090bff3ab1eaae39dfb4d9/src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Hierarchy.cs#L45) fails because the symbols are from different assemblies since one of them is portable.

**Comment by Pilchie** [comment]
I suspect this is NOT a regression from RTM, but it's still pretty painful.

**Comment by balajikris** [comment]
Need to see if this still reproes.

**Comment by DustinCampbell** [comment]
@balajikris, any update here?

**Comment by Pilchie** [comment]
Is this the same issue that @brettfo addressed in #4973?

**Comment by Pilchie** [comment]
@brettfo Can you confirm that this is the same?  If so, should we add some FAR specific tests here too?

**Comment by brettfo** [comment]
My fix for #4973 doesn't fix this issue, but it is most definitely related since the root cause of both failures is a type from a desktop assembly inheriting from a type in a portable one.  Given my context on the other issue I'll look at this now since I expect it to be a simple fix.

**Comment by balajikris** [comment]
Thanks @brettfo .. Just saw your change and was about to ask you to see if you can take it, thanks again.

**Comment by Pilchie** [comment]
Can you double check that this is fixed and close?

**Comment by Pilchie** [comment]
Ping again?

**Comment by brettfo** [comment]
This was fixed in #9363 and has since been merged into `master`, `future`, and `stabilization`.  Not sure why it's still open, but closing it now.
