### ISSUE TITLE
Intellisense is incorrectly invoked while typing comments for method parameters

### ISSUE THREAD

**Issue by conniey** [dotnet/roslyn#4999]
__Steps to Reproduce__
1. Copy the code below
2. Start typing a comment after `"one"` and include a comma. (ie. `"one", //here, it will happen`)
```csharp
    class Program
    {
        static void Main(string[] args)
        {
            Method1(
                "one",
                "two");
        }

        static void Method1(string argument1, string argument2)
        {
        }
    }
```

__Expected__
Nothing happens
__Actual__
![image](https://cloud.githubusercontent.com/assets/10136526/9674346/b6a8cee8-5264-11e5-8780-86924040d58f.png)

**Comment by dpoeschl** [comment]
@conniey - Is this just when you type the comma? I can't repro it in that case. I can get the signature help to show up if I invoke ```Edit.ParameterInfo``` (Ctrl+Shift+Space for me), but not just by typing the comment with a comma. Am I missing something? 

Also, is this plain VS2015, or is this a more recent build?

**Comment by conniey** [comment]
@dpoeschl: Here's my version information.  What build are you using to reproduce this?
Microsoft Visual Studio Enterprise 2015
Version 14.0.23107.0 D14REL
Installed Version: Enterprise

**Comment by dpoeschl** [comment]
Thanks @conniey! Yes, it **does** repro for me on VS 2015 RTM, but it does not repro for me on the current **master** branch bits. @rchande might be able to point us to the commit where this was fixed (it looks very similar to https://github.com/dotnet/roslyn/pull/3519, but not quite the same scenario).

**Comment by Pilchie** [comment]
@brettfo didn't you already fix this since 1.0?

**Comment by brettfo** [comment]
I didn't fix anything around signature help in comments and the only PRs that I can find related to this are @rchande's previously mentioned one.

I, too, was able to repro this on VS2015 RTM but not on current sources.  I'm going to mark this as closed for now unless/until we can find when/where it was fixed.
