### ISSUE TITLE
"CSharp.UseAutoProperty.UseAutoPropertyAnalyer" exceptions

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#5291]
These appeared in my error list so I don't have a dump:
```C#
Severity	Code	Description	Project	File	Line	Detail Description
Message	AD0001	Analyzer 'Microsoft.CodeAnalysis.Editor.CSharp.UseAutoProperty.UseAutoPropertyAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	CodeAnalysis		1	Analyzer 'Microsoft.CodeAnalysis.Editor.CSharp.UseAutoProperty.UseAutoPropertyAnalyzer' threw the following exception:
'System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Editor.CSharp.UseAutoProperty.UseAutoPropertyAnalyzer.GetGetterExpression(IMethodSymbol getMethod, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.UseAutoProperty.AbstractUseAutoPropertyAnalyzer`4.AnalyzeProperty(ConcurrentBag`1 analysisResults, SymbolAnalysisContext symbolContext)
   at Microsoft.CodeAnalysis.UseAutoProperty.AbstractUseAutoPropertyAnalyzer`4.<>c__DisplayClass13_0.<Initialize>b__1(SymbolAnalysisContext sac)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass33_0.<ExecuteSymbolActionsCore>b__0()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.
```
```C3
Severity	Code	Description	Project	File	Line	Detail Description
Message	AD0001	Analyzer 'Microsoft.CodeAnalysis.Editor.CSharp.UseAutoProperty.UseAutoPropertyAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Sequence contains more than one element'.	CodeAnalysis		1	Analyzer 'Microsoft.CodeAnalysis.Editor.CSharp.UseAutoProperty.UseAutoPropertyAnalyzer' threw the following exception:
'System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.Editor.CSharp.UseAutoProperty.UseAutoPropertyAnalyzer.GetGetterExpression(IMethodSymbol getMethod, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.UseAutoProperty.AbstractUseAutoPropertyAnalyzer`4.AnalyzeProperty(ConcurrentBag`1 analysisResults, SymbolAnalysisContext symbolContext)
   at Microsoft.CodeAnalysis.UseAutoProperty.AbstractUseAutoPropertyAnalyzer`4.<>c__DisplayClass13_0.<Initialize>b__1(SymbolAnalysisContext sac)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass33_0.<ExecuteSymbolActionsCore>b__0()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.
```

**Comment by rchande** [comment]
I have ~3700 of these in my error list for Roslyn.sln.

**Comment by balajikris** [comment]
The first stack, NRE at GetGetterExpression looks like what @brettfo fixed a couple days ago.

**Comment by brettfo** [comment]
Yes, this has been fixed. I removed the call to `SingleOrDefault()` in PR #5218.

**Comment by rchande** [comment]
I installed today's build and I'm still getting this. Reactivating.
