### ISSUE TITLE
New EditorConfig UI Editor doesn't work for external EditorConfig files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53845]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/New-EditorConfig-UI-Editor-doesnt-work-/1438127)._

---
[severity:Other]
After upgrading Visual Studio 2019 to 16.10.0, I tried to use the new . EditorConfig UI editor support and was unable to get it to work initially. After some testing it seems there are 3 use-cases with different results.

1. [Normal] Open a .editorconfig file that is inside your currently open solution
a. [Result] The file opens with the new editor config UI and populates correctly
2. [Single File] Open a .editorconfig with Visual Studio from file explorer (No solution associated / open in VS)
a. [Result] The file opens in Visual Studio using a default text editor
b. [Expectation] The file opens in Visual Studio using the new editor config UI
3. [Drag File] Open any solution in Visual Studio and then drag an external (not in the solution) .editorconfig file into Visual Studio to edit it
a. [Result] The file opens using the new editor config UI however it fails to populate and just shows an empty editor
b. [Expectation] The file opens in Visual Studio using the new editor config UI and populates correctly
c. [Expectation 2] (If Expectation 1 is not possible for some reason) The file opens in Visual Studio using the default text editor 

In our current setup we do not have any .editorconfig files directly included or specifically made for a single specific solution. Instead we have a single .editorconfig file placed in a folder above all of our projects and solutions and rely on the built in functionality for .editorconfig files where it will walk up the directory structure to find them. We do this in order to only need to maintain a single .editorconfig file for all of our projects and to help automatically enforce the .editorconfig for anyone who forgets to include one into their new project or solution.

---
#### Feedback Bot on 6/1/2021, 07:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/2/2021, 09:41 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
Related to https://github.com/dotnet/roslyn/issues/53081

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/roslyn/pull/56128

**Comment by RPCodeProjects** [comment]
This issue is back in VS2022 17.1.4 update.  Creates an empty editorconfig file

**Comment by Ksdmg** [comment]
Yep indeed, I can confirm that this issue is back. I'm using 17.1.5

**Comment by dspringer59** [comment]
The issue still exists in VS 2022 17.2.3.

**Comment by Piedone** [comment]
Reopened: https://github.com/dotnet/roslyn/issues/70326
