### ISSUE TITLE
Error parsing nullable arrays in switch patterns

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#55013]
Consider the following code 

```cs
#nullable enable
using System;
public class C {
    public object field;
    public void M() {
    }
    
    string Prop => field switch
    {
        string?[] arr => "a"
    };
}
```

This parses in 3.10 but fails in 4.0. Likely this is a regression introduced when we changed lambda parsing. 

DevDiv tracking issue: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1359655/

**Comment by cston** [comment]
FIxed in https://github.com/dotnet/roslyn/pull/55044.

**Comment by kevinchalet** [comment]
👋🏻 

Do we know whether the fix shipped as part of the .NET 6.0 preview7 tooling? I'm still seeing this error so I'm tempted to say "no", but just in case... 😄

**Comment by cston** [comment]
@kevinchalet, it looks like commit https://github.com/dotnet/roslyn/commit/ebbae5b9099aa1ede5d99beb2923655e7b64c729 was not merged in time to be included in .NET 6.0 preview 7. The fix should be included the next preview.

**Comment by kevinchalet** [comment]
Excellent, thanks @cston!
