### ISSUE TITLE
[Flaky test] GoToImplementationOpensProvisionalTabIfDocumentNotOpen

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#60071]
Example build: https://dev.azure.com/dnceng/public/_build/results?buildId=1650954
Example message:
> Assert.Equal() Failure ↓ (pos 0) Expected: FileImplementation.cs Actual: 'IBar' implementations - Entire solution ↑ (pos 0)

> Actual and expected values differ. Expected shown in baseline of diff: -<unknown>: class Implementation : IBar +<unknown>: The symbol has no implementations. Expected: True Actual: False

> System.MissingMethodException : Method not found: 'Microsoft.VisualStudio.Threading.JoinableTaskContext Microsoft.VisualStudio.Shell.ThreadHelper.get_JoinableTaskContext()'.

**Comment by sharwell** [comment]
This was likely fixed by #59956

**Comment by sharwell** [comment]
@allisonchou can you filter out all failures that occurred prior to #59956 merging, or somehow track builds that fail after the fix?

**Comment by allisonchou** [comment]
@sharwell Oops, didn't see your comment until now. It looks like we're still hitting failures as of this month, so it looks like there's still an issue here.

**Comment by sharwell** [comment]
@allisonchou The recent failures are completely unrelated to the test (the VSIX didn't install, so the test didn't even start). I previously filed https://github.com/microsoft/vs-extension-testing/issues/124 to address the underlying difficulty of triaging this type of failure.

**Comment by allisonchou** [comment]
Gotcha, thanks for taking a look. Will close this particular issue then since it seems to be resolved.
