### ISSUE TITLE
[Blocked] dci-win-rbld-12 has run out of disk space

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6099]
We're running our of disk space due to NuGet issue: https://github.com/NuGet/Home/issues/1608. We should isolate %TEMP% on a per job basis and blow it away on cleanup.

@mmitche said:
> Hm, I kind of like this idea.  It is possible to set environment variables on a per job basis.  We can alter the job to set TEMP to ${WORKSPACE}\TEMP or whatnot. Tanner you could prototype this through job dsl pretty easily.  That means that we can isolate TEMP on a per job basis and it will get auto-cleaned as workspaces are cleaned.

**Comment by mmitche** [comment]
@davkean Thanks for the heads up.  We'll find out what's going on with that machine.  The TEMP folder is filled with 50 gigs of RoslynTestFailureDump

**Comment by amcasey** [comment]
We believe this was the source of the temp files: https://github.com/NuGet/Home/issues/1608

**Comment by amcasey** [comment]
We may still wish to mitigate by cleaning our temp folder, possibly by putting it next to our binaries, as @Pilchie suggested.

**Comment by paul1956** [comment]
This is not the only place a Roslyn build fails due to having 65535 temp files. If I have close to that number and try to build Roslyn I get random failures. When I first reported this I was told there was a fix coming to allow a larger number of temp files is that not true? It would certainly cut down on support calls and always being told to clean out my temp folder.

**Comment by davkean** [comment]
@paul1956, which random in particular are you running into? Is there bugs you've filed on it? Can you point me to them?

**Comment by paul1956** [comment]
I reported them on the Microsoft Support Forum https://social.microsoft.com/Forums/en-US/e2946261-000c-4969-acbc-f00df41f7289/vs-2015-was-working-then-stopped?forum=vssetup and someone there recommended I cleanup temp files (I did have 65535 of them). It was also filed on Microsoft Connect https://connect.microsoft.com/VisualStudio/feedback/details/1171345/exception-when-opening-editor

The symptoms vary which is why the issues titles vary but the root cause is the same. It is fixed in Visual Studio 2013 Update 5 but not Visual Studio 2015.

**Comment by davkean** [comment]
Ah, this could be caused by absolutely anything that calls Path.GetTempFileName. ie While we might have fixed the leak that leaked the temp files in this case, or crashed because GetTempFileName threw, there might be other leaks, or other issues due to this. This particular leak is caused by a new change in NuGet 3.0, but is fixed in newer builds.

The fix is easy; clean out your %TEMP% directory.

**Comment by paul1956** [comment]
@davkean  Visual Studio 2013 Update 5 does not cause a build to fail in this exact case with 65535 temp files, with VS2013 Update 5 and an identical solution file, the build succeeds. I don't know how they fixed it. Generally with multi-terabyte driver failing or crashing when there are 65535 temp files seems unacceptable, at least detect it and tell me to clean my temp files. The real solution should be in the GetTempFileName or Visual Studio needs to create its own internal version.

**Comment by davkean** [comment]
@paul1956 Unless you believe it to be Roslyn issue (in which case, file on Github), can you file a bug on [Microsoft Connect](http://connect.microsoft.com/VisualStudio) or use Send-A-Frown with the build issue you encountering?

This issue is tracking the infrastructure for building Roslyn itself - nothing we do to fix this issue, will resolve your problem.

**Comment by paul1956** [comment]
@davkean the Out of Temp Filenames is reported on Microsoft Connect,(#1171345) and Microsoft User/Developer forums and marked as closed. Mark Wilson-Thomas Program Manager Visual Studio Editor Team, believed it is fixed in VS2013 Update 5 and will be fixed in VS2015 Update 1. I did  Send a Frown when it happened and so have others. If your builds are on Update 1 and are seeing the issue someone should reopen the Microsoft Connect issue.so it does get fixed on Update 1.

**Comment by davkean** [comment]
@paul1956 Looked internally, this bug was missed for inclusion as part of Visual Studio 2015, but was fixed as part of Visual Studio 20125 Update 1.

**Comment by davkean** [comment]
Going to close this, as looks like we're out of the woods on these issues, we've moved %TEMP% to be specific per job, and we're deleting it on cleanup.

**Comment by paul1956** [comment]
@davkean I don't understand what you closed. Does this mean you are not building with Update 1 so you hit the same bug or is the bug not really fixed with Update 1? Does your moving %TEMP% only apply to internal builds and normal users building Roslyn will still see it? Please clarify what was closed?

**Comment by davkean** [comment]
@paul1956 This issue that I opened is tracking the Roslyn build infrastructure - and has nothing to do with Visual Studio or the issue you are hitting. 

The issue you are hitting has been fixed for Visual Studio 2015 Update 1. Any communication regarding it is better done on the original Microsoft Connect issue over here: https://connect.microsoft.com/VisualStudio/feedback/details/1171345/exception-when-opening-editor.
