### ISSUE TITLE
VS17.2.3+ Rename symbol -> "rename symbols file" checkbox disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61726]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS1723-Rename-symbol---rename-symbo/10062024)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:approx 17.1.5]
When renaming a symbol one is presented with the option "rename symbols file". In recent versions of VS, this options keeps getting disabled, while in previous versions it would be enabled if the file-name matches that of the symbol.

Steps to reproduce:
1. Create a file A.cs with two classes A and B
2. Start renaming A, and enable "rename symbols file"
3. Exit renaming A, and start renaming B. The option will be disabled (**this is expected**)
4. Exit renaming B, and start renaming A. The option will be disabled (**behaviour differs from previous versions**)

Essentially the current behaviour is:
- Keep previous setting if symbol and file name matches
- Disable if symbol and file name does not match

While the previous behaviour was:
- Keep previous setting if symbol and file name matches
- **Temporarily** disable if symbol and file name does not match

The new behaviour was seen in 17.2.3 and 17.3.0-preview-1.1 (latest public releases as of writing)

---
#### Feedback Bot on 6/5/2022, 07:30 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
I was unable to reproduce this behavior in 17.3 Preview 1

**Comment by AignerGames** [comment]
I use Visual Studio 2022 Version 17.2.4 and have the same issue:
Class and file name match
I press F2 (rename) on the class name -> Rename symbol's file is NOT enabled by default and only the class is renamed
Im 100% sure that this checkbox was enabled by default in the previous versions, because I always renamed the class with F2, very annoying. 

I see this issue was closed, so will it be fixed in a future version?

**Comment by Jabbl** [comment]
This is very much still an issue in 17.2.5:\
![image](https://user-images.githubusercontent.com/23106475/178677113-4b3e3a0f-9750-4c3a-a615-49fad58cb432.png)

This is quite annoying since it leads to file- and symbol names mismatching.

**Comment by Jabbl** [comment]
Updated to 17.3.0 preview 3, but the issue still persists.

Is there a new option somewhere that has defaulted to `false` instead of the old `true`?\
I tried browsing through the settings, but couldn't find anything regarding renaming.

**Comment by R0boC0p** [comment]
Resolved in Version 17.3.4

**Comment by AArtlone** [comment]
@ryzngard I have just updated to 17.3.6 but the issue still persists.
