### ISSUE TITLE
Debugger: A type or generic instantiation needed to evaluate this expression does not exist in the process being debugged.

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#6226]
Maybe this is just a limitation of the debugger, but I ran into it when debugging some code using generics today.

![image](https://cloud.githubusercontent.com/assets/1249087/10651659/e9bdc93e-781e-11e5-9f28-f9aaf107b2a3.png)

Repro:

```CSharp
var tree = CSharpSyntaxTree.ParseText(@"
using System;
using Xunit;

namespace CodeConnect.TestSolution.TestFrameworkComparison
{
[CollectionDefinition(""SharedEndToEndCollection"")]
public class EndToEndCollection : ICollectionFixture<SharedCrossStoreFixture>
    {
        public static void Main()
        {
        }

    }
    public class SharedCrossStoreFixture
    {
    }

    
    public abstract class EndToEndTest<TTestStore, TFixture> : IDisposable
    {
        protected EndToEndTest(TFixture fixture)
        {
        }

        [Fact]
        public virtual void Can_save_changes_and_query()
        {
        }

        public void Dispose()
        {
        }
    }

    [Collection(""SharedEndToEndCollection"")]
    public class SharedInMemoryEndToEndTest : EndToEndTest<string, SharedCrossStoreFixture>
    {
        public SharedInMemoryEndToEndTest(SharedCrossStoreFixture fixture) : base(fixture)
        {
        }
    }

    [Collection(""SharedEndToEndCollection"")]
    public class SharedSqlServerEndToEndTest : EndToEndTest<string, SharedCrossStoreFixture>
    {
        public SharedSqlServerEndToEndTest(SharedCrossStoreFixture fixture) : base(fixture)
        {
        }
    }
}");

MetadataReference[] references = new MetadataReference[]
{
    //Xunit needs this PCL stuff.
    MetadataReference.CreateFromFile(@"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile7\System.Runtime.dll"),
    MetadataReference.CreateFromFile(@"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile7\System.Diagnostics.Debug.dll"),
    MetadataReference.CreateFromFile(typeof(System.Collections.Immutable.ImmutableArray).Assembly.Location),
    MetadataReference.CreateFromFile(typeof(Xunit.FactAttribute).Assembly.Location)
};

var compilation = CSharpCompilation.Create("MyCompilation",
    syntaxTrees: new[] { tree }, references: references);

var errs = compilation.GetDiagnostics().Where(n => n.Severity == DiagnosticSeverity.Error);
Debug.Assert(errs.Count() == 0);

var model = compilation.GetSemanticModel(tree);
var test = tree.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>().First();
var classSymbol = model.GetDeclaredSymbol(test);

var attributeData = classSymbol.GetAttributes().First();

//Cannot peek into arguments
var arguments = attributeData.ConstructorArguments;

```

**Comment by cston** [comment]
@JoshVarty Thanks for reporting the issue. Are you still hitting this with Update 1? There have been fixes for related issues in the debugger, and I have not reproduced the failure with that build.

**Comment by ManishJayaswal** [comment]
@JoshVarty - Pinging again to see if this is still an issue with update1.

**Comment by JoshVarty** [comment]
Sorry for the slow response. I can no longer repro, so it looks like this particular issue was fixed. Thanks guys! :)

**Comment by godlover88** [comment]
I still have this problem, I updated my VS 2015 to update 3 and Roslyn, but nothing changed. Can anybody help me?

**Comment by anirugu** [comment]
I am hitting same issue today in VS 2015, 

var prx = getData();

I can't see the value of prx, the thread has been dispatched in main UI and now I am debugging it and it's showing same issue, Any workaround for this
