### ISSUE TITLE
Visual Basic: "Object initialization can be simplified (IDE0017)" wrong indent with custom tab/indent size

### ISSUE THREAD

**Issue by skurth** [dotnet/roslyn#66071]
**Version Used**: Visual Studio 2022 (17.4.1, also with 17.4.3)

**Steps to Reproduce**:

```
Module Program

  Sub Main(args As String())
    Dim testObj As New Test()
    testObj.TestString = "harr"
    testObj.TestInt = 5
  End Sub

  Private Class Test
    Property TestString As String
    Property TestInt As Integer
  End Class

End Module
```

Tabs settings:
![image](https://user-images.githubusercontent.com/11660701/208616428-213cc748-23df-4e34-af91-08fb3df167be.png)

**Expected Behavior**:
The indent should be correct. In Visual Studio 2019, this worked:
![image](https://user-images.githubusercontent.com/11660701/208616567-9f140de8-5cd3-44ee-920a-9e4897a30d06.png)

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/11660701/208616594-9ad12d2f-83a6-4910-bdac-cd826c90a21e.png)

**Comment by Youssef1313** [comment]
@skurth Can you update to 17.4.3?

I think this issue was fixed and backported to 17.4 (PR: https://github.com/dotnet/roslyn/pull/65382)

**Comment by skurth** [comment]
@Youssef1313 I have updated to 17.4.3 and still have this issue.

**Comment by skurth** [comment]
@Youssef1313 Still have this issue in 17.4.4

**Comment by CyrusNajmabadi** [comment]
@skurth Does this repro with 17.5 or 17.6?

**Comment by skurth** [comment]
@CyrusNajmabadi Works in 17.5 :) Thx!
