### ISSUE TITLE
IntelliSense cannot detect IAsyncEnumerable's yield return type when that parameter is used

### ISSUE THREAD

**Issue by datvm** [dotnet/roslyn#68027]
**Version Used**: 4.5.2-3.23171.7 (d17f7415)

**Steps to Reproduce**:

Put in the following code (in this example it's in the top-level `Program.cs`):

```cs
Console.WriteLine("Hello");
_ = BarAsync();

static async IAsyncEnumerable<Foo> BarAsync()
{
    var tmp = new string[10];
    foreach (var item in tmp)
    {
        yield return new(async s =>
        {
            // Happen here
            await Task.CompletedTask;
            throw new NotImplementedException();
        });
    }
}

record Foo(Func<string, Task<string>> func); // Happen to both Func<> and delegate
```

The code above compiles but at the `// Happen here` line, any attempt to access `s` results in `s` being unknown `?` even though without it, the compiler and IntelliSense correctly detect `s` as `string`.

**Diagnostic Id**: N/A

**Expected Behavior**:

`s` should maintain its type as `string` while typing.

**Actual Behavior**:

Whenever there is an attempt to access `s`, it becomes `?`. This happens to both Visual Studio and VS Code (latest version). If you put in valid code without IntelliSense, it still compiles, for example:

```
yield return new(async s =>
{
    return s.ToUpper(); // Have to manually type it
    await Task.CompletedTask;
    throw new NotImplementedException();            
});
```

Correct behavior when `s` is not being typed:

![image](https://user-images.githubusercontent.com/6388546/235317576-22c6b799-0e03-4b55-893a-f489607b807d.png)

In both VS and VS Code, `s` becomes unknown when any attempt to access it is made:

![image](https://user-images.githubusercontent.com/6388546/235317592-355b9948-fc42-4aa1-9607-a26157380d33.png)

**Comment by datvm** [comment]
Attempt to "navigate" around the issue by declaring a variable does not work as well (note that `s2` now has type of `??` instead of `?`):

![image](https://user-images.githubusercontent.com/6388546/235317764-980f013b-bc5c-4205-adca-f1210b6f2784.png)

However this issue does not happen if `s2` is explicitly typed, maybe because at this time IntelliSense trusts that the error would be thrown earlier and `s2` doesn't need to be guessed:

![image](https://user-images.githubusercontent.com/6388546/235317800-5d2a0996-2c71-4574-867c-2e8fcf97bb00.png)

**Comment by datvm** [comment]
Hi any update on this? This is quite annoying to work with because I keep losing code suggestion.

Thanks.

**Comment by CyrusNajmabadi** [comment]
@datvm There is no update on this.  We would take a community contribution to fix this though, if you were interested :)

**Comment by datvm** [comment]
@CyrusNajmabadi  thanks. I hope someone can take a look at this. Unfortunately I am quite unfamiliar with Roslyn so I cannot really help :(

**Comment by CyrusNajmabadi** [comment]
Moving to compiler.  We call into their apis for semantic information.

**Comment by jcouv** [comment]
Fix was merged into 17.13p2. Thanks for reporting this issue @datvm !

**Comment by datvm** [comment]
@jcouv Thank you and congrats, that's awesome! I assume this issue is not related to #72571 and it's not fixed as a result of this fix then?

**Comment by jcouv** [comment]
> I assume this issue is not related to https://github.com/dotnet/roslyn/issues/72571 and it's not fixed as a result of this fix then?

That issue is not related. The issue here, which was fixed, relates to a lambda in a `yield return`.
