### ISSUE TITLE
`GetTypeInfo` returns `TypeInfo` with null as `Type` for `ImplicitObjectCreationExpression` inside `CollectionExpression`

### ISSUE THREAD

**Issue by csaba-sagi-sonarsource** [dotnet/roslyn#70041]
**Version Used**: 

**Steps to Reproduce**:

Call semanticModel.GetTypeInfo for the `ImplicitObjectCreationExpression` from the snippet below.
```
class SomeClass
{
    private static Line[] SomeMethod() => [new(0)];

    private class Line
    {
        public Line(int length)
        {
        }
    }
}
```
**Expected Behavior**:
The type should be correctly retrieved.
**Actual Behavior**:
The type is null.

**Comment by CyrusNajmabadi** [comment]
This is correct, an implicit objet has no type on it's own.  it needs a target type it is converted to to actually determine what type it is.  Check TypeInfo.ConvertedType instead.

**Comment by csaba-sagi-sonarsource** [comment]
@CyrusNajmabadi 
Yes, and for the aforementioned scnippet `TypeInfo.ConvertedType` is null too.

Also, what I would like to mention is that Type is not null for `ImplicitObjectCreationExpression` in the following snippet:

```
public record struct RecordStruct
{
    private class Line
    {
        public int Value;
    }

    public Line Create() => new() { Value = 1 };
}
```
I expect the behaviour to be the same for both calls.

**Comment by CyrusNajmabadi** [comment]
reactivating for compiler investigation.

**Comment by jcouv** [comment]
This was fixed as part of https://github.com/dotnet/roslyn/pull/69852 which includes multiple tests verifying that:
1. the `.Type` is `null`
2. the `.ConvertedType` is the proper/non-null converted type

**Comment by csaba-sagi-sonarsource** [comment]
@jcouv,

Out of curiosity, can you tell me why `Type` is not null for the second snippet I posted and why it is planned to be null for the first one?

**Comment by sebastien-marichal** [comment]
Hello @jcouv,

I tested with the latest preview version of Visual Studio (Preview 5) and am still facing the same issue. `ConvertedType` returns `null` for `ImplicitObjectCreationExpression` in the snippet provided by @csaba-sagi-sonarsource.

Is the fix in #69852 has been released yet?
