### ISSUE TITLE
Roslyn fails to verify nullable reference types' safety in collection expressions

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#72142]
**Version Used**: 
```
Microsoft Visual Studio Professional 2022
Version 17.10.0 Preview 1.0
VisualStudio.17.Preview/17.10.0-pre.1.0+34607.79
Microsoft .NET Framework
Version 4.8.09037
```

**Steps to Reproduce**:

Compile and run the following code:
```cs
using System;
using System.Collections.Generic;
#nullable enable

List<string> list = [null];
Console.WriteLine(list[0].Length);
```

[sharplab.io](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKHQAYACdbAFgG4CBiGAVwBsmJgmBTEjmNzgggBkoAZwAuAHnJEAfCSaixJALwkA2oxYBdGoWwBOABQLxaoloB0gngHMxACwCUVIA==)

**Expected Behavior**:
There should be a warning about mismatching nullability somewhere on the line `List<string> list = [null];`

**Actual Behavior**:
No warnings at all.
The program crashes at runtime with a `NullReferenceException`

**Comment by jaredpar** [comment]
@cston believed this is fixed now. Can we close?

**Comment by cston** [comment]
This is still an issue. The compiler is not checking the nullability for elements of collection expressions for target types that implement `IEnumerable` and do not use `[CollectionBuilder]`. See https://github.com/dotnet/roslyn/issues/68786.
