### ISSUE TITLE
Visual Studio operates on outdated cache after git pull again

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73455]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-operates-on-outdated-cache/10649921)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:a few versions ago, maybe 17.8]
This is the same issue as https://developercommunity.visualstudio.com/t/Visual-Studio-operates-on-outdated-cache/10161097 again since the same problem has come back:

When you git pull changes to files currently not opened in the editor and then run a codefix on project or solution level that will modify a file that was changed by the git pull, the codefix will undo the changes you’ve previously git pull’d.

In addition, if a file currently opened in the editor references members that are currently not open in the editor and were added in the latest git pull, those will have a red squiggly. The squiggly disappears if you open the file containing the added members.

In addition, even though the build worked fine, if you start debugging, halt at a breakpoint and then try to take a step, E&C will report errors due to changes you've supposedly made that cannot be applied.

To reproduce:
1. Download and extract attached Repro.zip
2. Navigate to the Checkout directory and open Repro.sln
3. Open Program.cs in the editor and perform a build
4. Open the git changes blade and click on pull
5. In Program.cs, bring up the light bulb menu on the second line where it says using System.IO;
6. Navigate to Remove Unnecessary Usings and in the preview pane, click on Fix all occurrences in: Project
7. Accept the proposed changes.
8. Review the changes made in the git changes blade, specifically OtherFile.cs.
8. The unnecessary usings were removed but the comment inside the OtherFile class, // these changes will be undone after applying the codefix, that was pulled in step 4, was removed as well.

---
#### Feedback Bot on 5/1/2024, 09:03 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Suchiman** [comment]
Here's the [Repro.zip](https://github.com/dotnet/roslyn/files/15305828/Repro.zip) again

**Comment by Cosifne** [comment]
Might related to workspace & PS.

**Comment by vortex852456** [comment]
Is there any workaround beside restarting visual studio or reloading the solution after the pull operation?

**Comment by Dreamescaper** [comment]
That is very annoying. Half the times I switch a branch I need to re-open VS for it to work again :(

**Comment by Rekkonnect** [comment]
This also affects the quick code search feature that opens with `Ctrl+T`, which will highlight the span as discovered before pulling the code. I suspect this is an issue affecting features across the board.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/75815

**Comment by Dreamescaper** [comment]
The issue is still present in VS 17.13 Preview 2.

**Comment by Suchiman** [comment]
@CyrusNajmabadi please reopen, the issue still occurs exactly as described in the repro steps as of VS 17.13 Preview 4

**Comment by CyrusNajmabadi** [comment]
@ToddGrun @jasonmalinowski  ptal.  Your fix doesn't seem to have addressed this according to users.

**Comment by ToddGrun** [comment]
Worked with VS-platform on this and they merged a fix in on their side last night. I've verified this works in today's VS build, and should be available publicly in 17.14 Preview 2
