### ISSUE TITLE
"New Line" options are not taking effect in VS 2022 Community (Version 17.12.0 Preview 1.0)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75393]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/New-Line-options-are-not-taking-effect/10725213)._

---
[regression] [worked-in:Version 17.11]
Despite having all of the "put X on a new line" options turned off, the auto complete and format document functionality is putting the brackets on new lines. I have had these turned off for years and they worked fine until this most recent VS 2022 community update.

---
#### Feedback Bot on 8/19/2024, 02:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Sam Harwell [MSFT] on 8/21/2024, 10:16 AM: 

<p>Hi <a target='_blank' href="https://developercommunity.visualstudio.com/user/341655/profile">Mitchell Russell</a>,</p>
<p>Thank you for reporting this issue. Typically, when this occurs one of two things has occurred:</p>
<ol>
<li>The user has a <strong>.editorconfig</strong> file in the directory with the source file, or in one of its parent folders. Options defined in this file override options found in <strong>Tools → Options…</strong>, so you would need to review that file for consistency with the desired settings.</li>
<li>The project sets the property <code>&lt;EnableCodeStyleInBuild&gt;true&lt;/EnableCodeStyleInBuild&gt;</code>. When this property is enabled, the formatter ignores all options from <strong>Tools → Options…</strong> to ensure the behavior during builds is consistent with the IDE experience. When this property is enabled, customized options must be defined in <strong>.editorconfig</strong> or <strong>.globalconfig</strong>.</li>
</ol>
<p>Documentation for these files can be found here:<br>
<a target='_blank' href="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files">https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files</a></p>
<p>If you have further questions, can you provide more information about which of these scenarios you are encountering?</p>
<p>Thank you,<br>
Sam Harwell</p>

#### Mitchell Russell on 9/15/2024, 03:22 PM: 

(private comment, text removed)
#### Mitchell Russell on 9/22/2024, 09:03 AM: 

<p>Can we please get this elevated or some focus on it? Nothing I’ve tried has worked.</p>

#### Feedback Bot on 8/28/2024, 00:51 AM: 

<p>We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.</p>

#### Mitchell Russell on 9/10/2024, 07:37 PM: 

<p><a target='_blank' href="/user/13574">Sam Harwell [MSFT]</a> Sorry, I just saw this. I didn’t get an email when you replied last week.</p>
<p>This is happening in <em>all</em> of my projects, suddenly, when I upgraded to 17.12.0 Preview 1.0, with no other changes having occurred. I did not add an editorconfig or change anything else.</p>
<p>Is there anything else I can check? It’s occurring on two different computers after the upgrade.</p>

#### Mitchell Russell on 9/22/2024, 08:55 AM: 

(private comment, text removed)
#### Feedback Bot on 10/4/2024, 10:58 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by caliberdigitalllc** [comment]
my very own VS 2022 Bug thread :) Such a proud father. (I'm Mitch).

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/75417

**Comment by caliberdigitalllc** [comment]
> Fixed by [#75417](https://github.com/dotnet/roslyn/pull/75417)
@sharwell @tmat  - the latest version of VS that says it includes this fix, does not fix the problem. Can we re-open and keep working on this? I tried it across 3 different projects and the new line formatting options continue to be ignored.

**Comment by caliberdigitalllc** [comment]
@sharwell  @tmat  - tagging you again as this issue still remains in the very latest preview across multiple computers and multiple projects.

**Comment by RoLYroLLs** [comment]
This is happening with VS 17.12 GA. Just downloaded it and it's always adding a new line before an open bracket, no matter what setting I have in options. I even tried resetting all options to default, in case my settings were corrupt, and no matter what options I set, it continues to do the same.

**Comment by caliberdigitalllc** [comment]
> This is happening with VS 17.12 GA. Just downloaded it and it's always adding a new line before an open bracket, no matter what setting I have in options. I even tried resetting all options to default, in case my settings were corrupt, and no matter what options I set, it continues to do the same.

yeah I've been tagging @sharwell  and @tmat  but they aren't seeing the tags. I will start a new issue and try and get them to reopen this.

**Comment by caliberdigitalllc** [comment]
@RoLYroLLs  - opened https://github.com/dotnet/roslyn/issues/75881 in hopes they come reopen this issue.

**Comment by GF-Huang** [comment]
17.12.2 issue still.
