### ISSUE TITLE
Refactoring shows doubled "Preview, fix all in" links

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#75633]
**Version Used**: 17.12 Preview 3.0

This happened several times today on two machines.

![Image](https://github.com/user-attachments/assets/72c8d8cf-d8e4-48bb-b88b-1d4f6301506a)

**Comment by DoctorKrolic** [comment]
I've seen this for quite some time for quite many versions (probablt starting somewhen from 17.2), but I never found a stable way to reproduce it

**Comment by CyrusNajmabadi** [comment]
I believe hti was fixed by platform.

**Comment by jnm2** [comment]
This is still happening with 17.13.0 Preview 2.1.

![Image](https://github.com/user-attachments/assets/a63efd8b-6db0-4e26-9abf-f319f8ee6857)

**Comment by jnm2** [comment]
Still happening with 17.14.0 Preview 2.0.

![Image](https://github.com/user-attachments/assets/6a172034-5aa1-4419-af45-24c7be4ba623)
