### ISSUE TITLE
workspace.OpenSolutionAsync locked after update code analysis libraries on vs 17.14

### ISSUE THREAD

**Issue by cgamberini** [dotnet/roslyn#78766]
On  vs17.14 my code analysis library did not work, so i updated the libraries to the last version as below:

```
<PackageReference Include="Microsoft.Build.Locator" Version="1.9.1" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.14.0" />
<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.14.0" />
<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.5" />
<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="9.0.5" />
<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.5" />
<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.5" />
<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
<PackageReference Include="NuGet.Frameworks" Version="6.14.0" />
<PackageReference Include="NuGet.ProjectModel" Version="6.14.0" />
<PackageReference Include="System.Security.Cryptography.Pkcs" Version="9.0.5" />
```

now if i call `await workspace.OpenSolutionAsync(solutionFilePath);` it does not return, in the console there are no errors.

downgrading net sdk using old version this code does not solve the problem.

`MSBuildLocator.RegisterMSBuildPath("C:\Program Files\dotnet\sdk\8.0.313");`

any suggestions?

NB. `solutionFilePath` target an ASP.NET MVC application build with .NET framework 4.7.2

Thanks

**Comment by jasonmalinowski** [comment]
Microsoft.Build.Locator is no longer needed for newer versions of MSBuildWorkspace, so you can delete that.

Otherwise if you can take a memory dump of the hung process (and any child processes), we can look at those further. File a feedback ticket on Visual Studio Developer community and attach any dump files to that. Include a link over here so I can find it and then I can take a look.

**Comment by cgamberini** [comment]
i opened a ticked on developer community: https://developercommunity.visualstudio.com/t/workspaceOpenSolutionAsync-locked-after/10916274, in the linked issue i attached the dump of the process

**Comment by jasonmalinowski** [comment]
@cgamberini So when you're hitting the hang, you should see that your process has a child process named Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe -- can you share a dump of that too? For a bunch of reasons we do the actual processing of the build in another process, and I see your process has called out to that and is just waiting for a response.

**Comment by cgamberini** [comment]
@jasonmalinowski attach dump file in comment gave me errors, so i uploaded on filebin: https://filebin.net/xvnelnot7uf2mu11

**Comment by jasonmalinowski** [comment]
Thanks for the dump -- that was quite helpful. The problem here is two things doing not great things interacting badly:

1. Your build is using BundlerMinifier; a build task there is logging directly to the console rather than through any MSBuild mechanism.
2. We were launching the BuildHost processes redirecting standard output. We originally were using this as a way to communicate with it; we moved to a pipe, but left the redirection in place...and now nothing was reading.

So eventually BundlerMinifier was writing enough that the stream got full, and since we weren't flushing it, it'd deadlock.

**Comment by cgamberini** [comment]
Thanks @jasonmalinowski , the problem will be solved in next release?

As workaround i have to temporary disable BundlerMinifier?

**Comment by jasonmalinowski** [comment]
I've merged the fix into our side; the next release would have the fix. If you needed something shorter term either you'd have to try picking up nighty builds (I'm not sure where we publish those right now...), or just disable BundlerMinifier. I'm not familiar with that project but you might be able to condition on the DesignTimeBuild MSBuild property which would be set to true when we're loading the project.

**Comment by cgamberini** [comment]
Hi @jasonmalinowski, sorry for the mention.

I still have the issue with the vs version 17.14.10 and disable BundlerMinifier does not solve. what's the vs release to wait for the solution?

Thanks

**Comment by jasonmalinowski** [comment]
Your version of VS won't matter, unless you're running that code inside a Visual Studio extension. What you need is an upgrade to your NuGet packages to a newer 5.0 version; but we don't have those uploaded yet. I think the hope is we'll have them out in a week or two.

**Comment by cgamberini** [comment]
Hi @jasonmalinowski , i updated my application to vs2026, updating all packages but the problem still remain.

as msbuild path i registered the new vs2026 location:

```
var msBuildPath = @"C:\Program Files\Microsoft Visual Studio\18\Enterprise\MSBuild\Current\Bin";
MSBuildLocator.RegisterMSBuildPath(msBuildPath);
```

`workspace.OpenSolutionAsync` remain locked

here the dump of `Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe`

https://filebin.net/9ptxs5oo09fir5iw/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.DMP

**Comment by jasonmalinowski** [comment]
@cgamberini Sorry about the slow response here -- for some reason GitHub didn't notify me on this one. And it appears your dump file isn't available anymore. 😦 The rest of a week is a holiday in the US, but we can take a look next week if you're able to get a new dump. Also feel free to email me the dump link if you'd like; my Microsoft email is in my GitHub profile.

The MSBuildLocator use isn't doing anything anymore: since we're running all our MSBuild interaction in another process you can simply delete that code.

**Comment by cgamberini** [comment]
Hi @jasonmalinowski i have solved the issue updating the project to net10 and not only the packages.  

Now i does not have an older version to reply the issue.

to summarize the environment to reply the issue:

- visual studio 2022 or visual studio 2026
- **console application net framework 4.7.1**
- packages updated to latest version
- call `workspace.OpenSolutionAsync` targeting a solution with BundlerMinifier

now i updated to this working environment: 
- visual studio 2026
- **console application net10**
- packages updated to latest version
- call `workspace.OpenSolutionAsync` targeting a solution with BundlerMinifier

**Comment by jasonmalinowski** [comment]
I'll close this out since there's not much to do at this point. Feel free to reactivate if you get it happening again.
