### ISSUE TITLE
look at memory consumption by SymbolTreeInfo and see whether it can be reduced.

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#8172]
I just took snapshot of Roslyn (open) in vs for something else, and saw this.

![image](https://cloud.githubusercontent.com/assets/1333179/12569725/409e3dda-c386-11e5-8619-9fd09a027156.png)

it looks like top 2 entry consumes about 100MB memory.

**Comment by CyrusNajmabadi** [comment]
SymbolTreeInfo holds onto the BKTree.  So these values shoudln't be summed.

These are the indices used for add-using.  For something the size of Roslyn, these sizes do not surprise me.

**Comment by CyrusNajmabadi** [comment]
Note: it's potentially possible we could get rid of the quick map inside SymbolTreeInfo and instead just use the BKTree instead.  If you search the BKTree with a tolerance of 0, then you get the same results that you would have if you searched the rest of the SymbolTreeInfo.  I'd be happy to try this out tomorrow.

**Comment by Pilchie** [comment]
Please take a look and see if we should do anything here.

**Comment by CyrusNajmabadi** [comment]
I don't see any issue here.  This seems reasonable for a project the size of Roslyn.

**Comment by heejaechang** [comment]
@CyrusNajmabadi @KevinH-MS @Pilchie if you guys think the memory size is okay, then just close the bug. added @KevinH-MS since this is VM increase, so he probably need to get exception for RI.

**Comment by heejaechang** [comment]
@rchande Ravi, this might be the cause of VM you are looking for, just for FYI. it might not have affected RPS at all.

**Comment by CyrusNajmabadi** [comment]
Adding 30mb to be able to fuzzy search all of Roslyn (both the source as well as all metadata) is in line with my expectations and seems reasonable to me.

**Comment by heejaechang** [comment]
@CyrusNajmabadi sure, i am not saying it is too much added or not, I simply opened the bug since they were top 2 and exclusive memory is 70MB. regardless it is new thing added or something always has been existed, they are still top 2 memory consumer.

the reason I mentioned RPS was I happen to got email about VM increase in Roslyn for RI. might or might not related like I said. since VM increase investigation is always hard, having any pointer is helpful for the one who investigate it.

**Comment by CyrusNajmabadi** [comment]
> I simply opened the bug since they were top 2 and exclusive memory is 70MB.

Ok.  So what would you like to be done with this bug?

**Comment by heejaechang** [comment]
@CyrusNajmabadi if ide team thinks the memory consumed is expected and perf team is okay with it (since they need to deal with RPS. by the way, I am not in perf team), just close the bug.

**Comment by heejaechang** [comment]
@rchande @CyrusNajmabadi giving this to Ravi since he will take a look at a way to get back some memory in VS.

by the way, next sprint I work on diagnostic engine out of proc, so that might save some memory off VS.

also, I have this. https://github.com/dotnet/roslyn/issues/6276 opened. which can also improve VM situation a bit.

**Comment by rchande** [comment]
@KevinH-MS Let's talk about this at perf swat tomorrow.

**Comment by DustinCampbell** [comment]
@rchande -- is this something we need to keep in 1.2? Do you have any update?

**Comment by Pilchie** [comment]
I suspect this was addressed by the switch to Metadata only reading...

**Comment by CyrusNajmabadi** [comment]
Unlikely.  Switching to metadata only means we don't hold onto PESymbols.  However, we will still have the memory overhead for the BKTrees themselves.

**Comment by CyrusNajmabadi** [comment]
Closing as i don't think there's anything to do here.  Memory usage is in line with my expectations, and we will also benefit from OOP as this memory will be in the server, and not taking up VS vm space.
