### ISSUE TITLE
ExpressionCompiler and friends build against OutDir causing warnings in VS

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8983]
Despite a [statement](https://github.com/dotnet/roslyn/pull/8615#discussion_r52698379) by @amcasey to the contrary, there does appear to be race in the build when ExpressionCompiler and other projects build against the outdir:

```
Severity	Code	Description	Project	File	Line	Source	Suppression State
Warning		The referenced component 'D:\Roslyn\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	CSharpResultProvider.Portable			Build	
Warning		The referenced component 'D:\Roslyn\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	ExpressionCompiler			Build	
Warning		The referenced component 'D:\Roslyn\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	BasicExpressionCompiler			Build	
Warning		The referenced component 'D:\Roslyn\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	CSharpExpressionCompiler			Build	
Warning		The referenced component 'D:\Roslyn\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	ResultProvider.Portable			Build	
Warning		The referenced component 'D:\Roslyn\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	BasicResultProvider.Portable			Build	
```

![image](https://cloud.githubusercontent.com/assets/1103906/13201474/bfd1ef88-d827-11e5-88ec-44fb712ce6d5.png)

**Comment by amcasey** [comment]
`Concord.csproj` builds that file after `CoreCompile`:
```
  <Target Name="IlasmPortable" 
          AfterTargets="CoreCompile"
          Inputs="@(ConcordAssemblies->'$(ConcordDir)%(Identity).Portable.il')"
          Outputs="$(OutDir)%(Identity).dll">
    <Exec Command="$(MSBuildFrameworkToolsPath)ilasm.exe /dll /quiet &quot;/output:$(OutDir)@(ConcordAssemblies).dll&quot; &quot;$(ConcordDir)@(ConcordAssemblies).Portable.il&quot;" />
    <Exec Command="&quot;$(FakeSignToolPath)&quot; &quot;$(OutDir)@(ConcordAssemblies).dll&quot;" />
  </Target>
```

Each EE project (other than the shprojs) depends on `Concord.csproj`.  For example, from `ExpressionCompiler.csproj`:
```
    <ProjectReference Include="..\Concord\Concord.csproj">
      <Project>{5002636a-fe8d-40bf-8818-ab513a2194fa}</Project>
      <Name>Concord</Name>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
```

@davkean have I misunderstood how the `Exec` task works in msbuild?  Does it return immediately, rather than waiting for the process to exit?  What does it do if the process fails?

**Comment by davkean** [comment]
I think this is the interaction on how references are resolved, this doesn't necessarily result in a build. 

To repro, delete this dll from the output directory and open VS.

**Comment by amcasey** [comment]
@davkean Does this only affect the in-proc build?  As soon as I build the `ExpressionCompiler` project, the binary is restored.  Is it just a matter of using a different `AfterTargets` to make the in-proc build happy?

**Comment by amcasey** [comment]
I tried `BuildDependsOn` and `AfterTargets="BeforeBuild"`, but VS still won't restore the missing binary.  Is there some way to get the msbuild log for the in-proc build so I can see which targets it's using?

**Comment by davkean** [comment]
I suspect this isn't a build per se, it's going through the RAR task directly. Come see me later and I'll show you the code.

**Comment by amcasey** [comment]
@davkean Can you confirm that this is VS-only?  It works on the command line?

**Comment by davkean** [comment]
This is VS-only.

**Comment by amcasey** [comment]
As we discussed offline, the correct fix is probably to find the property that would allow `Concord.csproj` to declare these binaries as outputs.  (Right now, only the targets do so.)

**Comment by davkean** [comment]
This was made worse recently with now the double amount of warnings. This isn't very friendly for someone who's new to Roslyn to have Roslyn.sln with a bunch of warnings when its opened for the first time.

**Comment by KevinH-MS** [comment]
I believe this is fixed with #12497.
