### ISSUE TITLE
Release branches should remove myget feeds

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#9252]
All uses of `myget.org` should be removed from our [Nuget.config](https://github.com/dotnet/roslyn/blob/master/NuGet.Config) file.  Packages can be deleted from `myget.org` at any time hence using those feeds compromises our ability to do historical builds of our releases.

**Comment by jaredpar** [comment]
Note: we should be careful to re-add `myget.org` in the master branch once the change to remove them flows stabilization -> master.  Or even better we should consider adding `Nuget.stabilization.config` so this gets done on a permanent basis.

**Comment by davkean** [comment]
Agreed. Let's make NuGet.config branch specific.

**Comment by dpoeschl** [comment]
So this would apply to all release branches?

Tagging @jasonmalinowski -- it sounded like he had an opinion about this.

**Comment by jasonmalinowski** [comment]
@jaredpar: any sense how we should do this since we're depending upon .NET CLI packages, which don't exist on nuget.org when we're spinning our final build? Perhaps there's a better/different solution with the stuff you're doing now?

**Comment by jaredpar** [comment]
Let's revisit this in a week.  There is a larger infrastructure push going on that will effect this item.

**Comment by tannergooding** [comment]
@jaredpar, @jasonmalinowski. I believe this has been resolved by our move to dotnet.myget.org, correct?

**Comment by jasonmalinowski** [comment]
Not really. The intent of this was that shipping branches should be guaranteed to not have stuff pulled out. In practice dotnet.myget.org still doesn't make such a guarantee.

**Comment by jasonmalinowski** [comment]
Thinking about this: this configuration isn't a branch-specific statement, but rather code-specific statement. A newly-created release branch will not conform to not having myget feeds, and also as we create new branches from other release branches we want the "it doesn't depend on myget"-ness to flow along.

Is there any reason we shouldn't just make a work item towards the end of a release to just delete the myget feed references, and any time we need them again they can be added by the developer re-creating the dependency? This would nicely double as a garbage collector of our feeds, and it also means that if we got rid of myget feeds in servicing branches and those flowed to master, then master doesn't have the dependencies either. Thus at any point in time we actually know what our dependencies are.

The only downside I see is it means whoever merges the deletion of a myget feed in some servicing branch may have to restore it in master. I'm OK signing up infrastructure to do that.

Thoughts @jaredpar? I agree on the idea behind this, just want to form this bug into something actionable and also granular enough to make progress.
