### ISSUE TITLE
OpenSourceDebugPackage did not load correctly

### ISSUE THREAD

**Issue by romanov** [dotnet/roslyn#928]
Hello.

1. I've installed VS2015 on Windows 10 (Hyper-V)
2. Installed SDK
3. Cloned repo
4. Made some changes in Microsoft.CodeAnalysis.CSharp
5. Builded everything
6. Ran OpenSourceDebugPackage

No effect inside it and:
![error1](https://cloud.githubusercontent.com/assets/644179/6412065/43f7504e-be90-11e4-86e0-08ac6b23919f.png)

Thank you for any help.

**Comment by Pilchie** [comment]
@KevinRansom or @jaredpar care to take a look?

**Comment by romanov** [comment]
Same story on Windows 8.1 x64

**Comment by petr-k** [comment]
Same here.

**Comment by christopherpaul** [comment]
I'm having the same problem (Windows 7 here). The same error dialog, and the debugger shows that the DLLs from my build aren't being loaded by the experimental VS instance.

The error in ActivityLog.xml is:

    <entry>
      <record>3132</record>
      <time>2015/03/22 11:02:07.446</time>
      <type>Error</type>
      <source>VisualStudio</source>
      <description>CreateInstance failed for package [OpenSourceDebugPackage]</description>
      <guid>{7922692F-F018-45E7-8F3F-D3B7C0262841}</guid>
      <hr>80131040</hr>
      <errorinfo>Could not load file or assembly 'OpenSourceDebug, Version=0.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)</errorinfo>
    </entry>

I can supply the full ActivityLog.xml if required.

Looking at the assembly in question, its version number is 42.42.42.42, which seems odd. The same goes for other assemblies produced by the build - e.g. Microsoft.CodeAnalysis.dll.

**Comment by alexsorokoletov** [comment]
I have the same problem. Version 42.42.42.42 is generated during build, and it looks like we're missing assembly redirect or so.

**Comment by jaredpar** [comment]
Fix is in review for this at PR #1527.

**Note:** Just syncing to this fix may not be sufficient if you have previously run into this error.  Please additionally run the following command from a VS command prompt:

> devenv /rootSuffix Roslyn /resetSkipPkgs

**Comment by romanov** [comment]
@jaredpar soon to be in master branch? Thx.

**Comment by jaredpar** [comment]
@romanov yep. Just have to get the necessary sign offs.

**Comment by jaredpar** [comment]
Fixed via https://github.com/dotnet/roslyn/commit/8cda04e7151dadaae93f6e0ce2db20084a6e069d

**Comment by christopherpaul** [comment]
Sadly, the fix doesn't fully solve the problem. Although the experimental VS instance no longer complains about the package, all the assemblies other than the OpenSourceDebug assembly are loaded from the VS install directory rather than the VSIX that I'm trying to debug. The debugger rightly complains that it can't load symbols:

![image](https://cloud.githubusercontent.com/assets/6624896/6984538/cd0f8aca-da21-11e4-9b1c-c519880ffd57.png)

Looking in the Modules window confirms this:
![image](https://cloud.githubusercontent.com/assets/6624896/6984575/2bcda02e-da22-11e4-89ab-7333c579cf16.png)

I thought this might be a glitch in my particular setup, but it's the same story on a VS2015 CTP6 Azure VM.

Should I raise a separate issue for this?

**Comment by jaredpar** [comment]
@christopherpaul yes please file a different issue for this.

CC @jasonmalinowski in case he has an idea what is going on here.

**Comment by christopherpaul** [comment]
@jaredpar OK, I've raised #1781.
